// frontend-angular/src/app/views/admin/ip-blacklist-settings/ip-blacklist-settings.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatInputModule } from '@angular/material/input';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import { MatChipsModule } from '@angular/material/chips';
import { MatIconModule } from '@angular/material/icon';
import { MatDividerModule } from '@angular/material/divider';
import { COMMA, ENTER } from '@angular/cdk/keycodes';
import { MatChipInputEvent } from '@angular/material/chips';
import { GlobalStateService } from '../../../services/global-state.service';
import { ApiService } from '../../../services/api.service';
import { SnackbarService } from '../../../services/snackbar.service';

@Component({
  selector: 'app-ip-blacklist-settings',
  standalone: true,
  imports: [
    CommonModule, FormsModule, MatCardModule, MatButtonModule,
    MatInputModule, MatFormFieldModule, MatSlideToggleModule,
    MatChipsModule, MatIconModule, MatDividerModule
  ],
  template: `
    <div class="container">
      <mat-card class="form-card">
        <mat-card-header>
          <mat-card-title>IP 黑名单设置</mat-card-title>
          <span class="spacer"></span>
          <button mat-raised-button color="primary" (click)="save()" [disabled]="state.loading()">
            保存
          </button>
        </mat-card-header>
        <mat-card-content>
          <div class="alert info mb-3">
            <div><strong>作用范围：创建邮箱地址、发送邮件、外部发送邮件 API、用户注册、验证码验证</strong></div>
            <div>• IP 黑名单：支持文本匹配或正则表达式</div>
            <div>• ASN 组织：根据运营商/ISP 拉黑</div>
            <div>• 浏览器指纹：根据浏览器指纹拉黑</div>
            <div>• 每日限流：限制单个 IP 地址每天最多请求次数</div>
          </div>

          <div class="setting-row mb-3">
            <mat-slide-toggle [(ngModel)]="enabled">启用 IP 黑名单</mat-slide-toggle>
            <span class="hint">阻止匹配黑名单的 IP 访问限流 API</span>
          </div>

          <mat-form-field appearance="outline" class="full-width mb-3">
            <mat-label>IP 黑名单匹配模式</mat-label>
            <mat-chip-grid #chipGrid1>
              @for (item of ipBlacklist; track item) {
                <mat-chip-row (removed)="removeItem(ipBlacklist, item)" [disabled]="!enabled">
                  {{item}}
                  <button matChipRemove><mat-icon>cancel</mat-icon></button>
                </mat-chip-row>
              }
            </mat-chip-grid>
            <input matInput [matChipInputFor]="chipGrid1" [matChipInputSeparatorKeyCodes]="separatorKeyCodes"
                   (matChipInputTokenEnd)="addItem(ipBlacklist, $event)" [disabled]="!enabled"
                   placeholder="输入匹配模式（例如：192.168.1）">
          </mat-form-field>

          <mat-form-field appearance="outline" class="full-width mb-3">
            <mat-label>ASN 组织（运营商）黑名单</mat-label>
            <mat-chip-grid #chipGrid2>
              @for (item of asnBlacklist; track item) {
                <mat-chip-row (removed)="removeItem(asnBlacklist, item)" [disabled]="!enabled">
                  {{item}}
                  <button matChipRemove><mat-icon>cancel</mat-icon></button>
                </mat-chip-row>
              }
            </mat-chip-grid>
            <input matInput [matChipInputFor]="chipGrid2" [matChipInputSeparatorKeyCodes]="separatorKeyCodes"
                   (matChipInputTokenEnd)="addItem(asnBlacklist, $event)" [disabled]="!enabled"
                   placeholder="输入 ASN 组织名称">
          </mat-form-field>

          <mat-form-field appearance="outline" class="full-width mb-3">
            <mat-label>浏览器指纹黑名单</mat-label>
            <mat-chip-grid #chipGrid3>
              @for (item of fingerprintBlacklist; track item) {
                <mat-chip-row (removed)="removeItem(fingerprintBlacklist, item)" [disabled]="!enabled">
                  {{item}}
                  <button matChipRemove><mat-icon>cancel</mat-icon></button>
                </mat-chip-row>
              }
            </mat-chip-grid>
            <input matInput [matChipInputFor]="chipGrid3" [matChipInputSeparatorKeyCodes]="separatorKeyCodes"
                   (matChipInputTokenEnd)="addItem(fingerprintBlacklist, $event)" [disabled]="!enabled"
                   placeholder="输入指纹 ID">
          </mat-form-field>

          <mat-divider class="mb-3"></mat-divider>

          <div class="setting-row mb-3">
            <mat-slide-toggle [(ngModel)]="enableDailyLimit">启用每日请求限流</mat-slide-toggle>
            <span class="hint">限制每个 IP 地址每天的 API 请求次数</span>
          </div>

          <mat-form-field appearance="outline" class="full-width">
            <mat-label>每日请求次数上限</mat-label>
            <input matInput type="number" [(ngModel)]="dailyRequestLimit" [disabled]="!enableDailyLimit"
                   min="1" max="1000000" placeholder="输入限制次数（例如：1000）">
          </mat-form-field>
        </mat-card-content>
      </mat-card>
    </div>
  `,
  styles: [`
    .container { display: flex; justify-content: center; padding: 20px; }
    .form-card { max-width: 600px; width: 100%; }
    .full-width { width: 100%; }
    .mb-3 { margin-bottom: 12px; }
    .alert { padding: 12px 16px; border-radius: 4px; line-height: 1.8; }
    .alert.info { background-color: #e3f2fd; color: #1976d2; }
    .setting-row { display: flex; align-items: center; gap: 8px; }
    .hint { font-size: 12px; color: #666; }
    .spacer { flex: 1; }
    mat-card-header { display: flex; align-items: center; padding: 16px; }
  `]
})
export class IpBlacklistSettingsComponent implements OnInit {
  state = inject(GlobalStateService);
  private api = inject(ApiService);
  private snackbar = inject(SnackbarService);

  separatorKeyCodes = [ENTER, COMMA];
  enabled = false;
  ipBlacklist: string[] = [];
  asnBlacklist: string[] = [];
  fingerprintBlacklist: string[] = [];
  enableDailyLimit = false;
  dailyRequestLimit = 1000;

  async ngOnInit() {
    await this.fetchData();
  }

  async fetchData() {
    try {
      const res = await this.api.fetch<any>('/admin/ip_blacklist/settings');
      this.enabled = res.enabled || false;
      this.ipBlacklist = res.blacklist || [];
      this.asnBlacklist = res.asnBlacklist || [];
      this.fingerprintBlacklist = res.fingerprintBlacklist || [];
      this.enableDailyLimit = res.enableDailyLimit || false;
      this.dailyRequestLimit = res.dailyRequestLimit || 1000;
    } catch (error: any) {
      this.snackbar.error(error.message || '获取设置失败');
    }
  }

  addItem(list: string[], event: MatChipInputEvent) {
    const value = (event.value || '').trim();
    if (value) list.push(value);
    event.chipInput!.clear();
  }

  removeItem(list: string[], item: string) {
    const index = list.indexOf(item);
    if (index >= 0) list.splice(index, 1);
  }

  async save() {
    try {
      await this.api.fetch('/admin/ip_blacklist/settings', {
        method: 'POST',
        body: {
          enabled: this.enabled,
          blacklist: this.ipBlacklist,
          asnBlacklist: this.asnBlacklist,
          fingerprintBlacklist: this.fingerprintBlacklist,
          enableDailyLimit: this.enableDailyLimit,
          dailyRequestLimit: this.dailyRequestLimit
        }
      });
      this.snackbar.success('保存成功');
    } catch (error: any) {
      this.snackbar.error(error.message || '保存失败');
    }
  }
}

// frontend/src/views/admin/IpBlacklistSettings.vue
<script setup>
import { onMounted, ref } from 'vue';
import { useI18n } from 'vue-i18n'

import { useGlobalState } from '../../store'
import { api } from '../../api'

const { loading, showSnackbar } = useGlobalState()

const { t } = useI18n({
    messages: {
        en: {
            title: 'IP Blacklist Settings',
            manualInputPrompt: 'Type pattern and press Enter to add',
            save: 'Save',
            successTip: 'Save Success',
            enable_ip_blacklist: 'Enable IP Blacklist',
            enable_tip: 'Block IPs matching blacklist patterns from accessing rate-limited APIs',
            ip_blacklist: 'IP Blacklist Patterns',
            ip_blacklist_placeholder: 'Enter pattern (e.g., 192.168.1 or ^10\\.0\\.0\\.5$)',
            asn_blacklist: 'ASN Organization Blacklist',
            asn_blacklist_placeholder: 'Enter ASN organization (e.g., Google, Amazon)',
            fingerprint_blacklist: 'Browser Fingerprint Blacklist',
            fingerprint_blacklist_placeholder: 'Enter fingerprint ID (e.g., a1b2c3d4e5f6g7h8)',
            tip_ip: 'IP Blacklist: Supports text matching (e.g., "192.168.1") or regex (e.g., "^10\\.0\\.0\\.5$").',
            tip_asn: 'ASN Organization: Block by ISP/provider. Case-insensitive text matching or regex.',
            tip_fingerprint: 'Browser Fingerprint: Block by browser fingerprint. Supports exact matching or regex patterns.',
            tip_daily_limit: 'Daily Limit: Restrict the maximum number of requests per IP address per day (1-1000000).',
            tip_scope: 'Applies to: Create Address, Send Mail, External Send Mail API, User Registration, Verify Code',
            enable_daily_limit: 'Enable Daily Request Limit',
            enable_daily_limit_tip: 'Limit the number of API requests per IP address per day',
            daily_request_limit: 'Daily Request Limit',
            daily_request_limit_placeholder: 'Enter limit (e.g., 1000)',
        },
        zh: {
            title: 'IP 黑名单设置',
            manualInputPrompt: '输入匹配模式后按回车键添加',
            save: '保存',
            successTip: '保存成功',
            enable_ip_blacklist: '启用 IP 黑名单',
            enable_tip: '阻止匹配黑名单的 IP 访问限流 API',
            ip_blacklist: 'IP 黑名单匹配模式',
            ip_blacklist_placeholder: '输入匹配模式（例如：192.168.1 或 ^10\\.0\\.0\\.5$）',
            asn_blacklist: 'ASN 组织（运营商）黑名单',
            asn_blacklist_placeholder: '输入 ASN 组织名称（例如：Google, Amazon）',
            fingerprint_blacklist: '浏览器指纹黑名单',
            fingerprint_blacklist_placeholder: '输入指纹 ID（例如：a1b2c3d4e5f6g7h8）',
            tip_ip: 'IP 黑名单：支持文本匹配（如 "192.168.1"）或正则表达式（如 "^10\\.0\\.0\\.5$"）。',
            tip_asn: 'ASN 组织：根据运营商/ISP 拉黑。支持不区分大小写的文本匹配或正则表达式。',
            tip_fingerprint: '浏览器指纹：根据浏览器指纹拉黑。支持完全匹配或正则表达式。',
            tip_daily_limit: '每日限流：限制单个 IP 地址每天最多请求次数（1-1000000）。',
            tip_scope: '作用范围：创建邮箱地址、发送邮件、外部发送邮件 API、用户注册、验证码验证',
            enable_daily_limit: '启用每日请求限流',
            enable_daily_limit_tip: '限制每个 IP 地址每天的 API 请求次数',
            daily_request_limit: '每日请求次数上限',
            daily_request_limit_placeholder: '输入限制次数（例如：1000）',
        }
    }
});

const enabled = ref(false)
const ipBlacklist = ref([])
const asnBlacklist = ref([])
const fingerprintBlacklist = ref([])
const enableDailyLimit = ref(false)
const dailyRequestLimit = ref(1000)

const fetchData = async () => {
    try {
        loading.value = true
        const res = await api.fetch(`/admin/ip_blacklist/settings`)
        enabled.value = res.enabled || false
        ipBlacklist.value = res.blacklist || []
        asnBlacklist.value = res.asnBlacklist || []
        fingerprintBlacklist.value = res.fingerprintBlacklist || []
        enableDailyLimit.value = res.enableDailyLimit || false
        dailyRequestLimit.value = res.dailyRequestLimit || 1000
    } catch (error) {
        showSnackbar(error.message || "error", 'error')
    } finally {
        loading.value = false
    }
}

const save = async () => {
    try {
        loading.value = true
        await api.fetch(`/admin/ip_blacklist/settings`, {
            method: 'POST',
            body: JSON.stringify({
                enabled: enabled.value,
                blacklist: ipBlacklist.value || [],
                asnBlacklist: asnBlacklist.value || [],
                fingerprintBlacklist: fingerprintBlacklist.value || [],
                enableDailyLimit: enableDailyLimit.value,
                dailyRequestLimit: dailyRequestLimit.value
            })
        })
        showSnackbar(t('successTip'), 'success')
    } catch (error) {
        showSnackbar(error.message || "error", 'error')
    } finally {
        loading.value = false
    }
}

onMounted(async () => {
    await fetchData();
})
</script>

<template>
    <div class="center ma-4">
        <v-card :title="t('title')" variant="flat" max-width="600" width="100%">
            <template v-slot:append>
                <v-btn color="primary" :loading="loading" @click="save">{{ t('save') }}</v-btn>
            </template>
            <v-card-text>
                <v-alert type="info" variant="tonal" class="mb-4">
                    <div style="line-height: 1.8;">
                        <div><strong>{{ t("tip_scope") }}</strong></div>
                        <div>• {{ t("tip_ip") }}</div>
                        <div>• {{ t("tip_asn") }}</div>
                        <div>• {{ t("tip_fingerprint") }}</div>
                        <div>• {{ t("tip_daily_limit") }}</div>
                    </div>
                </v-alert>

                <div class="d-flex align-center mb-4">
                    <v-switch v-model="enabled" :label="t('enable_ip_blacklist')" hide-details color="primary"></v-switch>
                    <span class="text-caption text-grey ml-2">{{ t('enable_tip') }}</span>
                </div>

                <v-combobox v-model="ipBlacklist" :label="t('ip_blacklist')" :placeholder="t('ip_blacklist_placeholder')" multiple chips closable-chips variant="outlined" density="compact" :disabled="!enabled" class="mb-4"></v-combobox>

                <v-combobox v-model="asnBlacklist" :label="t('asn_blacklist')" :placeholder="t('asn_blacklist_placeholder')" multiple chips closable-chips variant="outlined" density="compact" :disabled="!enabled" class="mb-4"></v-combobox>

                <v-combobox v-model="fingerprintBlacklist" :label="t('fingerprint_blacklist')" :placeholder="t('fingerprint_blacklist_placeholder')" multiple chips closable-chips variant="outlined" density="compact" :disabled="!enabled" class="mb-4"></v-combobox>

                <v-divider class="mb-4"></v-divider>

                <div class="d-flex align-center mb-4">
                    <v-switch v-model="enableDailyLimit" :label="t('enable_daily_limit')" hide-details color="primary"></v-switch>
                    <span class="text-caption text-grey ml-2">{{ t('enable_daily_limit_tip') }}</span>
                </div>

                <v-text-field v-model.number="dailyRequestLimit" :label="t('daily_request_limit')" type="number" :min="1" :max="1000000" :placeholder="t('daily_request_limit_placeholder')" :disabled="!enableDailyLimit" variant="outlined" density="compact"></v-text-field>
            </v-card-text>
        </v-card>
    </div>
</template>

<style scoped>
.center {
    display: flex;
    text-align: left;
    place-items: center;
    justify-content: center;
}
</style>
