// frontend-angular/src/app/views/admin/mails-unknow/mails-unknow.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ApiService } from '../../../services/api.service';
import { MailboxComponent } from '../../../components/mailbox/mailbox.component';

@Component({
  selector: 'app-mails-unknow',
  standalone: true,
  imports: [CommonModule, MailboxComponent],
  template: `
    <div class="container">
      <app-mailbox
        [enableUserDeleteEmail]="true"
        [fetchMailData]="fetchMailData"
        [deleteMail]="deleteMail">
      </app-mailbox>
    </div>
  `,
  styles: [`
    .container { padding: 16px; }
  `]
})
export class MailsUnknowComponent {
  private api = inject(ApiService);

  fetchMailData = async (limit: number, offset: number) => {
    return await this.api.fetch<any>(`/admin/mails_unknow?limit=${limit}&offset=${offset}`);
  };

  deleteMail = async (mailId: number) => {
    await this.api.fetch(`/admin/mails/${mailId}`, { method: 'DELETE' });
  };
}

// frontend/src/views/admin/MailsUnknow.vue
<script setup>
import { api } from '../../api'
import MailBox from '../../components/MailBox.vue';

const fetchMailUnknowData = async (limit, offset) => {
    return await api.fetch(
        `/admin/mails_unknow`
        + `?limit=${limit}`
        + `&offset=${offset}`
    );
}

const deleteMail = async (curMailId) => {
    await api.fetch(`/admin/mails/${curMailId}`, { method: 'DELETE' });
};
</script>

<template>
    <div class="mt-3">
        <MailBox :enableUserDeleteEmail="true" :fetchMailData="fetchMailUnknowData" :deleteMail="deleteMail" />
    </div>
</template>
