// frontend-angular/src/app/views/admin/send-mail/send-mail.component.ts
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatInputModule } from '@angular/material/input';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatButtonToggleModule } from '@angular/material/button-toggle';
import { ApiService } from '../../../services/api.service';
import { SnackbarService } from '../../../services/snackbar.service';

@Component({
  selector: 'app-admin-send-mail',
  standalone: true,
  imports: [
    CommonModule, FormsModule, MatCardModule, MatButtonModule,
    MatInputModule, MatFormFieldModule, MatButtonToggleModule
  ],
  template: `
    <div class="container">
      <mat-card class="form-card">
        <mat-card-content>
          <div class="actions-row mb-3">
            <button mat-raised-button color="primary" (click)="send()">发送</button>
          </div>

          <div class="mb-3">
            <p class="label">你的名称和地址，名称不填写则使用邮箱地址</p>
            <div class="row">
              <mat-form-field appearance="outline" class="flex-grow">
                <mat-label>名称</mat-label>
                <input matInput [(ngModel)]="model.fromName">
              </mat-form-field>
              <mat-form-field appearance="outline" class="flex-grow">
                <mat-label>邮箱地址</mat-label>
                <input matInput [(ngModel)]="model.fromMail">
              </mat-form-field>
            </div>
          </div>

          <div class="mb-3">
            <p class="label">收件人名称和地址，名称不填写则使用邮箱地址</p>
            <div class="row">
              <mat-form-field appearance="outline" class="flex-grow">
                <mat-label>名称</mat-label>
                <input matInput [(ngModel)]="model.toName">
              </mat-form-field>
              <mat-form-field appearance="outline" class="flex-grow">
                <mat-label>邮箱地址</mat-label>
                <input matInput [(ngModel)]="model.toMail">
              </mat-form-field>
            </div>
          </div>

          <mat-form-field appearance="outline" class="full-width mb-3">
            <mat-label>主题</mat-label>
            <input matInput [(ngModel)]="model.subject">
          </mat-form-field>

          <div class="mb-3">
            <p class="label">选项</p>
            <mat-button-toggle-group [(ngModel)]="model.contentType">
              <mat-button-toggle value="text">文本</mat-button-toggle>
              <mat-button-toggle value="html">HTML</mat-button-toggle>
            </mat-button-toggle-group>
            @if (model.contentType !== 'text') {
              <button mat-button (click)="isPreview.set(!isPreview())">
                {{ isPreview() ? '编辑' : '预览' }}
              </button>
            }
          </div>

          <div class="mb-3">
            <p class="label">内容</p>
            @if (isPreview()) {
              <div class="preview-box" [innerHTML]="model.content"></div>
            } @else {
              <mat-form-field appearance="outline" class="full-width">
                <textarea matInput [(ngModel)]="model.content" rows="10"></textarea>
              </mat-form-field>
            }
          </div>
        </mat-card-content>
      </mat-card>
    </div>
  `,
  styles: [`
    .container { display: flex; justify-content: center; padding: 20px; }
    .form-card { max-width: 800px; width: 100%; }
    .full-width { width: 100%; }
    .mb-3 { margin-bottom: 12px; }
    .row { display: flex; gap: 8px; }
    .flex-grow { flex: 1; }
    .label { font-size: 14px; color: #666; margin-bottom: 8px; }
    .actions-row { display: flex; justify-content: flex-end; }
    .preview-box { border: 1px solid #ccc; padding: 16px; border-radius: 4px; min-height: 200px; background: #fafafa; }
  `]
})
export class AdminSendMailComponent {
  private api = inject(ApiService);
  private snackbar = inject(SnackbarService);

  isPreview = signal(false);
  model = {
    fromName: '',
    fromMail: '',
    toName: '',
    toMail: '',
    subject: '',
    contentType: 'text',
    content: ''
  };

  async send() {
    try {
      await this.api.fetch('/admin/send_mail', {
        method: 'POST',
        body: {
          from_name: this.model.fromName,
          from_mail: this.model.fromMail,
          to_name: this.model.toName,
          to_mail: this.model.toMail,
          subject: this.model.subject,
          is_html: this.model.contentType !== 'text',
          content: this.model.content
        }
      });
      this.model = { fromName: '', fromMail: '', toName: '', toMail: '', subject: '', contentType: 'text', content: '' };
      this.snackbar.success('请查看您的发件箱, 如果失败, 请检查稍后重试。');
    } catch (error: any) {
      this.snackbar.error(error.message || '发送失败');
    }
  }
}

// frontend/src/views/admin/SendMail.vue
<script setup>
import '@wangeditor/editor/dist/css/style.css'
import { Editor, Toolbar } from '@wangeditor/editor-for-vue'
import { useI18n } from 'vue-i18n'
import { onBeforeUnmount, ref, shallowRef } from 'vue'
import { useSessionStorage } from '@vueuse/core'
import { api } from '../../api'
import { useGlobalState } from '../../store'

const { showSnackbar } = useGlobalState()
const isPreview = ref(false)
const editorRef = shallowRef()

const sendMailModel = useSessionStorage('sendMailByAdminModel', {
    fromName: "",
    fromMail: "",
    toName: "",
    toMail: "",
    subject: "",
    contentType: 'text',
    content: "",
});

const { t } = useI18n({
    locale: 'zh',
    messages: {
        en: {
            successSend: 'Please check your sendbox. If failed, please try again later.',
            fromName: 'Your Name and Address, leave Name blank to use email address',
            toName: 'Recipient Name and Address, leave Name blank to use email address',
            subject: 'Subject',
            options: 'Options',
            edit: 'Edit',
            preview: 'Preview',
            content: 'Content',
            send: 'Send',
            text: 'Text',
            html: 'HTML',
            'rich text': 'Rich Text',
            tooLarge: 'Too large file, please upload file less than 1MB.',
        },
        zh: {
            successSend: '请查看您的发件箱, 如果失败, 请检查稍后重试。',
            fromName: '你的名称和地址，名称不填写则使用邮箱地址',
            toName: '收件人名称和地址，名称不填写则使用邮箱地址',
            subject: '主题',
            options: '选项',
            edit: '编辑',
            preview: '预览',
            content: '内容',
            send: '发送',
            text: '文本',
            html: 'HTML',
            'rich text': '富文本',
            tooLarge: '文件过大, 请上传小于1MB的文件。',
        }
    }
});

const contentTypes = [
    { title: t('text'), value: 'text' },
    { title: t('html'), value: 'html' },
    { title: t('rich text'), value: 'rich' },
]

const send = async () => {
    try {
        await api.fetch(`/admin/send_mail`, {
            method: 'POST',
            body: JSON.stringify({
                from_name: sendMailModel.value.fromName,
                from_mail: sendMailModel.value.fromMail,
                to_name: sendMailModel.value.toName,
                to_mail: sendMailModel.value.toMail,
                subject: sendMailModel.value.subject,
                is_html: sendMailModel.value.contentType != 'text',
                content: sendMailModel.value.content,
            })
        })
        sendMailModel.value = {
            fromName: "",
            fromMail: "",
            toName: "",
            toMail: "",
            subject: "",
            contentType: 'text',
            content: "",
        }
    } catch (error) {
        showSnackbar(error.message || "error", 'error')
    } finally {
        showSnackbar(t("successSend"), 'success')
    }
}

const toolbarConfig = {
    excludeKeys: ["uploadVideo"]
}

const editorConfig = {
    MENU_CONF: {
        'uploadImage': {
            async customUpload() {
                showSnackbar(t('tooLarge'), 'error')
            },
            maxFileSize: 1 * 1024 * 1024,
            base64LimitSize: 1 * 1024 * 1024,
        }
    }
}

onBeforeUnmount(() => {
    const editor = editorRef.value
    if (editor == null) return
    editor.destroy()
})

const handleCreated = (editor) => {
    editorRef.value = editor;
}
</script>

<template>
    <div class="center">
        <v-card variant="flat" max-width="800" width="100%">
            <div class="d-flex justify-end mb-4">
                <v-btn color="primary" @click="send">{{ t('send') }}</v-btn>
            </div>
            <v-form class="text-left">
                <div class="mb-4">
                    <div class="text-subtitle-2 mb-2">{{ t('fromName') }}</div>
                    <div class="d-flex ga-2">
                        <v-text-field v-model="sendMailModel.fromName" variant="outlined" density="compact" hide-details class="flex-grow-1"></v-text-field>
                        <v-text-field v-model="sendMailModel.fromMail" variant="outlined" density="compact" hide-details class="flex-grow-1"></v-text-field>
                    </div>
                </div>
                <div class="mb-4">
                    <div class="text-subtitle-2 mb-2">{{ t('toName') }}</div>
                    <div class="d-flex ga-2">
                        <v-text-field v-model="sendMailModel.toName" variant="outlined" density="compact" hide-details class="flex-grow-1"></v-text-field>
                        <v-text-field v-model="sendMailModel.toMail" variant="outlined" density="compact" hide-details class="flex-grow-1"></v-text-field>
                    </div>
                </div>
                <div class="mb-4">
                    <div class="text-subtitle-2 mb-2">{{ t('subject') }}</div>
                    <v-text-field v-model="sendMailModel.subject" variant="outlined" density="compact" hide-details></v-text-field>
                </div>
                <div class="mb-4">
                    <div class="text-subtitle-2 mb-2">{{ t('options') }}</div>
                    <div class="d-flex align-center ga-2">
                        <v-btn-toggle v-model="sendMailModel.contentType" mandatory>
                            <v-btn v-for="option in contentTypes" :key="option.value" :value="option.value">{{ option.title }}</v-btn>
                        </v-btn-toggle>
                        <v-btn v-if="sendMailModel.contentType != 'text'" variant="tonal" @click="isPreview = !isPreview">
                            {{ isPreview ? t('edit') : t('preview') }}
                        </v-btn>
                    </div>
                </div>
                <div class="mb-4">
                    <div class="text-subtitle-2 mb-2">{{ t('content') }}</div>
                    <v-card v-if="isPreview" variant="tonal" class="pa-4">
                        <div v-html="sendMailModel.content"></div>
                    </v-card>
                    <div v-else-if="sendMailModel.contentType == 'rich'" style="border: 1px solid #ccc">
                        <Toolbar style="border-bottom: 1px solid #ccc" :defaultConfig="toolbarConfig" :editor="editorRef" mode="default" />
                        <Editor style="height: 500px; overflow-y: hidden;" v-model="sendMailModel.content" :defaultConfig="editorConfig" mode="default" @onCreated="handleCreated" />
                    </div>
                    <v-textarea v-else v-model="sendMailModel.content" variant="outlined" density="compact" rows="3" auto-grow></v-textarea>
                </div>
            </v-form>
        </v-card>
    </div>
</template>

<style scoped>
.center {
    display: flex;
    text-align: center;
    place-items: center;
    justify-content: center;
}
</style>
