// frontend-angular/src/app/views/admin/sendbox/sendbox.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { GlobalStateService } from '../../../services/global-state.service';
import { ApiService } from '../../../services/api.service';
import { SendboxComponent as SendboxListComponent } from '../../../components/sendbox/sendbox.component';

@Component({
  selector: 'app-admin-sendbox',
  standalone: true,
  imports: [CommonModule, FormsModule, MatFormFieldModule, MatInputModule, MatButtonModule, SendboxListComponent],
  template: `
    <div class="container">
      <div class="search-row mb-3">
        <mat-form-field appearance="outline" class="search-field">
          <mat-label>请输入地址查询, 留空则查询所有</mat-label>
          <input matInput [(ngModel)]="addressQuery" (keydown.enter)="refresh()">
        </mat-form-field>
        <button mat-stroked-button color="primary" (click)="refresh()">查询</button>
      </div>
      
      <app-sendbox
        [enableUserDeleteEmail]="true"
        [deleteMailFn]="deleteMail"
        [fetchMailData]="fetchData"
        [showEMailFrom]="true">
      </app-sendbox>
    </div>
  `,
  styles: [`
    .container { padding: 16px; }
    .search-row { display: flex; gap: 8px; align-items: center; }
    .search-field { max-width: 400px; flex: 1; }
    .mb-3 { margin-bottom: 12px; }
  `]
})
export class AdminSendboxComponent {
  state = inject(GlobalStateService);
  private api = inject(ApiService);

  addressQuery = '';

  fetchData = async (limit: number, offset: number) => {
    const query = this.addressQuery.trim();
    let url = `/admin/sendbox?limit=${limit}&offset=${offset}`;
    if (query) url += `&address=${encodeURIComponent(query)}`;
    return await this.api.fetch<any>(url);
  };

  deleteMail = async (mailId: number) => {
    await this.api.fetch(`/admin/sendbox/${mailId}`, { method: 'DELETE' });
  };

  refresh() {
    // Trigger re-fetch by updating the component
    this.state.adminSendBoxTabAddress.set(this.addressQuery);
  }
}

// frontend/src/views/admin/SendBox.vue
<script setup>
import { useI18n } from 'vue-i18n'

import { useGlobalState } from '../../store'
import { api } from '../../api'
import SendBox from '../../components/SendBox.vue';

const { adminSendBoxTabAddress } = useGlobalState()

const { t } = useI18n({
    messages: {
        en: {
            query: 'Query',
            queryTip: 'Please input address to query, leave blank to query all',
        },
        zh: {
            query: '查询',
            queryTip: '请输入地址查询, 留空则查询所有',
        }
    }
});

const fetchData = async (limit, offset) => {
    adminSendBoxTabAddress.value = adminSendBoxTabAddress.value.trim();
    return await api.fetch(
        `/admin/sendbox?limit=${limit}&offset=${offset}`
        + (adminSendBoxTabAddress.value ? `&address=${adminSendBoxTabAddress.value}` : '')
    );
}

const deleteSenboxMail = async (curMailId) => {
    await api.fetch(`/admin/sendbox/${curMailId}`, { method: 'DELETE' });
};
</script>

<template>
    <div>
        <div class="d-flex ga-2 mb-3">
            <v-text-field v-model="adminSendBoxTabAddress" :placeholder="t('queryTip')" variant="outlined"
                density="compact" hide-details @keydown.enter="fetchData" style="max-width: 400px;" />
            <v-btn @click="fetchData" color="primary" variant="outlined">
                {{ t('query') }}
            </v-btn>
        </div>
        <SendBox :enableUserDeleteEmail="true" :deleteMail="deleteSenboxMail" :fetchMailData="fetchData"
            :showEMailFrom="true" />
    </div>
</template>
