// frontend-angular/src/app/views/admin/user-settings/user-settings.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatInputModule } from '@angular/material/input';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatChipsModule } from '@angular/material/chips';
import { MatIconModule } from '@angular/material/icon';
import { COMMA, ENTER } from '@angular/cdk/keycodes';
import { MatChipInputEvent } from '@angular/material/chips';
import { GlobalStateService } from '../../../services/global-state.service';
import { ApiService } from '../../../services/api.service';
import { SnackbarService } from '../../../services/snackbar.service';

@Component({
  selector: 'app-admin-user-settings',
  standalone: true,
  imports: [
    CommonModule, FormsModule, MatCardModule, MatButtonModule,
    MatInputModule, MatFormFieldModule, MatSlideToggleModule,
    MatCheckboxModule, MatChipsModule, MatIconModule
  ],
  template: `
    <div class="container">
      <mat-card class="form-card">
        <mat-card-actions align="end">
          <button mat-raised-button color="primary" (click)="save()" [disabled]="state.loading()">
            保存
          </button>
        </mat-card-actions>
        <mat-card-content>
          <mat-slide-toggle [(ngModel)]="userSettings.enable" class="mb-3">
            允许用户注册
          </mat-slide-toggle>

          <div class="setting-row mb-3">
            <mat-checkbox [(ngModel)]="userSettings.enableMailVerify">启用</mat-checkbox>
            @if (userSettings.enableMailVerify) {
              <mat-form-field appearance="outline" class="flex-grow">
                <mat-label>验证邮件发送地址</mat-label>
                <input matInput [(ngModel)]="userSettings.verifyMailSender">
              </mat-form-field>
            }
          </div>
          <p class="hint-text mb-3">启用邮件验证(发送地址必须是系统中能有余额且能正常发送邮件的地址)</p>

          <div class="setting-row mb-3">
            <mat-checkbox [(ngModel)]="userSettings.enableMailAllowList">启用</mat-checkbox>
            @if (userSettings.enableMailAllowList) {
              <mat-form-field appearance="outline" class="flex-grow">
                <mat-label>邮件地址白名单</mat-label>
                <mat-chip-grid #chipGrid>
                  @for (item of userSettings.mailAllowList; track item) {
                    <mat-chip-row (removed)="removeAllowItem(item)">
                      {{item}}
                      <button matChipRemove><mat-icon>cancel</mat-icon></button>
                    </mat-chip-row>
                  }
                </mat-chip-grid>
                <input matInput [matChipInputFor]="chipGrid" [matChipInputSeparatorKeyCodes]="separatorKeyCodes"
                       (matChipInputTokenEnd)="addAllowItem($event)">
              </mat-form-field>
            }
          </div>
          <p class="hint-text mb-3">启用邮件地址白名单(可手动输入, 回车增加)</p>

          <mat-form-field appearance="outline" class="full-width">
            <mat-label>可绑定最大邮箱地址数量</mat-label>
            <input matInput type="number" [(ngModel)]="userSettings.maxAddressCount">
          </mat-form-field>
        </mat-card-content>
      </mat-card>
    </div>
  `,
  styles: [`
    .container { display: flex; justify-content: center; padding: 20px; }
    .form-card { max-width: 600px; width: 100%; }
    .full-width { width: 100%; }
    .mb-3 { margin-bottom: 12px; }
    .setting-row { display: flex; align-items: center; gap: 8px; }
    .flex-grow { flex: 1; }
    .hint-text { color: #666; font-size: 12px; margin-top: -8px; }
  `]
})
export class AdminUserSettingsComponent implements OnInit {
  state = inject(GlobalStateService);
  private api = inject(ApiService);
  private snackbar = inject(SnackbarService);

  separatorKeyCodes = [ENTER, COMMA];
  userSettings = {
    enable: false,
    enableMailVerify: false,
    verifyMailSender: '',
    enableMailAllowList: false,
    mailAllowList: ['gmail.com', '163.com', '126.com', 'qq.com', 'outlook.com', 'hotmail.com', 'icloud.com', 'yahoo.com', 'foxmail.com'],
    maxAddressCount: 5
  };

  async ngOnInit() {
    await this.fetchData();
  }

  async fetchData() {
    try {
      const res = await this.api.fetch<any>('/admin/user_settings');
      Object.assign(this.userSettings, res);
    } catch (error: any) {
      this.snackbar.error(error.message || '获取设置失败');
    }
  }

  addAllowItem(event: MatChipInputEvent) {
    const value = (event.value || '').trim();
    if (value) this.userSettings.mailAllowList.push(value);
    event.chipInput!.clear();
  }

  removeAllowItem(item: string) {
    const index = this.userSettings.mailAllowList.indexOf(item);
    if (index >= 0) this.userSettings.mailAllowList.splice(index, 1);
  }

  async save() {
    try {
      await this.api.fetch('/admin/user_settings', {
        method: 'POST',
        body: this.userSettings
      });
      this.snackbar.success('保存成功');
    } catch (error: any) {
      this.snackbar.error(error.message || '保存失败');
    }
  }
}

// frontend/src/views/admin/UserSettings.vue
<script setup>
import { onMounted, ref } from 'vue';
import { useI18n } from 'vue-i18n'

import { useGlobalState } from '../../store'
import { api } from '../../api'

const { loading } = useGlobalState()

const snackbar = ref({ show: false, text: '', color: 'success' })
const showMessage = (text, color = 'success') => {
    snackbar.value = { show: true, text, color }
}

const { t } = useI18n({
    messages: {
        en: {
            save: 'Save',
            successTip: 'Save Success',
            enable: 'Enable',
            enableUserRegister: 'Allow User Register',
            enableMailVerify: 'Enable Mail Verify (Send address must be an address in the system with a balance and can send mail normally)',
            verifyMailSender: 'Verify Mail Sender',
            enableMailAllowList: 'Enable Mail Address Allow List(Manually enterable)',
            manualInputPrompt: 'Type and press Enter to add',
            mailAllowList: 'Mail Address Allow List',
            maxAddressCount: 'Maximum number of email addresses that can be binded',
        },
        zh: {
            save: '保存',
            successTip: '保存成功',
            enable: '启用',
            enableUserRegister: "允许用户注册",
            enableMailVerify: '启用邮件验证(发送地址必须是系统中能有余额且能正常发送邮件的地址)',
            verifyMailSender: '验证邮件发送地址',
            enableMailAllowList: '启用邮件地址白名单(可手动输入, 回车增加)',
            manualInputPrompt: '输入后按回车键添加',
            mailAllowList: '邮件地址白名单',
            maxAddressCount: '可绑定最大邮箱地址数量',
        }
    }
});

const commonMail = [
    "gmail.com", "163.com", "126.com", "qq.com", "outlook.com", "hotmail.com",
    "icloud.com", "yahoo.com", "foxmail.com"
]

const userSettings = ref({
    enable: false,
    enableMailVerify: false,
    verifyMailSender: "",
    enableMailAllowList: false,
    mailAllowList: commonMail,
    maxAddressCount: 5,
});

const fetchData = async () => {
    try {
        const res = await api.fetch(`/admin/user_settings`)
        Object.assign(userSettings.value, res)
    } catch (error) {
        showMessage(error.message || "error", 'error');
    }
}

const save = async () => {
    try {
        await api.fetch(`/admin/user_settings`, {
            method: 'POST',
            body: JSON.stringify(userSettings.value)
        })
        showMessage(t('successTip'))
    } catch (error) {
        showMessage(error.message || "error", 'error');
    }
}

onMounted(async () => {
    await fetchData();
})
</script>

<template>
    <div class="d-flex justify-center">
        <v-card variant="flat" max-width="600" width="100%">
            <v-card-actions class="justify-end">
                <v-btn @click="save" color="primary" :loading="loading">{{ t('save') }}</v-btn>
            </v-card-actions>
            <v-card-text>
                <v-switch v-model="userSettings.enable" :label="t('enableUserRegister')" color="primary" hide-details
                    class="mb-4" />
                <div class="mb-4">
                    <div class="d-flex align-center ga-2">
                        <v-checkbox v-model="userSettings.enableMailVerify" :label="t('enable')" hide-details
                            style="flex: 0 0 auto;" />
                        <v-text-field v-if="userSettings.enableMailVerify" v-model="userSettings.verifyMailSender"
                            :placeholder="t('verifyMailSender')" variant="outlined" density="compact" hide-details />
                    </div>
                    <div class="text-caption text-medium-emphasis mt-1">{{ t('enableMailVerify') }}</div>
                </div>
                <div class="mb-4">
                    <div class="d-flex align-center ga-2">
                        <v-checkbox v-model="userSettings.enableMailAllowList" :label="t('enable')" hide-details
                            style="flex: 0 0 auto;" />
                        <v-combobox v-if="userSettings.enableMailAllowList" v-model="userSettings.mailAllowList"
                            :placeholder="t('mailAllowList')" multiple chips closable-chips variant="outlined"
                            density="compact" hide-details />
                    </div>
                    <div class="text-caption text-medium-emphasis mt-1">{{ t('enableMailAllowList') }}</div>
                </div>
                <v-text-field v-model.number="userSettings.maxAddressCount" :label="t('maxAddressCount')" type="number"
                    variant="outlined" density="compact" />
            </v-card-text>
        </v-card>

        <v-snackbar v-model="snackbar.show" :color="snackbar.color" :timeout="2000">
            {{ snackbar.text }}
        </v-snackbar>
    </div>
</template>
