// frontend-angular/src/app/views/admin/worker-config/worker-config.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { ApiService } from '../../../services/api.service';
import { SnackbarService } from '../../../services/snackbar.service';

@Component({
  selector: 'app-worker-config',
  standalone: true,
  imports: [CommonModule, MatCardModule],
  template: `
    <div class="container">
      <mat-card class="form-card">
        <mat-card-content>
          <pre class="config-box">{{ settings() | json }}</pre>
        </mat-card-content>
      </mat-card>
    </div>
  `,
  styles: [`
    .container { display: flex; justify-content: center; padding: 20px; }
    .form-card { max-width: 800px; width: 100%; overflow: auto; }
    .config-box { background: #f5f5f5; padding: 16px; border-radius: 4px; overflow: auto; text-align: left; }
  `]
})
export class WorkerConfigComponent implements OnInit {
  private api = inject(ApiService);
  private snackbar = inject(SnackbarService);

  settings = signal<any>({});

  async ngOnInit() {
    await this.fetchData();
  }

  async fetchData() {
    try {
      const res = await this.api.fetch<any>('/admin/worker/configs');
      this.settings.set(res);
    } catch (error: any) {
      this.snackbar.error(error.message || '获取配置失败');
    }
  }
}

// frontend/src/views/admin/WorkerConfig.vue
<script setup>
import { onMounted, ref } from 'vue';
import { useI18n } from 'vue-i18n'

import { useGlobalState } from '../../store'
import { api } from '../../api'

const { loading, showSnackbar } = useGlobalState()

const settings = ref({})

const fetchData = async () => {
    try {
        const res = await api.fetch(`/admin/worker/configs`)
        Object.assign(settings.value, res)
    } catch (error) {
        showSnackbar(error.message || "error", 'error')
    }
}

onMounted(async () => {
    await fetchData();
})
</script>

<template>
    <div class="center">
        <v-card variant="flat" max-width="800" width="100%" style="overflow: auto;">
            <pre class="text-left pa-4">{{ JSON.stringify(settings, null, 2) }}</pre>
        </v-card>
    </div>
</template>

<style scoped>
.center {
    display: flex;
    text-align: left;
    place-items: center;
    justify-content: center;
}
</style>
