// frontend/src/views/index/Attachment.vue
<script setup>
import { ref, onMounted } from 'vue';
import { useI18n } from 'vue-i18n'

import { api } from '../../api'

const snackbar = ref({ show: false, text: '', color: 'success' })
const showMessage = (text, color = 'success') => {
    snackbar.value = { show: true, text, color }
}

const { t } = useI18n({
    messages: {
        en: {
            download: 'Download',
            action: 'Action',
            delete: 'Delete',
            deleteConfirm: 'Are you sure to delete this attachment?',
            deleteSuccess: 'Deleted successfully',
            cancel: 'Cancel',
            key: 'Key',
        },
        zh: {
            download: '下载',
            action: '操作',
            delete: '删除',
            deleteConfirm: '确定要删除此附件吗？',
            deleteSuccess: '删除成功',
            cancel: '取消',
            key: '键',
        }
    }
});

const data = ref([])
const showDownload = ref(false)
const showDeleteConfirm = ref(false)
const curRow = ref({})
const curDownloadUrl = ref('')

const fetchData = async () => {
    try {
        const { results } = await api.fetch(`/api/attachment/list`);
        data.value = results;
    } catch (error) {
        console.log(error)
        showMessage(error.message || "error", 'error');
    }
}

const downloadAttachment = async (row) => {
    try {
        const { url } = await api.fetch(`/api/attachment/get_url`, {
            method: 'POST',
            body: JSON.stringify({ key: row.key })
        });
        curDownloadUrl.value = url;
        curRow.value = row;
        showDownload.value = true;
    } catch (error) {
        console.error(error);
        showMessage(error.message || "error", 'error');
    }
}

const confirmDelete = (row) => {
    curRow.value = row;
    showDeleteConfirm.value = true;
}

const deleteAttachment = async () => {
    try {
        await api.fetch(`/api/attachment/delete`, {
            method: 'POST',
            body: JSON.stringify({ key: curRow.value.key })
        });
        showMessage(t('deleteSuccess'));
        showDeleteConfirm.value = false;
        await fetchData();
    } catch (error) {
        console.error(error);
        showMessage(error.message || "error", 'error');
    }
}

onMounted(async () => {
    await fetchData()
})
</script>

<template>
    <div>
        <v-table>
            <thead>
                <tr>
                    <th>{{ t('key') }}</th>
                    <th>{{ t('action') }}</th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="row in data" :key="row.key">
                    <td>{{ row.key }}</td>
                    <td>
                        <v-btn size="small" color="success" variant="text" @click="downloadAttachment(row)">
                            {{ t('download') }}
                        </v-btn>
                        <v-btn size="small" color="error" variant="text" @click="confirmDelete(row)">
                            {{ t('delete') }}
                        </v-btn>
                    </td>
                </tr>
            </tbody>
        </v-table>

        <v-dialog v-model="showDownload" max-width="500">
            <v-card>
                <v-card-title>{{ t('download') }}</v-card-title>
                <v-card-text>
                    <v-chip color="info" class="mb-3">{{ curRow.key }}</v-chip>
                    <br />
                    <v-btn :href="curDownloadUrl" target="_blank" :download="curRow.key?.replace('/', '_')"
                        color="info" variant="tonal">
                        {{ t('download') }}
                    </v-btn>
                </v-card-text>
            </v-card>
        </v-dialog>

        <v-dialog v-model="showDeleteConfirm" max-width="400">
            <v-card>
                <v-card-text>{{ t('deleteConfirm') }}</v-card-text>
                <v-card-actions>
                    <v-spacer />
                    <v-btn @click="showDeleteConfirm = false">{{ t('cancel') }}</v-btn>
                    <v-btn color="error" @click="deleteAttachment">{{ t('delete') }}</v-btn>
                </v-card-actions>
            </v-card>
        </v-dialog>

        <v-snackbar v-model="snackbar.show" :color="snackbar.color" :timeout="2000">
            {{ snackbar.text }}
        </v-snackbar>
    </div>
</template>

// frontend-angular/src/app/views/index/attachment/attachment.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatTableModule } from '@angular/material/table';
import { MatButtonModule } from '@angular/material/button';
import { MatDialogModule, MatDialog, MAT_DIALOG_DATA, MatDialogRef } from '@angular/material/dialog';
import { MatChipsModule } from '@angular/material/chips';
import { MatIconModule } from '@angular/material/icon';
import { ApiService } from '../../../services/api.service';
import { SnackbarService } from '../../../services/snackbar.service';

interface AttachmentRow {
  key: string;
}

@Component({
  selector: 'app-attachment',
  standalone: true,
  imports: [CommonModule, MatTableModule, MatButtonModule, MatDialogModule, MatChipsModule, MatIconModule],
  template: `
    <div class="attachment-container">
      <table mat-table [dataSource]="data()" class="full-width">
        <ng-container matColumnDef="key">
          <th mat-header-cell *matHeaderCellDef>键</th>
          <td mat-cell *matCellDef="let row">{{ row.key }}</td>
        </ng-container>
        <ng-container matColumnDef="action">
          <th mat-header-cell *matHeaderCellDef>操作</th>
          <td mat-cell *matCellDef="let row">
            <button mat-button color="primary" (click)="downloadAttachment(row)">下载</button>
            <button mat-button color="warn" (click)="confirmDelete(row)">删除</button>
          </td>
        </ng-container>
        <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
        <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
      </table>
    </div>
  `,
  styles: [`
    .attachment-container { padding: 16px; }
    .full-width { width: 100%; }
  `]
})
export class AttachmentComponent implements OnInit {
  private api = inject(ApiService);
  private snackbar = inject(SnackbarService);
  private dialog = inject(MatDialog);

  displayedColumns = ['key', 'action'];
  data = signal<AttachmentRow[]>([]);
  curRow = signal<AttachmentRow | null>(null);

  async ngOnInit() {
    await this.fetchData();
  }

  async fetchData() {
    try {
      const { results } = await this.api.fetch<{ results: AttachmentRow[] }>('/api/attachment/list');
      this.data.set(results || []);
    } catch (error: any) {
      this.snackbar.error(error.message || 'error');
    }
  }

  async downloadAttachment(row: AttachmentRow) {
    try {
      const { url } = await this.api.fetch<{ url: string }>('/api/attachment/get_url', {
        method: 'POST',
        body: { key: row.key },
      });
      this.dialog.open(AttachmentDownloadDialogComponent, {
        width: '400px',
        data: { key: row.key, url }
      });
    } catch (error: any) {
      this.snackbar.error(error.message || 'error');
    }
  }

  confirmDelete(row: AttachmentRow) {
    this.curRow.set(row);
    const dialogRef = this.dialog.open(AttachmentDeleteDialogComponent, { width: '320px' });
    dialogRef.afterClosed().subscribe(result => {
      if (result) this.deleteAttachment();
    });
  }

  async deleteAttachment() {
    try {
      await this.api.fetch('/api/attachment/delete', {
        method: 'POST',
        body: { key: this.curRow()?.key },
      });
      this.snackbar.success('删除成功');
      await this.fetchData();
    } catch (error: any) {
      this.snackbar.error(error.message || 'error');
    }
  }
}

// Download Dialog
@Component({
  selector: 'app-attachment-download-dialog',
  standalone: true,
  imports: [CommonModule, MatDialogModule, MatButtonModule, MatChipsModule],
  template: `
    <h2 mat-dialog-title>下载</h2>
    <mat-dialog-content>
      <mat-chip color="primary" highlighted class="mb-3">{{ data.key }}</mat-chip>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button mat-dialog-close>关闭</button>
      <a mat-raised-button color="primary" [href]="data.url" target="_blank" [download]="data.key?.replace('/', '_')">下载</a>
    </mat-dialog-actions>
  `,
  styles: [`.mb-3 { margin-bottom: 12px; }`]
})
export class AttachmentDownloadDialogComponent {
  data = inject(MAT_DIALOG_DATA);
}

// Delete Confirm Dialog
@Component({
  selector: 'app-attachment-delete-dialog',
  standalone: true,
  imports: [CommonModule, MatDialogModule, MatButtonModule],
  template: `
    <h2 mat-dialog-title>删除</h2>
    <mat-dialog-content>确定要删除此附件吗？</mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button mat-dialog-close>取消</button>
      <button mat-raised-button color="warn" [mat-dialog-close]="true">删除</button>
    </mat-dialog-actions>
  `
})
export class AttachmentDeleteDialogComponent {}
