// frontend/src/components/ShadowHtmlComponent.vue
<template>
    <div v-if="useFallback" v-html="htmlContent"></div>
    <div v-else ref="shadowHost"></div>
</template>

<script setup>
import { ref, watch, onMounted, onBeforeUnmount } from 'vue';

const props = defineProps({
    htmlContent: {
        type: String,
        required: true,
    },
});

const shadowHost = ref(null);
let shadowRoot = null;
const useFallback = ref(false);

const renderShadowDom = () => {
    if (!shadowHost.value && !useFallback.value) return;

    try {
        if (useFallback.value) return;

        if (!shadowRoot && shadowHost.value) {
            try {
                shadowRoot = shadowHost.value.attachShadow({ mode: 'open' });
            } catch (error) {
                console.warn('Shadow DOM not supported, falling back to v-html:', error);
                useFallback.value = true;
                return;
            }
        }

        if (shadowRoot) {
            shadowRoot.innerHTML = props.htmlContent;
        }
    } catch (error) {
        console.error('Failed to render Shadow DOM, falling back to v-html:', error);
        useFallback.value = true;
    }
};

onMounted(() => {
    if (typeof Element.prototype.attachShadow !== 'function') {
        console.warn('Shadow DOM is not supported in this browser, using v-html fallback');
        useFallback.value = true;
        return;
    }
    renderShadowDom();
});

onBeforeUnmount(() => {
    if (shadowRoot) {
        shadowRoot.innerHTML = '';
    }
    shadowRoot = null;
});

watch(() => props.htmlContent, () => {
    renderShadowDom();
}, { flush: 'post' });
</script>

// frontend-angular/src/app/components/shadow-html/shadow-html.component.ts
import { Component, Input, ElementRef, OnChanges, OnDestroy, SimpleChanges, ViewChild, AfterViewInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-shadow-html',
  standalone: true,
  imports: [CommonModule],
  template: `
    @if (useFallback()) {
      <div [innerHTML]="htmlContent"></div>
    } @else {
      <div #shadowHost></div>
    }
  `,
  styles: [`
    :host {
      display: block;
    }
  `]
})
export class ShadowHtmlComponent implements AfterViewInit, OnChanges, OnDestroy {
  @Input() htmlContent: string = '';
  @ViewChild('shadowHost') shadowHostRef!: ElementRef<HTMLDivElement>;

  useFallback = signal(false);
  private shadowRoot: ShadowRoot | null = null;

  ngAfterViewInit() {
    if (typeof Element.prototype.attachShadow !== 'function') {
      console.warn('Shadow DOM is not supported in this browser, using innerHTML fallback');
      this.useFallback.set(true);
      return;
    }
    this.renderShadowDom();
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['htmlContent'] && !changes['htmlContent'].firstChange) {
      this.renderShadowDom();
    }
  }

  ngOnDestroy() {
    if (this.shadowRoot) {
      this.shadowRoot.innerHTML = '';
    }
    this.shadowRoot = null;
  }

  private renderShadowDom() {
    if (this.useFallback()) return;
    if (!this.shadowHostRef?.nativeElement) return;

    try {
      if (!this.shadowRoot) {
        try {
          this.shadowRoot = this.shadowHostRef.nativeElement.attachShadow({ mode: 'open' });
        } catch (error) {
          console.warn('Shadow DOM not supported, falling back to innerHTML:', error);
          this.useFallback.set(true);
          return;
        }
      }

      if (this.shadowRoot) {
        this.shadowRoot.innerHTML = this.htmlContent;
      }
    } catch (error) {
      console.error('Failed to render Shadow DOM, falling back to innerHTML:', error);
      this.useFallback.set(true);
    }
  }
}
