// frontend/src/views/index/LocalAddress.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { useLocalStorage } from '@vueuse/core';
import { useI18n } from 'vue-i18n'

// @ts-ignore
import { useGlobalState } from '../../store'
// @ts-ignore
import Login from '../common/Login.vue';

const { jwt } = useGlobalState()

const snackbar = ref({ show: false, text: '', color: 'success' })
const showMessage = (text: string, color: string = 'success') => {
    snackbar.value = { show: true, text, color }
}

const showChangeConfirm = ref(false)
const showUnbindConfirm = ref(false)
const selectedRow = ref<any>(null)

const { t } = useI18n({
    messages: {
        en: {
            tip: 'These addresses are stored in your browser, maybe loss if you clear the browser cache.',
            success: 'success',
            address: 'Address',
            actions: 'Actions',
            changeMailAddress: 'Change Mail Address',
            unbindMailAddress: 'Unbind Mail Address credential',
            create_or_bind: 'Create or Bind',
            bindAddressSuccess: 'Bind Address Success',
            cancel: 'Cancel',
        },
        zh: {
            tip: '这些地址存储在您的浏览器中，如果您清除浏览器缓存，可能会丢失。',
            success: '成功',
            address: '地址',
            actions: '操作',
            changeMailAddress: '切换邮箱地址',
            unbindMailAddress: '解绑邮箱地址',
            create_or_bind: '创建或绑定',
            bindAddressSuccess: '绑定地址成功',
            cancel: '取消',
        }
    }
});

const tabValue = ref('address')
const localAddressCache = useLocalStorage("LocalAddressCache", [] as string[]);

const data = computed(() => {
    if (!localAddressCache.value.includes(jwt.value)) {
        localAddressCache.value.push(jwt.value)
    }
    return localAddressCache.value.map((curJwt: string) => {
        try {
            var payload = JSON.parse(
                decodeURIComponent(
                    atob(curJwt.split(".")[1]
                        .replace(/-/g, "+").replace(/_/g, "/")
                    )
                )
            );
            return {
                valid: true,
                address: payload.address,
                jwt: curJwt
            }
        } catch (e) {
            return {
                valid: false,
                address: `invalid jwt [${curJwt}]`,
                jwt: curJwt
            }
        }
    })
})

const bindAddress = async () => {
    try {
        if (!localAddressCache.value.includes(jwt.value)) {
            localAddressCache.value.push(jwt.value)
        }
        tabValue.value = 'address'
        showMessage(t('bindAddressSuccess'));
    } catch (error) {
        showMessage((error as Error).message || "error", 'error');
    }
}

const confirmChange = (row: any) => {
    selectedRow.value = row
    showChangeConfirm.value = true
}

const confirmUnbind = (row: any) => {
    selectedRow.value = row
    showUnbindConfirm.value = true
}

const changeAddress = () => {
    jwt.value = selectedRow.value.jwt
    location.reload()
}

const unbindAddress = () => {
    if (jwt.value === selectedRow.value.jwt) {
        return;
    }
    localAddressCache.value = localAddressCache.value.filter(
        (curJwt: string) => curJwt !== selectedRow.value.jwt
    );
    showUnbindConfirm.value = false
}
</script>

<template>
    <div>
        <v-alert type="warning" variant="tonal" density="compact" class="mb-4">
            {{ t('tip') }}
        </v-alert>

        <v-tabs v-model="tabValue" color="primary">
            <v-tab value="address">{{ t('address') }}</v-tab>
            <v-tab value="create_or_bind">{{ t('create_or_bind') }}</v-tab>
        </v-tabs>

        <v-window v-model="tabValue">
            <v-window-item value="address">
                <v-table class="mt-4">
                    <thead>
                        <tr>
                            <th>{{ t('address') }}</th>
                            <th>{{ t('actions') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="row in data" :key="row.jwt">
                            <td>{{ row.address }}</td>
                            <td>
                                <v-btn size="small" color="primary" variant="text" @click="confirmChange(row)">
                                    {{ t('changeMailAddress') }}
                                </v-btn>
                                <v-btn size="small" color="warning" variant="text" :disabled="jwt === row.jwt"
                                    @click="confirmUnbind(row)">
                                    {{ t('unbindMailAddress') }}
                                </v-btn>
                            </td>
                        </tr>
                    </tbody>
                </v-table>
            </v-window-item>
            <v-window-item value="create_or_bind">
                <div class="mt-4">
                    <Login :bindUserAddress="bindAddress" />
                </div>
            </v-window-item>
        </v-window>

        <v-dialog v-model="showChangeConfirm" max-width="400">
            <v-card>
                <v-card-text>{{ t('changeMailAddress') }}?</v-card-text>
                <v-card-actions>
                    <v-spacer />
                    <v-btn @click="showChangeConfirm = false">{{ t('cancel') }}</v-btn>
                    <v-btn color="primary" @click="changeAddress">{{ t('changeMailAddress') }}</v-btn>
                </v-card-actions>
            </v-card>
        </v-dialog>

        <v-dialog v-model="showUnbindConfirm" max-width="400">
            <v-card>
                <v-card-text>{{ t('unbindMailAddress') }}?</v-card-text>
                <v-card-actions>
                    <v-spacer />
                    <v-btn @click="showUnbindConfirm = false">{{ t('cancel') }}</v-btn>
                    <v-btn color="warning" @click="unbindAddress">{{ t('unbindMailAddress') }}</v-btn>
                </v-card-actions>
            </v-card>
        </v-dialog>

        <v-snackbar v-model="snackbar.show" :color="snackbar.color" :timeout="2000">
            {{ snackbar.text }}
        </v-snackbar>
    </div>
</template>

// frontend-angular/src/app/views/index/local-address/local-address.component.ts
import { Component, inject, OnInit, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatTabsModule } from '@angular/material/tabs';
import { MatTableModule } from '@angular/material/table';
import { MatButtonModule } from '@angular/material/button';
import { MatDialogModule, MatDialog, MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { GlobalStateService } from '../../../services/global-state.service';
import { SnackbarService } from '../../../services/snackbar.service';
import { LoginComponent } from '../../common/login/login.component';

interface LocalAddressRow {
  valid: boolean;
  address: string;
  jwt: string;
}

@Component({
  selector: 'app-local-address',
  standalone: true,
  imports: [
    CommonModule,
    MatTabsModule,
    MatTableModule,
    MatButtonModule,
    MatDialogModule,
    LoginComponent,
  ],
  template: `
    <div class="local-address">
      <div class="warning-alert mb-3">
        这些地址存储在您的浏览器中，如果您清除浏览器缓存，可能会丢失。
      </div>

      <mat-tab-group [(selectedIndex)]="selectedTab" color="primary" animationDuration="0ms">
        <mat-tab label="地址"></mat-tab>
        <mat-tab label="创建或绑定"></mat-tab>
      </mat-tab-group>

      <div class="tab-content">
        @if (selectedTab === 0) {
          <div class="table-container">
            <table mat-table [dataSource]="data()" class="full-width">
              <ng-container matColumnDef="address">
                <th mat-header-cell *matHeaderCellDef>地址</th>
                <td mat-cell *matCellDef="let row">{{ row.address }}</td>
              </ng-container>

              <ng-container matColumnDef="actions">
                <th mat-header-cell *matHeaderCellDef>操作</th>
                <td mat-cell *matCellDef="let row">
                  <button mat-button color="primary" (click)="confirmChange(row)">切换邮箱地址</button>
                  <button mat-button color="warn" [disabled]="state.jwt() === row.jwt" (click)="confirmUnbind(row)">
                    解绑邮箱地址
                  </button>
                </td>
              </ng-container>

              <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
              <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
            </table>
          </div>
        } @else {
          <div class="login-container">
            <app-login></app-login>
          </div>
        }
      </div>
    </div>
  `,
  styles: [`
    .local-address { padding: 16px 0; }
    .warning-alert {
      display: flex; align-items: center; gap: 8px; padding: 12px 16px;
      background-color: #fff3e0; border-radius: 4px; color: #e65100;
    }
    .tab-content { padding: 16px 0; }
    .table-container { overflow: auto; }
    .full-width { width: 100%; }
    .login-container { margin-top: 16px; }
    .mb-3 { margin-bottom: 12px; }
    :host-context(.dark-theme) .warning-alert { background-color: #4a3000; color: #ffb74d; }
  `]
})
export class LocalAddressComponent implements OnInit {
  state = inject(GlobalStateService);
  private snackbar = inject(SnackbarService);
  private dialog = inject(MatDialog);

  selectedTab = 0;
  displayedColumns = ['address', 'actions'];
  selectedRow = signal<LocalAddressRow | null>(null);

  private localAddressCache = signal<string[]>(
    JSON.parse(localStorage.getItem('LocalAddressCache') || '[]')
  );

  data = computed(() => {
    const currentJwt = this.state.jwt();
    const cache = this.localAddressCache();
    if (currentJwt && !cache.includes(currentJwt)) {
      const newCache = [...cache, currentJwt];
      this.localAddressCache.set(newCache);
      localStorage.setItem('LocalAddressCache', JSON.stringify(newCache));
    }
    return this.localAddressCache().map(jwt => {
      try {
        const payload = JSON.parse(decodeURIComponent(atob(jwt.split('.')[1].replace(/-/g, '+').replace(/_/g, '/'))));
        return { valid: true, address: payload.address, jwt };
      } catch (e) {
        return { valid: false, address: `invalid jwt [${jwt}]`, jwt };
      }
    });
  });

  ngOnInit() {
    const currentJwt = this.state.jwt();
    if (currentJwt) {
      const cache = this.localAddressCache();
      if (!cache.includes(currentJwt)) {
        const newCache = [...cache, currentJwt];
        this.localAddressCache.set(newCache);
        localStorage.setItem('LocalAddressCache', JSON.stringify(newCache));
      }
    }
  }

  confirmChange(row: LocalAddressRow) {
    this.selectedRow.set(row);
    const dialogRef = this.dialog.open(ConfirmDialogComponent, {
      width: '320px',
      data: { title: '切换邮箱地址', message: '切换邮箱地址?', confirmText: '切换邮箱地址', confirmColor: 'primary' }
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) this.changeAddress();
    });
  }

  confirmUnbind(row: LocalAddressRow) {
    this.selectedRow.set(row);
    const dialogRef = this.dialog.open(ConfirmDialogComponent, {
      width: '320px',
      data: { title: '解绑邮箱地址', message: '解绑邮箱地址?', confirmText: '解绑邮箱地址', confirmColor: 'warn' }
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) this.unbindAddress();
    });
  }

  changeAddress() {
    const row = this.selectedRow();
    if (row) {
      this.state.setJwt(row.jwt);
      location.reload();
    }
  }

  unbindAddress() {
    const row = this.selectedRow();
    if (row && this.state.jwt() !== row.jwt) {
      const newCache = this.localAddressCache().filter(jwt => jwt !== row.jwt);
      this.localAddressCache.set(newCache);
      localStorage.setItem('LocalAddressCache', JSON.stringify(newCache));
    }
  }

  bindAddress() {
    const currentJwt = this.state.jwt();
    if (currentJwt) {
      const cache = this.localAddressCache();
      if (!cache.includes(currentJwt)) {
        const newCache = [...cache, currentJwt];
        this.localAddressCache.set(newCache);
        localStorage.setItem('LocalAddressCache', JSON.stringify(newCache));
      }
      this.selectedTab = 0;
      this.snackbar.success('绑定地址成功');
    }
  }
}

// Confirm Dialog Component
@Component({
  selector: 'app-confirm-dialog',
  standalone: true,
  imports: [CommonModule, MatDialogModule, MatButtonModule],
  template: `
    <h2 mat-dialog-title>{{ data.title }}</h2>
    <mat-dialog-content>{{ data.message }}</mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button mat-dialog-close>取消</button>
      <button mat-raised-button [color]="data.confirmColor || 'primary'" [mat-dialog-close]="true">{{ data.confirmText }}</button>
    </mat-dialog-actions>
  `
})
export class ConfirmDialogComponent {
  data = inject(MAT_DIALOG_DATA);
}
