// frontend/src/views/index/AccountSettings.vue
<script setup>
import { ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRouter } from 'vue-router'

import { useGlobalState } from '../../store'
import { api } from '../../api'
import { hashPassword, getRouterPathWithLang } from '../../utils'

const {
    jwt, settings, showAddressCredential, loading, openSettings
} = useGlobalState()
const router = useRouter()

const snackbar = ref({ show: false, text: '', color: 'success' })
const showMessage = (text, color = 'success') => {
    snackbar.value = { show: true, text, color }
}

const showLogout = ref(false)
const showDeleteAccount = ref(false)
const showClearInbox = ref(false)
const showClearSentItems = ref(false)
const showChangePassword = ref(false)
const newPassword = ref('')
const confirmPassword = ref('')

const { locale, t } = useI18n({
    messages: {
        en: {
            logout: "Logout",
            deleteAccount: "Delete Account",
            showAddressCredential: 'Show Address Credential',
            logoutConfirm: 'Are you sure to logout?',
            deleteAccountConfirm: "Are you sure to delete your account and all emails for this account?",
            clearInbox: "Clear Inbox",
            clearSentItems: "Clear Sent Items",
            clearInboxConfirm: "Are you sure to clear all emails in your inbox?",
            clearSentItemsConfirm: "Are you sure to clear all emails in your sent items?",
            success: "Success",
            changePassword: "Change Password",
            newPassword: "New Password",
            confirmPassword: "Confirm Password",
            passwordMismatch: "Passwords do not match",
            passwordChanged: "Password changed successfully",
            cancel: "Cancel",
        },
        zh: {
            logout: '退出登录',
            deleteAccount: "删除账户",
            showAddressCredential: '查看邮箱地址凭证',
            logoutConfirm: '确定要退出登录吗？',
            deleteAccountConfirm: "确定要删除你的账户和其中的所有邮件吗?",
            clearInbox: "清空收件箱",
            clearSentItems: "清空发件箱",
            clearInboxConfirm: "确定要清空你收件箱中的所有邮件吗？",
            clearSentItemsConfirm: "确定要清空你发件箱中的所有邮件吗？",
            success: "成功",
            changePassword: "修改密码",
            newPassword: "新密码",
            confirmPassword: "确认密码",
            passwordMismatch: "密码不匹配",
            passwordChanged: "密码修改成功",
            cancel: "取消",
        }
    }
});

const logout = async () => {
    jwt.value = '';
    await router.push(getRouterPathWithLang("/", locale.value))
    location.reload()
}

const deleteAccount = async () => {
    try {
        await api.fetch(`/api/delete_address`, { method: 'DELETE' });
        jwt.value = '';
        await router.push(getRouterPathWithLang("/", locale.value))
        location.reload()
    } catch (error) {
        showMessage(error.message || "error", 'error');
    }
};

const clearInbox = async () => {
    try {
        await api.fetch(`/api/clear_inbox`, { method: 'DELETE' });
        showMessage(t("success"));
    } catch (error) {
        showMessage(error.message || "error", 'error');
    } finally {
        showClearInbox.value = false;
    }
};

const clearSentItems = async () => {
    try {
        await api.fetch(`/api/clear_sent_items`, { method: 'DELETE' });
        showMessage(t("success"));
    } catch (error) {
        showMessage(error.message || "error", 'error');
    } finally {
        showClearSentItems.value = false;
    }
};

const changePassword = async () => {
    if (newPassword.value !== confirmPassword.value) {
        showMessage(t("passwordMismatch"), 'error');
        return;
    }
    try {
        await api.fetch(`/api/address_change_password`, {
            method: 'POST',
            body: JSON.stringify({
                new_password: await hashPassword(newPassword.value)
            })
        });
        showMessage(t("passwordChanged"));
        newPassword.value = '';
        confirmPassword.value = '';
        showChangePassword.value = false;
    } catch (error) {
        showMessage(error.message || "error", 'error');
    }
};
</script>

<template>
    <div class="d-flex justify-center" v-if="settings.address">
        <v-card variant="flat" max-width="800" width="100%">
            <v-card-text>
                <v-btn @click="showAddressCredential = true" color="primary" variant="outlined" block class="mb-2">
                    {{ t('showAddressCredential') }}
                </v-btn>
                <v-btn v-if="openSettings?.enableAddressPassword" @click="showChangePassword = true" color="info"
                    variant="outlined" block class="mb-2">
                    {{ t('changePassword') }}
                </v-btn>
                <v-btn v-if="openSettings.enableUserDeleteEmail" @click="showClearInbox = true" color="warning"
                    variant="outlined" block class="mb-2">
                    {{ t('clearInbox') }}
                </v-btn>
                <v-btn v-if="openSettings.enableUserDeleteEmail" @click="showClearSentItems = true" color="warning"
                    variant="outlined" block class="mb-2">
                    {{ t('clearSentItems') }}
                </v-btn>
                <v-btn @click="showLogout = true" variant="outlined" block class="mb-2">
                    {{ t('logout') }}
                </v-btn>
                <v-btn v-if="openSettings.enableUserDeleteEmail" @click="showDeleteAccount = true" color="error"
                    variant="outlined" block>
                    {{ t('deleteAccount') }}
                </v-btn>
            </v-card-text>
        </v-card>

        <v-dialog v-model="showLogout" max-width="400">
            <v-card>
                <v-card-title>{{ t('logout') }}</v-card-title>
                <v-card-text>{{ t('logoutConfirm') }}</v-card-text>
                <v-card-actions>
                    <v-spacer />
                    <v-btn @click="showLogout = false">{{ t('cancel') }}</v-btn>
                    <v-btn :loading="loading" @click="logout" color="warning">{{ t('logout') }}</v-btn>
                </v-card-actions>
            </v-card>
        </v-dialog>

        <v-dialog v-model="showDeleteAccount" max-width="400">
            <v-card>
                <v-card-title>{{ t('deleteAccount') }}</v-card-title>
                <v-card-text>{{ t('deleteAccountConfirm') }}</v-card-text>
                <v-card-actions>
                    <v-spacer />
                    <v-btn @click="showDeleteAccount = false">{{ t('cancel') }}</v-btn>
                    <v-btn :loading="loading" @click="deleteAccount" color="error">{{ t('deleteAccount') }}</v-btn>
                </v-card-actions>
            </v-card>
        </v-dialog>

        <v-dialog v-model="showClearInbox" max-width="400">
            <v-card>
                <v-card-title>{{ t('clearInbox') }}</v-card-title>
                <v-card-text>{{ t('clearInboxConfirm') }}</v-card-text>
                <v-card-actions>
                    <v-spacer />
                    <v-btn @click="showClearInbox = false">{{ t('cancel') }}</v-btn>
                    <v-btn :loading="loading" @click="clearInbox" color="warning">{{ t('clearInbox') }}</v-btn>
                </v-card-actions>
            </v-card>
        </v-dialog>

        <v-dialog v-model="showClearSentItems" max-width="400">
            <v-card>
                <v-card-title>{{ t('clearSentItems') }}</v-card-title>
                <v-card-text>{{ t('clearSentItemsConfirm') }}</v-card-text>
                <v-card-actions>
                    <v-spacer />
                    <v-btn @click="showClearSentItems = false">{{ t('cancel') }}</v-btn>
                    <v-btn :loading="loading" @click="clearSentItems" color="warning">{{ t('clearSentItems') }}</v-btn>
                </v-card-actions>
            </v-card>
        </v-dialog>

        <v-dialog v-model="showChangePassword" max-width="400">
            <v-card>
                <v-card-title>{{ t('changePassword') }}</v-card-title>
                <v-card-text>
                    <v-text-field v-model="newPassword" :label="t('newPassword')" type="password" variant="outlined"
                        density="compact" class="mb-3" />
                    <v-text-field v-model="confirmPassword" :label="t('confirmPassword')" type="password"
                        variant="outlined" density="compact" />
                </v-card-text>
                <v-card-actions>
                    <v-spacer />
                    <v-btn @click="showChangePassword = false">{{ t('cancel') }}</v-btn>
                    <v-btn :loading="loading" @click="changePassword" color="info">{{ t('changePassword') }}</v-btn>
                </v-card-actions>
            </v-card>
        </v-dialog>

        <v-snackbar v-model="snackbar.show" :color="snackbar.color" :timeout="2000">
            {{ snackbar.text }}
        </v-snackbar>
    </div>
</template>

// frontend-angular/src/app/views/index/account-settings/account-settings.component.ts
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatDialogModule, MatDialog, MAT_DIALOG_DATA, MatDialogRef } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';

import { GlobalStateService } from '../../../services/global-state.service';
import { ApiService } from '../../../services/api.service';
import { SnackbarService } from '../../../services/snackbar.service';
import { hashPassword } from '../../../utils/index';

@Component({
  selector: 'app-account-settings',
  standalone: true,
  imports: [CommonModule, FormsModule, MatCardModule, MatButtonModule, MatDialogModule, MatFormFieldModule, MatInputModule],
  template: `
    @if (state.settings().address) {
      <div class="settings-container">
        <button mat-stroked-button color="primary" class="full-width mb-2" 
                (click)="state.showAddressCredential.set(true)">
          查看邮箱地址凭证
        </button>
        @if (state.openSettings().enableAddressPassword) {
          <button mat-stroked-button color="accent" class="full-width mb-2" (click)="openChangePasswordDialog()">
            修改密码
          </button>
        }
        @if (state.openSettings().enableUserDeleteEmail) {
          <button mat-stroked-button color="warn" class="full-width mb-2" (click)="openClearInboxDialog()">
            清空收件箱
          </button>
          <button mat-stroked-button color="warn" class="full-width mb-2" (click)="openClearSentItemsDialog()">
            清空发件箱
          </button>
        }
        <button mat-stroked-button class="full-width mb-2" (click)="openLogoutDialog()">
          退出登录
        </button>
        @if (state.openSettings().enableUserDeleteEmail) {
          <button mat-stroked-button color="warn" class="full-width" (click)="openDeleteAccountDialog()">
            删除账户
          </button>
        }
      </div>
    }
  `,
  styles: [`
    .settings-container { max-width: 400px; margin: 0 auto; }
    .full-width { width: 100%; }
    .mb-2 { margin-bottom: 8px; }
  `]
})
export class AccountSettingsComponent {
  state = inject(GlobalStateService);
  private api = inject(ApiService);
  private router = inject(Router);
  private snackbar = inject(SnackbarService);
  private dialog = inject(MatDialog);

  openLogoutDialog() {
    const dialogRef = this.dialog.open(AccountConfirmDialogComponent, {
      width: '320px',
      data: { title: '退出登录', message: '确定要退出登录吗？', confirmText: '退出登录', confirmColor: 'warn' }
    });
    dialogRef.afterClosed().subscribe(result => { if (result) this.logout(); });
  }

  openDeleteAccountDialog() {
    const dialogRef = this.dialog.open(AccountConfirmDialogComponent, {
      width: '320px',
      data: { title: '删除账户', message: '确定要删除你的账户和其中的所有邮件吗?', confirmText: '删除账户', confirmColor: 'warn' }
    });
    dialogRef.afterClosed().subscribe(result => { if (result) this.deleteAccount(); });
  }

  openClearInboxDialog() {
    const dialogRef = this.dialog.open(AccountConfirmDialogComponent, {
      width: '320px',
      data: { title: '清空收件箱', message: '确定要清空你收件箱中的所有邮件吗？', confirmText: '清空收件箱', confirmColor: 'warn' }
    });
    dialogRef.afterClosed().subscribe(result => { if (result) this.clearInbox(); });
  }

  openClearSentItemsDialog() {
    const dialogRef = this.dialog.open(AccountConfirmDialogComponent, {
      width: '320px',
      data: { title: '清空发件箱', message: '确定要清空你发件箱中的所有邮件吗？', confirmText: '清空发件箱', confirmColor: 'warn' }
    });
    dialogRef.afterClosed().subscribe(result => { if (result) this.clearSentItems(); });
  }

  openChangePasswordDialog() {
    const dialogRef = this.dialog.open(ChangePasswordDialogComponent, { width: '400px' });
    dialogRef.afterClosed().subscribe(async (result) => {
      if (result) {
        try {
          await this.api.fetch('/api/address_change_password', {
            method: 'POST',
            body: { new_password: await hashPassword(result) }
          });
          this.snackbar.success('密码修改成功');
        } catch (e: any) {
          this.snackbar.error(e.message || '修改失败');
        }
      }
    });
  }

  async logout() {
    this.state.setJwt('');
    await this.router.navigate(['/']);
    location.reload();
  }

  async deleteAccount() {
    try {
      await this.api.fetch('/api/delete_address', { method: 'DELETE' });
      this.state.setJwt('');
      await this.router.navigate(['/']);
      location.reload();
    } catch (e: any) {
      this.snackbar.error(e.message || '删除失败');
    }
  }

  async clearInbox() {
    try {
      await this.api.fetch('/api/clear_inbox', { method: 'DELETE' });
      this.snackbar.success('清空成功');
    } catch (e: any) {
      this.snackbar.error(e.message || '清空失败');
    }
  }

  async clearSentItems() {
    try {
      await this.api.fetch('/api/clear_sent_items', { method: 'DELETE' });
      this.snackbar.success('清空成功');
    } catch (e: any) {
      this.snackbar.error(e.message || '清空失败');
    }
  }
}

// Confirm Dialog
@Component({
  selector: 'app-account-confirm-dialog',
  standalone: true,
  imports: [CommonModule, MatDialogModule, MatButtonModule],
  template: `
    <h2 mat-dialog-title>{{ data.title }}</h2>
    <mat-dialog-content>{{ data.message }}</mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button mat-dialog-close>取消</button>
      <button mat-raised-button [color]="data.confirmColor || 'primary'" [mat-dialog-close]="true">{{ data.confirmText }}</button>
    </mat-dialog-actions>
  `
})
export class AccountConfirmDialogComponent {
  data = inject(MAT_DIALOG_DATA);
}

// Change Password Dialog
@Component({
  selector: 'app-change-password-dialog',
  standalone: true,
  imports: [CommonModule, FormsModule, MatDialogModule, MatButtonModule, MatFormFieldModule, MatInputModule],
  template: `
    <h2 mat-dialog-title>修改密码</h2>
    <mat-dialog-content>
      <mat-form-field appearance="outline" class="full-width">
        <mat-label>新密码</mat-label>
        <input matInput type="password" [(ngModel)]="newPassword">
      </mat-form-field>
      <mat-form-field appearance="outline" class="full-width">
        <mat-label>确认密码</mat-label>
        <input matInput type="password" [(ngModel)]="confirmPassword">
      </mat-form-field>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button mat-dialog-close>取消</button>
      <button mat-raised-button color="primary" (click)="submit()">修改密码</button>
    </mat-dialog-actions>
  `,
  styles: [`.full-width { width: 100%; }`]
})
export class ChangePasswordDialogComponent {
  private dialogRef = inject(MatDialogRef<ChangePasswordDialogComponent>);
  private snackbar = inject(SnackbarService);
  newPassword = '';
  confirmPassword = '';

  submit() {
    if (this.newPassword !== this.confirmPassword) {
      this.snackbar.error('密码不匹配');
      return;
    }
    this.dialogRef.close(this.newPassword);
  }
}
