// frontend/src/views/admin/RoleAddressConfig.vue
<script setup>
import { ref, onMounted } from 'vue';
import { useI18n } from 'vue-i18n'

import { useGlobalState } from '../../store'
import { api } from '../../api'

const { loading, showSnackbar } = useGlobalState()

const { t } = useI18n({
    messages: {
        en: {
            role: 'Role',
            maxAddressCount: 'Max Address Count',
            save: 'Save',
            successTip: 'Success',
            noRolesAvailable: 'No roles available in system config',
            roleConfigDesc: 'Configure maximum address count for each user role. Role-based limits take priority over global settings.',
            notConfigured: 'Not Configured (Use Global Settings)',
        },
        zh: {
            role: '角色',
            maxAddressCount: '最大地址数量',
            save: '保存',
            successTip: '成功',
            noRolesAvailable: '系统配置中没有可用的角色',
            roleConfigDesc: '为每个用户角色配置最大地址数量。角色配置优先于全局设置。',
            notConfigured: '未配置（使用全局设置）',
        }
    }
});

const systemRoles = ref([])
const tableData = ref([])

const headers = [
    { title: t('role'), key: 'role', width: '200px' },
    { title: t('maxAddressCount'), key: 'max_address_count' },
];

const fetchUserRoles = async () => {
    try {
        const results = await api.fetch(`/admin/user_roles`);
        systemRoles.value = results;
    } catch (error) {
        console.log(error)
        showSnackbar(error.message || "error", 'error')
    }
}

const fetchRoleConfigs = async () => {
    try {
        const { configs } = await api.fetch(`/admin/role_address_config`);
        tableData.value = systemRoles.value.map(roleObj => ({
            role: roleObj.role,
            max_address_count: configs[roleObj.role]?.maxAddressCount ?? null,
        }));
    } catch (error) {
        console.log(error)
        showSnackbar(error.message || "error", 'error')
    }
}

const saveConfig = async () => {
    try {
        const configs = {};
        tableData.value.forEach(row => {
            if (row.max_address_count !== null && row.max_address_count !== undefined) {
                configs[row.role] = { maxAddressCount: row.max_address_count };
            }
        });
        await api.fetch(`/admin/role_address_config`, {
            method: 'POST',
            body: JSON.stringify({ configs })
        });
        showSnackbar(t('successTip'), 'success')
        await fetchRoleConfigs();
    } catch (error) {
        console.log(error)
        showSnackbar(error.message || "error", 'error')
    }
}

onMounted(async () => {
    await fetchUserRoles();
    await fetchRoleConfigs();
})
</script>

<template>
    <div class="d-flex justify-center mt-4">
        <v-card variant="flat" max-width="600" width="100%">
            <v-card-text>
                <v-alert type="info" variant="tonal" class="mb-4">
                    {{ t('roleConfigDesc') }}
                </v-alert>

                <v-alert v-if="systemRoles.length === 0" type="warning" variant="tonal">
                    {{ t('noRolesAvailable') }}
                </v-alert>

                <div v-else>
                    <div class="d-flex justify-end mb-4">
                        <v-btn :loading="loading" color="primary" @click="saveConfig">
                            {{ t('save') }}
                        </v-btn>
                    </div>

                    <v-data-table :headers="headers" :items="tableData" hide-default-footer class="elevation-0">
                        <template v-slot:item.role="{ item }">
                            <v-chip color="info" size="small">{{ item.role }}</v-chip>
                        </template>
                        <template v-slot:item.max_address_count="{ item }">
                            <v-text-field
                                v-model.number="item.max_address_count"
                                type="number"
                                :min="0"
                                :max="999"
                                clearable
                                :placeholder="t('notConfigured')"
                                variant="outlined"
                                density="compact"
                                hide-details
                                style="max-width: 200px"
                            ></v-text-field>
                        </template>
                    </v-data-table>
                </div>
            </v-card-text>
        </v-card>
    </div>
</template>

<style scoped>
</style>

// frontend-angular/src/app/views/admin/role-address-config/role-address-config.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatTableModule } from '@angular/material/table';
import { MatChipsModule } from '@angular/material/chips';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { TranslateModule, TranslateService } from '@ngx-translate/core';
import { GlobalStateService } from '../../../services/global-state.service';
import { ApiService } from '../../../services/api.service';
import { SnackbarService } from '../../../services/snackbar.service';

interface RoleConfig {
  role: string;
  max_address_count: number | null;
}

@Component({
  selector: 'app-admin-role-address-config',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatCardModule,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatTableModule,
    MatChipsModule,
    MatIconModule,
    MatProgressSpinnerModule,
    TranslateModule,
  ],
  template: `
    <div class="center">
      <mat-card appearance="outlined" class="config-card">
        <mat-card-content>
          <div class="alert-info mb-4">
            <mat-icon>info</mat-icon>
            <span>{{ 'roleConfigDesc' | translate }}</span>
          </div>

          @if (systemRoles().length === 0) {
            <div class="alert-warning">
              <mat-icon>warning</mat-icon>
              <span>{{ 'noRolesAvailable' | translate }}</span>
            </div>
          } @else {
            <div class="actions-row mb-4">
              <button mat-raised-button color="primary" (click)="saveConfig()" [disabled]="state.loading()">
                {{ 'save' | translate }}
              </button>
            </div>

            <table mat-table [dataSource]="tableData()" class="full-width">
              <ng-container matColumnDef="role">
                <th mat-header-cell *matHeaderCellDef>{{ 'role' | translate }}</th>
                <td mat-cell *matCellDef="let row">
                  <mat-chip color="primary" highlighted>{{ row.role }}</mat-chip>
                </td>
              </ng-container>

              <ng-container matColumnDef="max_address_count">
                <th mat-header-cell *matHeaderCellDef>{{ 'maxAddressCount' | translate }}</th>
                <td mat-cell *matCellDef="let row">
                  <mat-form-field appearance="outline" class="count-field">
                    <input matInput type="number" [(ngModel)]="row.max_address_count"
                           [placeholder]="'notConfigured' | translate"
                           min="0" max="999">
                  </mat-form-field>
                </td>
              </ng-container>

              <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
              <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
            </table>
          }
        </mat-card-content>
      </mat-card>
    </div>
  `,
  styles: [`
    .center {
      display: flex;
      justify-content: center;
      margin-top: 16px;
    }
    .config-card {
      max-width: 600px;
      width: 100%;
    }
    .full-width {
      width: 100%;
    }
    .mb-4 {
      margin-bottom: 16px;
    }
    .actions-row {
      display: flex;
      justify-content: flex-end;
    }
    .count-field {
      max-width: 200px;
    }
    .alert-info {
      display: flex;
      align-items: center;
      gap: 8px;
      padding: 12px;
      background: #e3f2fd;
      border-radius: 4px;
      color: #1565c0;
    }
    .alert-warning {
      display: flex;
      align-items: center;
      gap: 8px;
      padding: 12px;
      background: #fff3e0;
      border-radius: 4px;
      color: #e65100;
    }
    :host-context(.dark-theme) .alert-info {
      background: #0d47a1;
      color: #90caf9;
    }
    :host-context(.dark-theme) .alert-warning {
      background: #4a3000;
      color: #ffb74d;
    }
  `]
})
export class AdminRoleAddressConfigComponent implements OnInit {
  state = inject(GlobalStateService);
  private api = inject(ApiService);
  private snackbar = inject(SnackbarService);
  private translate = inject(TranslateService);

  systemRoles = signal<{ role: string }[]>([]);
  tableData = signal<RoleConfig[]>([]);
  displayedColumns = ['role', 'max_address_count'];

  async ngOnInit() {
    await this.fetchUserRoles();
    await this.fetchRoleConfigs();
  }

  async fetchUserRoles() {
    try {
      const results = await this.api.fetch<{ role: string }[]>('/admin/user_roles');
      this.systemRoles.set(results || []);
    } catch (error: any) {
      this.snackbar.error(error.message || 'error');
    }
  }

  async fetchRoleConfigs() {
    try {
      const { configs } = await this.api.fetch<{ configs: Record<string, { maxAddressCount: number }> }>('/admin/role_address_config');
      const data = this.systemRoles().map(roleObj => ({
        role: roleObj.role,
        max_address_count: configs?.[roleObj.role]?.maxAddressCount ?? null
      }));
      this.tableData.set(data);
    } catch (error: any) {
      this.snackbar.error(error.message || 'error');
    }
  }

  async saveConfig() {
    try {
      const configs: Record<string, { maxAddressCount: number }> = {};
      this.tableData().forEach(row => {
        if (row.max_address_count !== null && row.max_address_count !== undefined) {
          configs[row.role] = { maxAddressCount: row.max_address_count };
        }
      });
      await this.api.fetch('/admin/role_address_config', {
        method: 'POST',
        body: JSON.stringify({ configs })
      });
      this.snackbar.success(this.translate.instant('successTip'));
      await this.fetchRoleConfigs();
    } catch (error: any) {
      this.snackbar.error(error.message || 'error');
    }
  }
}
