// frontend/src/components/MailContentRenderer.vue
<script setup>
import { ref } from "vue";
import { useI18n } from 'vue-i18n'
import ShadowHtmlComponent from "./ShadowHtmlComponent.vue";
import AiExtractInfo from "./AiExtractInfo.vue";
import { getDownloadEmlUrl } from '../utils/email-parser';
import { utcToLocalDate } from '../utils';
import { useGlobalState } from '../store';

const { preferShowTextMail, useIframeShowMail, useUTCDate } = useGlobalState();

const { t } = useI18n({
  messages: {
    en: {
      delete: 'Delete', deleteMailTip: 'Are you sure?', attachments: 'Attachments',
      downloadMail: 'Download', reply: 'Reply', forward: 'Forward',
      showTextMail: 'Text', showHtmlMail: 'HTML', saveToS3: 'Save S3',
      size: 'Size', fullscreen: 'Fullscreen',
    },
    zh: {
      delete: '删除', deleteMailTip: '确定删除?', attachments: '附件',
      downloadMail: '下载', reply: '回复', forward: '转发',
      showTextMail: '纯文本', showHtmlMail: 'HTML', saveToS3: '保存S3',
      size: '大小', fullscreen: '全屏',
    }
  }
});

const props = defineProps({
  mail: { type: Object, required: true },
  showEMailTo: { type: Boolean, default: true },
  enableUserDeleteEmail: { type: Boolean, default: false },
  showReply: { type: Boolean, default: false },
  showSaveS3: { type: Boolean, default: false },
  onDelete: { type: Function, default: () => { } },
  onReply: { type: Function, default: () => { } },
  onForward: { type: Function, default: () => { } },
  onSaveToS3: { type: Function, default: () => { } }
});

const showTextMail = ref(preferShowTextMail.value);
const showAttachments = ref(false);
const curAttachments = ref([]);
const attachmentLoading = ref(false);
const showFullscreen = ref(false);
const deleteConfirmDialog = ref(false);

const handleDelete = () => { props.onDelete(); };
const handleViewAttachments = () => { curAttachments.value = props.mail.attachments; showAttachments.value = true; };
const handleReply = () => { props.onReply(); };
const handleForward = () => { props.onForward(); };

const handleSaveToS3 = async (filename, blob) => {
  attachmentLoading.value = true;
  try { await props.onSaveToS3(filename, blob); } finally { attachmentLoading.value = false; }
};
</script>

<template>
  <div class="mail-content-renderer">
    <!-- 邮件头信息 -->
    <div class="mail-meta mb-3">
      <div class="text-body-2"><strong>发件人：</strong>{{ mail.source }}</div>
      <div class="text-body-2"><strong>发送时间：</strong>{{ utcToLocalDate(mail.created_at, useUTCDate.value) }}</div>
      <div v-if="showEMailTo" class="text-body-2"><strong>收件人：</strong>{{ mail.address }}</div>
      <div class="text-body-2"><strong>主题：</strong>{{ mail.subject }}</div>
    </div>

    <!-- 操作按钮 -->
    <div class="d-flex flex-wrap ga-2 mb-3">
      <v-btn v-if="enableUserDeleteEmail" size="small" color="error" variant="text" @click="deleteConfirmDialog = true">
        {{ t('delete') }}
      </v-btn>

      <v-btn :href="getDownloadEmlUrl(mail.raw)" :download="mail.id + '.eml'" size="small" color="info" variant="text">
        <v-icon start>mdi-download</v-icon>{{ t('downloadMail') }}
      </v-btn>

      <v-btn v-if="showReply" size="small" color="info" variant="text" @click="handleReply">
        <v-icon start>mdi-reply</v-icon>{{ t('reply') }}
      </v-btn>

      <v-btn v-if="showReply" size="small" color="info" variant="text" @click="handleForward">
        <v-icon start>mdi-forward</v-icon>{{ t('forward') }}
      </v-btn>

      <v-btn size="small" color="info" variant="text" @click="showTextMail = !showTextMail">
        {{ showTextMail ? t('showHtmlMail') : t('showTextMail') }}
      </v-btn>

      <v-btn size="small" color="info" variant="text" @click="showFullscreen = true">
        <v-icon start>mdi-fullscreen</v-icon>{{ t('fullscreen') }}
      </v-btn>

      <v-btn v-if="mail.attachments && mail.attachments.length > 0" size="small" color="info" variant="text"
        @click="handleViewAttachments">
        {{ t('attachments') }}
      </v-btn>
    </div>

    <AiExtractInfo :metadata="mail.metadata" />

    <div class="mail-content">
      <pre v-if="showTextMail" class="mail-text">{{ mail.text }}</pre>
      <iframe v-else-if="useIframeShowMail" :srcdoc="mail.message" class="mail-iframe"></iframe>
      <ShadowHtmlComponent v-else :key="mail.id" :htmlContent="mail.message" class="mail-html" />
    </div>
  </div>

  <v-dialog v-model="showFullscreen" fullscreen>
    <v-card flat rounded="0">
      <v-card-title class="d-flex align-center">
        <span class="text-truncate flex-grow-1 mr-2">{{ mail.subject }}</span>
        <v-btn icon variant="text" @click="showFullscreen = false" class="flex-shrink-0"><v-icon>mdi-close</v-icon></v-btn>
      </v-card-title>
      <v-card-text class="fullscreen-mail-content">
        <pre v-if="showTextMail" class="mail-text">{{ mail.text }}</pre>
        <iframe v-else-if="useIframeShowMail" :srcdoc="mail.message" class="mail-iframe"></iframe>
        <ShadowHtmlComponent v-else :key="mail.id" :htmlContent="mail.message" class="mail-html" />
      </v-card-text>
    </v-card>
  </v-dialog>

  <v-dialog v-model="showAttachments" max-width="500">
    <v-card>
      <v-card-title>{{ t('attachments') }}</v-card-title>
      <v-card-text>
        <v-overlay :model-value="attachmentLoading" contained class="align-center justify-center">
          <v-progress-circular indeterminate></v-progress-circular>
        </v-overlay>
        <v-list>
          <v-list-item v-for="row in curAttachments" :key="row.id">
            <v-list-item-title>{{ row.filename }}</v-list-item-title>
            <v-list-item-subtitle>
              <v-chip size="x-small">{{ t('size') }}: {{ row.size }}</v-chip>
              <v-btn v-if="showSaveS3" @click="handleSaveToS3(row.filename, row.blob)" size="x-small" variant="text">
                {{ t('saveToS3') }}
              </v-btn>
            </v-list-item-subtitle>
            <template v-slot:append>
              <v-btn :href="row.url" :download="row.filename" icon size="small" variant="text">
                <v-icon>mdi-download</v-icon>
              </v-btn>
            </template>
          </v-list-item>
        </v-list>
      </v-card-text>
    </v-card>
  </v-dialog>

  <v-dialog v-model="deleteConfirmDialog" max-width="300">
    <v-card>
      <v-card-title>{{ t('delete') }}</v-card-title>
      <v-card-text>{{ t('deleteMailTip') }}</v-card-text>
      <v-card-actions>
        <v-spacer></v-spacer>
        <v-btn @click="deleteConfirmDialog = false">Cancel</v-btn>
        <v-btn color="error" @click="deleteConfirmDialog = false; handleDelete()">{{ t('delete') }}</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<style scoped>
.mail-content-renderer { display: flex; flex-direction: column; gap: 10px; }
.mail-meta { background: rgba(var(--v-theme-surface-variant), 0.3); padding: 12px; border-radius: 8px; }
.mail-content { margin-top: 10px; flex: 1; }
.mail-text { white-space: pre-wrap; word-wrap: break-word; margin: 0; padding: 0; }
.mail-iframe { width: 100%; height: 100%; border: none; min-height: 400px; }
.mail-html { width: 100%; height: 100%; }
.fullscreen-mail-content { height: calc(100vh - 120px); overflow: auto; }
.fullscreen-mail-content .mail-iframe { min-height: calc(100vh - 120px); }
</style>

// frontend-angular/src/app/components/mail-content-renderer/mail-content-renderer.component.ts
import { Component, Input, Output, EventEmitter, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatChipsModule } from '@angular/material/chips';
import { MatListModule } from '@angular/material/list';
import { MatDialogModule, MatDialog } from '@angular/material/dialog';
import { MatCardModule } from '@angular/material/card';
import { TranslateModule } from '@ngx-translate/core';

import { ParsedMail } from '../../utils/email-parser';
import { getDownloadEmlUrl } from '../../utils/email-parser';
import { utcToLocalDate } from '../../utils/index';
import { AiExtractInfoComponent } from '../ai-extract-info/ai-extract-info.component';
import { ShadowHtmlComponent } from '../shadow-html/shadow-html.component';
import { GlobalStateService } from '../../services/global-state.service';

@Component({
  selector: 'app-mail-content-renderer',
  standalone: true,
  imports: [
    CommonModule,
    MatButtonModule,
    MatIconModule,
    MatChipsModule,
    MatListModule,
    MatDialogModule,
    MatCardModule,
    TranslateModule,
    AiExtractInfoComponent,
    ShadowHtmlComponent,
  ],
  template: `
    <div class="mail-renderer">
      <!-- Mail Info -->
      <div class="mail-info">
        <div class="info-row">
          <span class="label">{{ 'from' | translate }}:</span>
          <span class="value">{{ mail.source }}</span>
        </div>
        <div class="info-row">
          <span class="label">{{ 'time' | translate }}:</span>
          <span class="value">{{ formatDate(mail.created_at) }}</span>
        </div>
        @if (showEMailTo) {
          <div class="info-row">
            <span class="label">{{ 'to' | translate }}:</span>
            <span class="value">{{ mail.address }}</span>
          </div>
        }
        <div class="info-row">
          <span class="label">{{ 'subject' | translate }}:</span>
          <span class="value">{{ mail.subject }}</span>
        </div>
      </div>

      <!-- Actions -->
      <div class="mail-actions">
        @if (enableUserDeleteEmail) {
          <button mat-stroked-button color="warn" (click)="openDeleteDialog()">
            <mat-icon>delete</mat-icon>
            {{ 'delete' | translate }}
          </button>
        }
        <button mat-stroked-button (click)="downloadMail()">
          <mat-icon>download</mat-icon>
          {{ 'downloadMail' | translate }}
        </button>
        @if (showReply) {
          <button mat-stroked-button (click)="onReply.emit()">
            <mat-icon>reply</mat-icon>
            {{ 'reply' | translate }}
          </button>
          <button mat-stroked-button (click)="onForward.emit()">
            <mat-icon>forward</mat-icon>
            {{ 'forward' | translate }}
          </button>
        }
        <button mat-stroked-button (click)="toggleShowText()">
          {{ showText() ? ('showHtmlMail' | translate) : ('showTextMail' | translate) }}
        </button>
        <button mat-stroked-button (click)="openFullscreenDialog()">
          <mat-icon>fullscreen</mat-icon>
          {{ 'fullscreen' | translate }}
        </button>
        @if (mail.attachments && mail.attachments.length > 0) {
          <button mat-stroked-button (click)="openAttachmentsDialog()">
            <mat-icon>attachment</mat-icon>
            {{ 'attachments' | translate }}
          </button>
        }
      </div>

      <!-- AI Extract Info -->
      <app-ai-extract-info [metadata]="mail.metadata || null"></app-ai-extract-info>

      <!-- Mail Body -->
      <div class="mail-body">
        @if (showText()) {
          <pre class="text-content">{{ mail.text }}</pre>
        } @else if (globalState.useIframeShowMail()) {
          <iframe [srcdoc]="mail.message" class="mail-iframe"></iframe>
        } @else {
          <app-shadow-html [htmlContent]="mail.message || ''" class="mail-html"></app-shadow-html>
        }
      </div>
    </div>
  `,
  styles: [`
    .mail-renderer {
      display: flex;
      flex-direction: column;
      gap: 10px;
    }
    .mail-info {
      background: rgba(0, 0, 0, 0.04);
      padding: 12px;
      border-radius: 8px;
      margin-bottom: 12px;
    }
    :host-context(.dark-theme) .mail-info {
      background: rgba(255, 255, 255, 0.08);
    }
    .info-row {
      display: flex;
      margin-bottom: 4px;
      font-size: 14px;
    }
    .label {
      min-width: 70px;
      color: var(--mat-sys-on-surface-variant, #666);
      font-weight: 500;
    }
    .value {
      flex: 1;
      word-break: break-all;
    }
    .mail-actions {
      display: flex;
      gap: 8px;
      margin-bottom: 12px;
      flex-wrap: wrap;
    }
    .mail-body {
      margin-top: 10px;
      flex: 1;
    }
    .text-content {
      white-space: pre-wrap;
      word-wrap: break-word;
      margin: 0;
      padding: 0;
    }
    .mail-iframe {
      width: 100%;
      height: 100%;
      border: none;
      min-height: 400px;
    }
    .mail-html {
      width: 100%;
      height: 100%;
    }
    /* Fullscreen overlay */
    .fullscreen-overlay {
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background: #fff;
      z-index: 9999;
      display: flex;
      flex-direction: column;
    }
    :host-context(.dark-theme) .fullscreen-overlay {
      background: #121212;
      color: #fff;
    }
    .fullscreen-header {
      display: flex;
      align-items: center;
      padding: 12px 16px;
      border-bottom: 1px solid #ccc;
    }
    :host-context(.dark-theme) .fullscreen-header {
      border-bottom-color: #444;
    }
    .fullscreen-title {
      flex: 1;
      font-size: 18px;
      font-weight: 500;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }
    .fullscreen-body {
      flex: 1;
      overflow: auto;
      padding: 16px;
    }
  `]
})
export class MailContentRendererComponent {
  @Input() mail!: ParsedMail;
  @Input() enableUserDeleteEmail = false;
  @Input() showReply = false;
  @Input() showEMailTo = true;
  @Input() showSaveS3 = false;
  @Output() onDelete = new EventEmitter<void>();
  @Output() onReply = new EventEmitter<void>();
  @Output() onForward = new EventEmitter<void>();
  @Output() onSaveToS3 = new EventEmitter<{filename: string, blob: Blob}>();

  globalState = inject(GlobalStateService);
  private dialog = inject(MatDialog);

  showText = signal(false);

  formatDate(date: string): string {
    return utcToLocalDate(date, this.globalState.useUTCDate());
  }

  toggleShowText() {
    this.showText.update(v => !v);
  }

  downloadMail() {
    const url = getDownloadEmlUrl(this.mail.raw);
    const a = document.createElement('a');
    a.href = url;
    a.download = `mail-${this.mail.id}.eml`;
    a.click();
    URL.revokeObjectURL(url);
  }

  openFullscreenDialog() {
    this.dialog.open(MailFullscreenDialogComponent, {
      data: { 
        mail: this.mail, 
        showText: this.showText(),
        useIframeShowMail: this.globalState.useIframeShowMail()
      },
      width: '100vw',
      height: '100vh',
      maxWidth: '100vw',
      maxHeight: '100vh',
      panelClass: 'fullscreen-dialog'
    });
  }

  openAttachmentsDialog() {
    this.dialog.open(MailAttachmentsDialogComponent, {
      data: { attachments: this.mail.attachments, showSaveS3: this.showSaveS3 },
      width: '500px',
    });
  }

  openDeleteDialog() {
    // 直接删除，不需要确认
    this.onDelete.emit();
  }
}

import { MAT_DIALOG_DATA } from '@angular/material/dialog';

// Attachments Dialog Component
@Component({
  selector: 'app-mail-attachments-dialog',
  standalone: true,
  imports: [CommonModule, MatButtonModule, MatIconModule, MatDialogModule, MatListModule, MatChipsModule, TranslateModule],
  template: `
    <h2 mat-dialog-title>{{ 'attachments' | translate }}</h2>
    <mat-dialog-content>
      <mat-list>
        @for (att of data.attachments; track att.id) {
          <mat-list-item>
            <span matListItemTitle>{{ att.filename }}</span>
            <span matListItemLine>
              <mat-chip size="small">{{ att.size }}</mat-chip>
            </span>
            <a mat-icon-button [href]="att.url" [download]="att.filename" matListItemMeta>
              <mat-icon>download</mat-icon>
            </a>
          </mat-list-item>
        }
      </mat-list>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button mat-dialog-close>{{ 'close' | translate }}</button>
    </mat-dialog-actions>
  `
})
export class MailAttachmentsDialogComponent {
  data = inject(MAT_DIALOG_DATA);
}

// Delete Confirm Dialog Component
@Component({
  selector: 'app-mail-delete-dialog',
  standalone: true,
  imports: [CommonModule, MatButtonModule, MatIconModule, MatDialogModule, TranslateModule],
  template: `
    <div class="delete-dialog">
      <mat-icon color="warn">delete_outline</mat-icon>
      <h3>{{ 'delete' | translate }}</h3>
      <p>{{ 'deleteMailTip' | translate }}</p>
      <mat-dialog-actions align="end">
        <button mat-button mat-dialog-close>{{ 'cancel' | translate }}</button>
        <button mat-button color="warn" [mat-dialog-close]="true">{{ 'delete' | translate }}</button>
      </mat-dialog-actions>
    </div>
  `,
  styles: [`
    .delete-dialog {
      text-align: center;
      padding: 16px;
    }
    .delete-dialog mat-icon {
      font-size: 48px;
      width: 48px;
      height: 48px;
    }
    .delete-dialog h3 {
      margin: 16px 0 8px;
    }
    .delete-dialog p {
      color: #666;
      margin-bottom: 16px;
    }
  `]
})
export class MailDeleteDialogComponent {}

// Fullscreen Dialog Component
@Component({
  selector: 'app-mail-fullscreen-dialog',
  standalone: true,
  imports: [CommonModule, MatButtonModule, MatIconModule, MatDialogModule, ShadowHtmlComponent],
  template: `
    <div class="fullscreen-dialog-container">
      <div class="fullscreen-header">
        <span class="fullscreen-title">{{ data.mail.subject }}</span>
        <button mat-icon-button mat-dialog-close>
          <mat-icon>close</mat-icon>
        </button>
      </div>
      <div class="fullscreen-body">
        @if (data.showText) {
          <pre class="text-content">{{ data.mail.text }}</pre>
        } @else if (data.useIframeShowMail) {
          <iframe [srcdoc]="data.mail.message" class="mail-iframe"></iframe>
        } @else {
          <app-shadow-html [htmlContent]="data.mail.message || ''" class="mail-html"></app-shadow-html>
        }
      </div>
    </div>
  `,
  styles: [`
    .fullscreen-dialog-container {
      display: flex;
      flex-direction: column;
      height: 100vh;
      width: 100vw;
    }
    .fullscreen-header {
      display: flex;
      align-items: center;
      padding: 12px 16px;
      border-bottom: 1px solid #ccc;
      flex-shrink: 0;
    }
    :host-context(.dark-theme) .fullscreen-header {
      border-bottom-color: #444;
    }
    .fullscreen-title {
      flex: 1;
      font-size: 18px;
      font-weight: 500;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
      margin-right: 8px;
    }
    .fullscreen-body {
      flex: 1;
      overflow: auto;
      padding: 16px;
    }
    .text-content {
      white-space: pre-wrap;
      word-wrap: break-word;
      margin: 0;
      padding: 0;
    }
    .mail-iframe {
      width: 100%;
      height: 100%;
      border: none;
      min-height: calc(100vh - 80px);
    }
    .mail-html {
      width: 100%;
      height: 100%;
    }
  `]
})
export class MailFullscreenDialogComponent {
  data = inject(MAT_DIALOG_DATA);
}
