// frontend-angular/src/app/views/index/simple-index/simple-index.component.ts
import { Component, inject, OnInit, OnDestroy, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatDialogModule } from '@angular/material/dialog';
import { TranslateModule, TranslateService } from '@ngx-translate/core';
import { GlobalStateService } from '../../../services/global-state.service';
import { ApiService } from '../../../services/api.service';
import { SnackbarService } from '../../../services/snackbar.service';
import { LoginComponent } from '../../common/login/login.component';
import { AccountSettingsComponent } from '../account-settings/account-settings.component';
import { MailContentRendererComponent } from '../../../components/mail-content-renderer/mail-content-renderer.component';
import { processItem } from '../../../utils/email-parser';

@Component({
  selector: 'app-simple-index',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatButtonModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatDialogModule,
    TranslateModule,
    LoginComponent,
    AccountSettingsComponent,
    MailContentRendererComponent,
  ],
  template: `
    <div class="simple-index-container">
      @if (!state.settings().address) {
        <mat-card appearance="outlined">
          <mat-card-content>
            <app-login></app-login>
          </mat-card-content>
        </mat-card>
      } @else {
        <mat-card appearance="outlined" class="mb-4">
          <mat-card-content class="text-center">
            <div class="address-display mb-4">{{ state.settings().address }}</div>
            <div class="actions-row">
              <button mat-stroked-button color="primary" (click)="refreshMails()" [disabled]="state.loading()">
                <mat-icon>refresh</mat-icon>
                {{ 'refreshMails' | translate }}
              </button>
              <button mat-stroked-button (click)="copyAddress()">
                <mat-icon>content_copy</mat-icon>
                {{ 'copyAddress' | translate }}
              </button>
              <button mat-stroked-button (click)="exitSimpleIndex()">
                <mat-icon>exit_to_app</mat-icon>
                {{ 'exitSimpleIndex' | translate }}
              </button>
              <button mat-stroked-button (click)="showAccountSettingsCard.set(true)">
                <mat-icon>settings</mat-icon>
                {{ 'accountSettings' | translate }}
              </button>
            </div>
            @if (isFirstPage()) {
              <div class="refresh-timer mt-3">
                {{ 'refreshAfter' | translate:{ msg: Math.max(0, currentAutoRefreshInterval()) } }}
              </div>
            }
          </mat-card-content>
        </mat-card>

        @if (showAccountSettingsCard()) {
          <mat-card appearance="outlined" class="mb-4">
            <mat-card-header>
              <mat-card-title>{{ 'accountSettings' | translate }}</mat-card-title>
              <span class="spacer"></span>
              <button mat-icon-button (click)="showAccountSettingsCard.set(false)">
                <mat-icon>close</mat-icon>
              </button>
            </mat-card-header>
            <mat-card-content>
              <app-account-settings></app-account-settings>
            </mat-card-content>
          </mat-card>
        } @else {
          <mat-card appearance="outlined" class="text-left">
            <mat-card-content>
              @if (totalCount() > 1) {
                <div class="pagination-row mb-4">
                  <button mat-button [disabled]="!canGoPrev()" (click)="prevPage()">
                    <mat-icon>chevron_left</mat-icon>
                    {{ 'prevPage' | translate }}
                  </button>
                  <span class="page-info">
                    {{ 'mailCount' | translate:{ current: currentPage(), total: totalCount() } }}
                  </span>
                  <button mat-button [disabled]="!canGoNext()" (click)="nextPage()">
                    {{ 'nextPage' | translate }}
                    <mat-icon>chevron_right</mat-icon>
                  </button>
                </div>
              }

              @if (!currentMail()) {
                <div class="empty-state">
                  <mat-icon class="empty-icon">email</mat-icon>
                  <h3>{{ 'noMails' | translate }}</h3>
                </div>
              } @else {
                @if (currentMail()?.subject) {
                  <h3 class="mb-4">{{ currentMail()?.subject }}</h3>
                }
                <app-mail-content-renderer
                  [mail]="currentMail()!"
                  [showReply]="false"
                  [showEMailTo]="false"
                  [enableUserDeleteEmail]="state.openSettings().enableUserDeleteEmail"
                  (onDelete)="deleteMail()">
                </app-mail-content-renderer>
              }
            </mat-card-content>
          </mat-card>
        }
      }
    </div>
  `,
  styles: [`
    .simple-index-container {
      max-width: 800px;
      margin: 0 auto;
    }
    .mb-4 {
      margin-bottom: 16px;
    }
    .mt-3 {
      margin-top: 12px;
    }
    .text-center {
      text-align: center;
    }
    .text-left {
      text-align: left;
    }
    .address-display {
      font-size: 1.25rem;
      font-weight: bold;
    }
    .actions-row {
      display: flex;
      justify-content: center;
      gap: 8px;
      flex-wrap: wrap;
    }
    .refresh-timer {
      font-size: 0.875rem;
      color: rgba(0, 0, 0, 0.6);
    }
    :host-context(.dark-theme) .refresh-timer {
      color: rgba(255, 255, 255, 0.6);
    }
    .pagination-row {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .page-info {
      font-size: 0.875rem;
    }
    .empty-state {
      text-align: center;
      padding: 48px;
    }
    .empty-icon {
      font-size: 64px;
      width: 64px;
      height: 64px;
      color: #9e9e9e;
    }
    mat-card-header {
      display: flex;
      align-items: center;
    }
    .spacer {
      flex: 1;
    }
  `]
})
export class SimpleIndexComponent implements OnInit, OnDestroy {
  state = inject(GlobalStateService);
  private api = inject(ApiService);
  private snackbar = inject(SnackbarService);
  private translate = inject(TranslateService);

  Math = Math;

  currentPage = signal(1);
  totalCount = signal(0);
  currentMail = signal<any>(null);
  showAccountSettingsCard = signal(false);
  currentAutoRefreshInterval = signal(60);
  private timer: any = null;

  isFirstPage = computed(() => this.currentPage() === 1);
  canGoPrev = computed(() => this.currentPage() > 1);
  canGoNext = computed(() => this.currentPage() < this.totalCount());

  async ngOnInit() {
    await this.api.getSettings();
    await this.fetchMails();

    this.timer = setInterval(async () => {
      if (!this.isFirstPage()) {
        this.currentAutoRefreshInterval.set(60);
        return;
      }

      const newVal = this.currentAutoRefreshInterval() - 1;
      this.currentAutoRefreshInterval.set(newVal);
      if (newVal <= 0) {
        await this.refreshMails();
      }
    }, 1000);
  }

  ngOnDestroy() {
    if (this.timer) {
      clearInterval(this.timer);
    }
  }

  async fetchMails() {
    if (!this.state.settings().address) return;
    try {
      const { results, count } = await this.api.fetch<{ results: any[]; count: number }>(
        `/api/mails?limit=1&offset=${this.currentPage() - 1}`
      );
      if (count > 0) {
        this.totalCount.set(count);
      }
      const rawMail = results && results.length > 0 ? results[0] : null;
      this.currentMail.set(rawMail ? await processItem(rawMail) : null);
    } catch (error: any) {
      console.error('Failed to fetch mails:', error);
      this.snackbar.error('获取邮件失败');
    }
  }

  async deleteMail() {
    const mail = this.currentMail();
    if (!mail) return;
    try {
      await this.api.fetch(`/api/mails/${mail.id}`, { method: 'DELETE' });
      this.snackbar.success(this.translate.instant('deleteSuccess'));
      this.currentMail.set(null);
      await this.refreshMails();
    } catch (error: any) {
      console.error('Failed to delete mail:', error);
      this.snackbar.error('删除邮件失败');
    }
  }

  async refreshMails() {
    if (this.state.loading()) return;
    this.currentPage.set(1);
    this.showAccountSettingsCard.set(false);
    this.currentAutoRefreshInterval.set(60);
    await this.fetchMails();
    this.snackbar.success(this.translate.instant('refreshSuccess'));
  }

  async copyAddress() {
    try {
      await navigator.clipboard.writeText(this.state.settings().address);
      this.snackbar.success(this.translate.instant('addressCopied'));
    } catch (error) {
      this.snackbar.error('复制失败');
    }
  }

  exitSimpleIndex() {
    this.state.useSimpleIndex.set(false);
    localStorage.setItem('useSimpleIndex', 'false');
  }

  prevPage() {
    if (this.canGoPrev()) {
      this.currentPage.update(p => p - 1);
      this.fetchMails();
    }
  }

  nextPage() {
    if (this.canGoNext()) {
      this.currentPage.update(p => p + 1);
      this.fetchMails();
    }
  }
}

// frontend/src/views/index/SimpleIndex.vue
<script setup>
import { ref, onMounted, computed, watch, onBeforeUnmount } from 'vue'
import { useI18n } from 'vue-i18n'

import { useGlobalState } from '../../store'
import { api } from '../../api'
import Login from '../common/Login.vue'
import AccountSettings from './AccountSettings.vue'
import { processItem } from '../../utils/email-parser'
import MailContentRenderer from '../../components/MailContentRenderer.vue'

const { jwt, settings, useSimpleIndex, showAddressCredential, openSettings, loading } = useGlobalState()

const snackbar = ref({ show: false, text: '', color: 'success' })
const showMessage = (text, color = 'success') => {
    snackbar.value = { show: true, text, color }
}

const currentPage = ref(1)
const totalCount = ref(0)
const currentMail = ref(null)
const showAccountSettingsCard = ref(false)
const currentAutoRefreshInterval = ref(60)
const timer = ref(null)

const { t } = useI18n({
    messages: {
        en: {
            exitSimpleIndex: 'Exit Simple',
            copyAddress: 'Copy',
            addressCopied: 'Address copied successfully',
            refreshMails: 'Refresh',
            noMails: 'No mails found',
            prevPage: 'Previous',
            nextPage: 'Next',
            refreshSuccess: 'Mails refreshed successfully',
            mailCount: '{current} / {total} emails',
            accountSettings: "Account Settings",
            addressCredential: 'Mail Address Credential',
            addressCredentialTip: 'Please copy the Mail Address Credential and you can use it to login',
            deleteSuccess: 'Mail deleted successfully',
            refreshAfter: 'Refresh After {msg} Seconds',
            close: 'Close',
        },
        zh: {
            exitSimpleIndex: '退出极简',
            copyAddress: '复制',
            addressCopied: '地址复制成功',
            refreshMails: '刷新',
            noMails: '暂无邮件',
            prevPage: '上一页',
            nextPage: '下一页',
            refreshSuccess: '邮件刷新成功',
            mailCount: '{current} / {total} 封邮件',
            accountSettings: "账户设置",
            addressCredential: '邮箱地址凭证',
            addressCredentialTip: '请复制邮箱地址凭证，你可以使用它登录你的邮箱。',
            deleteSuccess: '邮件删除成功',
            refreshAfter: '{msg}秒后刷新',
            close: '关闭',
        }
    }
})

const copyAddress = async () => {
    try {
        await navigator.clipboard.writeText(settings.value.address)
        showMessage(t('addressCopied'))
    } catch (error) {
        showMessage('复制失败', 'error')
    }
}

const fetchMails = async () => {
    if (!settings.value.address) return
    try {
        const { results, count } = await api.fetch(`/api/mails?limit=1&offset=${currentPage.value - 1}`)
        totalCount.value = count > 0 ? count : totalCount.value;
        const rawMail = results && results.length > 0 ? results[0] : null
        currentMail.value = rawMail ? await processItem(rawMail) : null
    } catch (error) {
        console.error('Failed to fetch mails:', error)
        showMessage('获取邮件失败', 'error')
    }
}

const deleteMail = async () => {
    if (!currentMail.value) return;
    try {
        await api.fetch(`/api/mails/${currentMail.value.id}`, { method: 'DELETE' });
        showMessage(t('deleteSuccess'));
        currentMail.value = null;
        await refreshMails();
    } catch (error) {
        console.error('Failed to delete mail:', error);
        showMessage('删除邮件失败', 'error');
    }
}

const refreshMails = async () => {
    if (loading.value) return
    currentPage.value = 1
    showAccountSettingsCard.value = false
    currentAutoRefreshInterval.value = 60
    await fetchMails()
    showMessage(t('refreshSuccess'))
}

const currentPageDisplay = computed(() => currentPage.value)
const totalPages = computed(() => Math.max(1, totalCount.value))
const canGoPrev = computed(() => currentPage.value > 1)
const canGoNext = computed(() => currentPage.value < totalPages.value)
const isFirstPage = computed(() => currentPage.value === 1)

const prevPage = async () => {
    if (canGoPrev.value) {
        currentPage.value--
    }
}

const nextPage = async () => {
    if (canGoNext.value) {
        currentPage.value++
    }
}

watch(currentPage, () => {
    fetchMails()
})

onMounted(async () => {
    await api.getSettings()
    await fetchMails()

    timer.value = setInterval(async () => {
        if (!isFirstPage.value) {
            currentAutoRefreshInterval.value = 60
            return
        }

        if (--currentAutoRefreshInterval.value <= 0) {
            await refreshMails()
        }
    }, 1000)
})

onBeforeUnmount(() => {
    clearInterval(timer.value)
})
</script>

<template>
    <div class="simple-index-container">
        <div v-if="!settings.address">
            <v-card variant="flat">
                <v-card-text>
                    <Login />
                </v-card-text>
            </v-card>
        </div>

        <div v-else>
            <v-card variant="flat" class="mb-4">
                <v-card-text class="text-center">
                    <div class="text-h6 font-weight-bold mb-4">{{ settings.address }}</div>
                    <div class="d-flex justify-center ga-2 flex-wrap">
                        <v-btn @click="refreshMails" :loading="loading" color="primary" variant="tonal" size="small"
                            prepend-icon="mdi-refresh">
                            {{ t('refreshMails') }}
                        </v-btn>
                        <v-btn @click="copyAddress" variant="tonal" size="small" prepend-icon="mdi-content-copy">
                            {{ t('copyAddress') }}
                        </v-btn>
                        <v-btn @click="useSimpleIndex = false" variant="tonal" size="small"
                            prepend-icon="mdi-exit-to-app">
                            {{ t('exitSimpleIndex') }}
                        </v-btn>
                        <v-btn @click="showAccountSettingsCard = true" variant="tonal" size="small"
                            prepend-icon="mdi-cog">
                            {{ t('accountSettings') }}
                        </v-btn>
                    </div>
                    <div v-if="isFirstPage" class="text-caption text-medium-emphasis mt-3">
                        {{ t('refreshAfter', { msg: Math.max(0, currentAutoRefreshInterval) }) }}
                    </div>
                </v-card-text>
            </v-card>

            <v-card v-if="showAccountSettingsCard" variant="flat" class="mb-4">
                <v-card-title class="d-flex justify-space-between align-center">
                    {{ t('accountSettings') }}
                    <v-btn icon variant="text" @click="showAccountSettingsCard = false">
                        <v-icon>mdi-close</v-icon>
                    </v-btn>
                </v-card-title>
                <v-card-text>
                    <AccountSettings />
                </v-card-text>
            </v-card>

            <v-card v-else variant="flat" class="text-left">
                <v-card-text>
                    <div v-if="totalCount > 1" class="d-flex justify-space-between align-center mb-4">
                        <v-btn @click="prevPage" :disabled="!canGoPrev" variant="text" size="small"
                            prepend-icon="mdi-chevron-left">
                            {{ t('prevPage') }}
                        </v-btn>
                        <span class="text-caption">
                            {{ t('mailCount', { current: currentPageDisplay, total: totalCount }) }}
                        </span>
                        <v-btn @click="nextPage" :disabled="!canGoNext" variant="text" size="small"
                            append-icon="mdi-chevron-right">
                            {{ t('nextPage') }}
                        </v-btn>
                    </div>

                    <v-empty-state v-if="!currentMail" icon="mdi-email-outline" :title="t('noMails')" />
                    <div v-else>
                        <h3 v-if="currentMail.subject" class="mb-4">{{ currentMail.subject }}</h3>
                        <MailContentRenderer :mail="currentMail" :showEMailTo="false" :showReply="false"
                            :enableUserDeleteEmail="openSettings.enableUserDeleteEmail" :showSaveS3="false"
                            :onDelete="deleteMail" />
                    </div>
                </v-card-text>
            </v-card>
        </div>

        <v-dialog v-model="showAddressCredential" max-width="500">
            <v-card>
                <v-card-title>{{ t('addressCredential') }}</v-card-title>
                <v-card-text>
                    <p class="mb-4">{{ t("addressCredentialTip") }}</p>
                    <v-card variant="tonal">
                        <v-card-text>
                            <strong>{{ jwt }}</strong>
                        </v-card-text>
                    </v-card>
                </v-card-text>
                <v-card-actions>
                    <v-spacer />
                    <v-btn @click="showAddressCredential = false">{{ t('close') }}</v-btn>
                </v-card-actions>
            </v-card>
        </v-dialog>

        <v-snackbar v-model="snackbar.show" :color="snackbar.color" :timeout="2000">
            {{ snackbar.text }}
        </v-snackbar>
    </div>
</template>

<style scoped>
.simple-index-container {
    max-width: 800px;
    margin: 0 auto;
}
</style>
