// frontend/src/views/index/AutoReply.vue
<script setup>
import { useI18n } from 'vue-i18n'
import { onMounted, ref } from 'vue'

import { useGlobalState } from '../../store'
import { api } from '../../api'

const snackbar = ref({ show: false, text: '', color: 'success' })
const showMessage = (text, color = 'success') => {
    snackbar.value = { show: true, text, color }
}

const sourcePrefix = ref("")
const enableAutoReply = ref(false)
const autoReplyMessage = ref("")
const subject = ref("")
const name = ref("")

const { settings } = useGlobalState()

const { t } = useI18n({
    locale: 'zh',
    messages: {
        en: {
            success: 'Success',
            settings: 'Settings',
            sourcePrefix: 'Source Mail Prefix',
            name: 'Name',
            enableAutoReply: 'Enable Auto Reply',
            subject: 'Subject',
            autoReply: 'Auto Reply',
            save: 'Save',
        },
        zh: {
            success: '成功',
            settings: '设置',
            sourcePrefix: '来源邮件前缀',
            name: '名称',
            enableAutoReply: '启用自动回复',
            subject: '主题',
            autoReply: '自动回复',
            save: '保存',
        }
    }
});

const fetchData = async () => {
    try {
        const res = await api.fetch("/api/auto_reply")
        sourcePrefix.value = res.source_prefix || ""
        enableAutoReply.value = res.enabled || false
        name.value = res.name || ""
        autoReplyMessage.value = res.message || ""
        subject.value = res.subject || ""
    } catch (error) {
        showMessage(error.message || "error", 'error');
    }
}

const saveData = async () => {
    try {
        await api.fetch("/api/auto_reply", {
            method: "POST",
            body: JSON.stringify({
                auto_reply: {
                    enabled: enableAutoReply.value,
                    source_prefix: sourcePrefix.value,
                    name: name.value,
                    message: autoReplyMessage.value,
                    subject: subject.value,
                }
            })
        })
        showMessage(t("success"))
    } catch (error) {
        showMessage(error.message || "error", 'error');
    }
}

onMounted(async () => {
    await fetchData()
})
</script>

<template>
    <div class="d-flex justify-center">
        <v-card v-if="settings.address" variant="flat" max-width="800" width="100%">
            <v-card-title class="d-flex justify-space-between align-center">
                {{ t('settings') }}
                <v-btn color="primary" @click="saveData">{{ t('save') }}</v-btn>
            </v-card-title>
            <v-card-text>
                <v-switch v-model="enableAutoReply" :label="t('enableAutoReply')" color="primary" hide-details
                    class="mb-4" />
                <v-text-field v-model="name" :label="t('name')" :disabled="!enableAutoReply" variant="outlined"
                    density="compact" class="mb-3" />
                <v-text-field v-model="sourcePrefix" :label="t('sourcePrefix')" :disabled="!enableAutoReply"
                    variant="outlined" density="compact" class="mb-3" />
                <v-text-field v-model="subject" :label="t('subject')" :disabled="!enableAutoReply" variant="outlined"
                    density="compact" class="mb-3" />
                <v-textarea v-model="autoReplyMessage" :label="t('autoReply')" :disabled="!enableAutoReply"
                    variant="outlined" rows="4" />
            </v-card-text>
        </v-card>

        <v-snackbar v-model="snackbar.show" :color="snackbar.color" :timeout="2000">
            {{ snackbar.text }}
        </v-snackbar>
    </div>
</template>

// frontend-angular/src/app/views/index/auto-reply/auto-reply.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';

import { GlobalStateService } from '../../../services/global-state.service';
import { ApiService } from '../../../services/api.service';
import { SnackbarService } from '../../../services/snackbar.service';

@Component({
  selector: 'app-auto-reply',
  standalone: true,
  imports: [
    CommonModule, FormsModule, MatCardModule, MatButtonModule,
    MatFormFieldModule, MatInputModule, MatSlideToggleModule
  ],
  template: `
    @if (state.settings().address) {
      <div class="auto-reply-container">
        <div class="header">
          <h3>设置</h3>
          <button mat-raised-button color="primary" (click)="saveData()">保存</button>
        </div>

        <mat-slide-toggle [(ngModel)]="enableAutoReply" class="mb-3">
          启用自动回复
        </mat-slide-toggle>

        <mat-form-field appearance="outline" class="full-width">
          <mat-label>名称</mat-label>
          <input matInput [(ngModel)]="name" [disabled]="!enableAutoReply">
        </mat-form-field>

        <mat-form-field appearance="outline" class="full-width">
          <mat-label>来源邮件前缀</mat-label>
          <input matInput [(ngModel)]="sourcePrefix" [disabled]="!enableAutoReply">
        </mat-form-field>

        <mat-form-field appearance="outline" class="full-width">
          <mat-label>主题</mat-label>
          <input matInput [(ngModel)]="subject" [disabled]="!enableAutoReply">
        </mat-form-field>

        <mat-form-field appearance="outline" class="full-width">
          <mat-label>自动回复内容</mat-label>
          <textarea matInput [(ngModel)]="autoReplyMessage" rows="4" [disabled]="!enableAutoReply"></textarea>
        </mat-form-field>
      </div>
    }
  `,
  styles: [`
    .auto-reply-container { max-width: 600px; margin: 0 auto; }
    .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px; }
    .full-width { width: 100%; margin-bottom: 16px; }
    .mb-3 { margin-bottom: 16px; display: block; }
  `]
})
export class AutoReplyComponent implements OnInit {
  state = inject(GlobalStateService);
  private api = inject(ApiService);
  private snackbar = inject(SnackbarService);

  sourcePrefix = '';
  enableAutoReply = false;
  autoReplyMessage = '';
  subject = '';
  name = '';

  async ngOnInit() {
    await this.fetchData();
  }

  async fetchData() {
    try {
      const res = await this.api.fetch<any>('/api/auto_reply');
      this.sourcePrefix = res.source_prefix || '';
      this.enableAutoReply = res.enabled || false;
      this.name = res.name || '';
      this.autoReplyMessage = res.message || '';
      this.subject = res.subject || '';
    } catch (e: any) {
      this.snackbar.error(e.message || '加载失败');
    }
  }

  async saveData() {
    try {
      await this.api.fetch('/api/auto_reply', {
        method: 'POST',
        body: {
          auto_reply: {
            enabled: this.enableAutoReply,
            source_prefix: this.sourcePrefix,
            name: this.name,
            message: this.autoReplyMessage,
            subject: this.subject,
          }
        }
      });
      this.snackbar.success('保存成功');
    } catch (e: any) {
      this.snackbar.error(e.message || '保存失败');
    }
  }
}
