// frontend/src/components/MailBox.vue
<script setup>
import { watch, onMounted, ref, onBeforeUnmount, computed } from "vue";
import { useI18n } from 'vue-i18n'
import { useGlobalState } from '../store'
import { useIsMobile } from '../utils/composables'
import { processItem } from '../utils/email-parser'
import { utcToLocalDate } from '../utils';
import MailContentRenderer from "./MailContentRenderer.vue";
import AiExtractInfo from "./AiExtractInfo.vue";

const isMobile = useIsMobile()

const snackbar = ref(false)
const snackbarText = ref('')
const snackbarColor = ref('info')

const showMessage = (text, color = 'info') => {
    snackbarText.value = text
    snackbarColor.value = color
    snackbar.value = true
}

const message = {
    error: (text) => showMessage(text, 'error'),
    success: (text) => showMessage(text, 'success'),
}

const props = defineProps({
  enableUserDeleteEmail: { type: Boolean, default: false },
  showEMailTo: { type: Boolean, default: true },
  fetchMailData: { type: Function, default: () => { }, required: true },
  deleteMail: { type: Function, default: () => { } },
  showReply: { type: Boolean, default: false },
  showSaveS3: { type: Boolean, default: false },
  saveToS3: { type: Function, default: () => { } },
  showFilterInput: { type: Boolean, default: false },
})

const localFilterKeyword = ref('')

const {
  isDark, indexTab, loading, useUTCDate,
  autoRefresh, configAutoRefreshInterval, sendMailModel
} = useGlobalState()
const autoRefreshInterval = ref(configAutoRefreshInterval.value)
const rawData = ref([])
const timer = ref(null)

const count = ref(0)
const page = ref(1)
const pageSize = ref(20)

const data = computed(() => {
  if (!localFilterKeyword.value || localFilterKeyword.value.trim() === '') {
    return rawData.value;
  }
  const keyword = localFilterKeyword.value.toLowerCase();
  return rawData.value.filter(mail => {
    const searchFields = [mail.subject || '', mail.text || '', mail.message || ''].map(f => f.toLowerCase());
    return searchFields.some(field => field.includes(keyword));
  });
})

const canGoPrevMail = computed(() => {
  if (!curMail.value) return false
  const currentIndex = data.value.findIndex(mail => mail.id === curMail.value.id)
  return currentIndex > 0 || page.value > 1
})

const canGoNextMail = computed(() => {
  if (!curMail.value) return false
  const currentIndex = data.value.findIndex(mail => mail.id === curMail.value.id)
  return currentIndex < data.value.length - 1 || count.value > page.value * pageSize.value
})

const prevMail = async () => {
  if (!canGoPrevMail.value) return
  const currentIndex = data.value.findIndex(mail => mail.id === curMail.value.id)
  if (currentIndex > 0) {
    curMail.value = data.value[currentIndex - 1]
  } else if (page.value > 1) {
    page.value--
    await refresh()
    if (data.value.length > 0) curMail.value = data.value[data.value.length - 1]
  }
}

const nextMail = async () => {
  if (!canGoNextMail.value) return
  const currentIndex = data.value.findIndex(mail => mail.id === curMail.value.id)
  if (currentIndex < data.value.length - 1) {
    curMail.value = data.value[currentIndex + 1]
  } else if (count.value > page.value * pageSize.value) {
    page.value++
    await refresh()
    if (data.value.length > 0) curMail.value = data.value[0]
  }
}

const curMail = ref(null);
const showMailDrawer = ref(false);
const multiActionMode = ref(false)
const showMultiActionDownload = ref(false)
const showMultiActionDelete = ref(false)
const multiActionDownloadZip = ref({})
const multiActionDeleteProgress = ref({ percentage: 0, tip: '0/0' })
const deleteConfirmDialog = ref(false)

const { t } = useI18n({
  messages: {
    en: {
      success: 'Success', autoRefresh: 'Auto Refresh', refreshAfter: 'Refresh After {msg}s',
      refresh: 'Refresh', attachments: 'Show Attachments', downloadMail: 'Download Mail',
      pleaseSelectMail: "Please select mail", delete: 'Delete', deleteMailTip: 'Are you sure?',
      reply: 'Reply', forwardMail: 'Forward', showTextMail: 'Show Text', showHtmlMail: 'Show Html',
      saveToS3: 'Save to S3', multiAction: 'Multi', cancelMultiAction: 'Cancel',
      selectAll: 'Select All', unselectAll: 'Unselect All', prevMail: 'Prev', nextMail: 'Next',
      keywordQueryTip: 'Filter', query: 'Query',
    },
    zh: {
      success: '成功', autoRefresh: '自动刷新', refreshAfter: '{msg}秒后刷新',
      refresh: '刷新', downloadMail: '下载邮件', attachments: '查看附件',
      pleaseSelectMail: "请选择邮件", delete: '删除', deleteMailTip: '确定删除?',
      reply: '回复', forwardMail: '转发', showTextMail: '纯文本', showHtmlMail: 'HTML',
      saveToS3: '保存到S3', multiAction: '多选', cancelMultiAction: '取消',
      selectAll: '全选', unselectAll: '取消全选', prevMail: '上一封', nextMail: '下一封',
      keywordQueryTip: '过滤', query: '查询',
    }
  }
});

const setupAutoRefresh = async (autoRefresh) => {
  autoRefreshInterval.value = configAutoRefreshInterval.value;
  if (autoRefresh) {
    clearInterval(timer.value);
    timer.value = setInterval(async () => {
      if (loading.value) return;
      autoRefreshInterval.value--;
      if (autoRefreshInterval.value <= 0) {
        autoRefreshInterval.value = configAutoRefreshInterval.value;
        await backFirstPageAndRefresh();
      }
    }, 1000)
  } else {
    clearInterval(timer.value)
    timer.value = null
  }
}

watch(autoRefresh, async (val) => { setupAutoRefresh(val) }, { immediate: true })
watch([page, pageSize], async () => { await refresh(); })
// 当从移动端切换到桌面端时，关闭抽屉
watch(isMobile, (val) => { if (!val) showMailDrawer.value = false; })

const refresh = async () => {
  try {
    const { results, count: totalCount } = await props.fetchMailData(pageSize.value, (page.value - 1) * pageSize.value);
    loading.value = true;
    rawData.value = await Promise.all(results.map(async (item) => {
      item.checked = false;
      return await processItem(item);
    }));
    if (totalCount > 0) count.value = totalCount;
    curMail.value = null;
    if (!isMobile.value && data.value.length > 0) curMail.value = data.value[0];
  } catch (error) {
    message.error(error.message || "error");
  } finally {
    loading.value = false;
  }
};

const backFirstPageAndRefresh = async () => { page.value = 1; await refresh(); }

const clickRow = async (row) => {
  if (multiActionMode.value) { row.checked = !row.checked; return; }
  curMail.value = row;
  if (isMobile.value) showMailDrawer.value = true;
};

const mailItemClass = (row) => {
  return curMail.value && row.id == curMail.value.id ? 'selected-mail' : '';
};

const deleteMail = async () => {
  try {
    await props.deleteMail(curMail.value.id);
    message.success(t("success"));
    curMail.value = null;
    await refresh();
  } catch (error) {
    message.error(error.message || "error");
  }
};

const replyMail = async () => {
  const emailRegex = /(.+?) <(.+?)>/;
  let toMail = curMail.value.originalSource;
  let toName = ""
  const match = emailRegex.exec(curMail.value.source);
  if (match) { toName = match[1]; toMail = match[2]; }
  Object.assign(sendMailModel.value, {
    toName, toMail, subject: `${t('reply')}: ${curMail.value.subject}`,
    contentType: 'rich',
    content: curMail.value.text ? `<p><br></p><blockquote>${curMail.value.text}</blockquote>` : '',
  });
  indexTab.value = 'sendmail';
};

const forwardMail = async () => {
  Object.assign(sendMailModel.value, {
    subject: `${t('forwardMail')}: ${curMail.value.subject}`,
    contentType: curMail.value.message ? 'html' : 'text',
    content: curMail.value.message || curMail.value.text,
  });
  indexTab.value = 'sendmail';
};

const saveToS3Proxy = async (filename, blob) => { await props.saveToS3(curMail.value.id, filename, blob); }

const multiActionModeClick = (enable) => {
  data.value.forEach((item) => { item.checked = false; });
  multiActionMode.value = enable;
}

const multiActionSelectAll = (checked) => { data.value.forEach((item) => { item.checked = checked; }); }

const multiActionDeleteMail = async () => {
  try {
    loading.value = true;
    const selectedMails = data.value.filter((item) => item.checked);
    if (selectedMails.length === 0) { message.error(t('pleaseSelectMail')); return; }
    multiActionDeleteProgress.value = { percentage: 0, tip: `0/${selectedMails.length}` };
    for (const [index, mail] of selectedMails.entries()) {
      await props.deleteMail(mail.id);
      showMultiActionDelete.value = true;
      multiActionDeleteProgress.value = {
        percentage: Math.floor((index + 1) / selectedMails.length * 100),
        tip: `${index + 1}/${selectedMails.length}`
      };
    }
    message.success(t("success"));
    await refresh();
  } catch (error) {
    message.error(error.message || "error");
  } finally {
    loading.value = false;
  }
}

const multiActionDownload = async () => {
  try {
    loading.value = true;
    const selectedMails = data.value.filter((item) => item.checked);
    if (selectedMails.length === 0) { message.error(t('pleaseSelectMail')); return; }
    const JSZipModule = await import('jszip');
    const JSZip = JSZipModule.default;
    const zip = new JSZip();
    for (const mail of selectedMails) { zip.file(`${mail.id}.eml`, mail.raw); }
    multiActionDownloadZip.value = {
      url: URL.createObjectURL(await zip.generateAsync({ type: "blob" })),
      filename: `mails-${new Date().toISOString().replace(/:/g, '-')}.zip`
    }
    showMultiActionDownload.value = true;
  } catch (error) {
    message.error(error.message || "error");
  } finally {
    loading.value = false;
  }
}

onMounted(async () => { await refresh(); });
onBeforeUnmount(() => { clearInterval(timer.value) })
</script>

<template>
  <div>
    <!-- Desktop View -->
    <div v-if="!isMobile">
      <div class="mb-4">
        <v-row v-if="multiActionMode" align="center" dense>
          <v-col cols="auto"><v-btn @click="multiActionModeClick(false)" variant="text">{{ t('cancelMultiAction') }}</v-btn></v-col>
          <v-col cols="auto"><v-btn @click="multiActionSelectAll(true)" variant="text">{{ t('selectAll') }}</v-btn></v-col>
          <v-col cols="auto"><v-btn @click="multiActionSelectAll(false)" variant="text">{{ t('unselectAll') }}</v-btn></v-col>
          <v-col cols="auto" v-if="enableUserDeleteEmail">
            <v-btn color="error" variant="text" @click="deleteConfirmDialog = true">{{ t('delete') }}</v-btn>
          </v-col>
          <v-col cols="auto">
            <v-btn color="info" variant="text" @click="multiActionDownload">
              <v-icon start>mdi-download</v-icon>{{ t('downloadMail') }}
            </v-btn>
          </v-col>
        </v-row>
        <v-row v-else align="center" dense>
          <v-col cols="auto"><v-btn @click="multiActionModeClick(true)" color="primary" variant="text">{{ t('multiAction') }}</v-btn></v-col>
          <v-col cols="auto">
            <v-pagination v-model="page" :length="Math.ceil(count / pageSize)" density="compact" size="small"></v-pagination>
          </v-col>
          <v-col cols="auto">
            <v-switch v-model="autoRefresh" density="compact" hide-details color="primary"
              :label="autoRefresh ? t('refreshAfter', { msg: autoRefreshInterval }) : t('autoRefresh')"></v-switch>
          </v-col>
          <v-col cols="auto"><v-btn @click="backFirstPageAndRefresh" color="primary" variant="text">{{ t('refresh') }}</v-btn></v-col>
          <v-col v-if="showFilterInput" cols="3">
            <v-text-field v-model="localFilterKeyword" :placeholder="t('keywordQueryTip')" 
              variant="outlined" density="compact" hide-details clearable></v-text-field>
          </v-col>
        </v-row>
      </div>

      <div class="d-flex" style="gap: 16px;">
        <div style="width: 280px; min-width: 280px; max-height: 70vh; overflow-y: auto;">
          <v-list lines="three" density="compact">
            <v-list-item v-for="row in data" :key="row.id" @click="clickRow(row)" :class="mailItemClass(row)">
              <template v-slot:prepend v-if="multiActionMode">
                <v-checkbox-btn v-model="row.checked"></v-checkbox-btn>
              </template>
              <v-list-item-title class="text-body-2 font-weight-medium">{{ row.subject }}</v-list-item-title>
              <v-list-item-subtitle class="text-caption">
                <div>ID: {{ row.id }} | {{ utcToLocalDate(row.created_at, useUTCDate) }}</div>
                <div class="text-truncate">{{ row.source }}</div>
                <AiExtractInfo :metadata="row.metadata" compact />
              </v-list-item-subtitle>
            </v-list-item>
          </v-list>
        </div>
        <div style="flex: 1; min-width: 0;">
          <div v-if="curMail" class="d-flex justify-space-between align-center mb-2">
            <v-btn @click="prevMail" :disabled="!canGoPrevMail" variant="text" size="small">
              <v-icon start>mdi-chevron-left</v-icon>{{ t('prevMail') }}
            </v-btn>
            <v-btn @click="nextMail" :disabled="!canGoNextMail" variant="text" size="small">
              {{ t('nextMail') }}<v-icon end>mdi-chevron-right</v-icon>
            </v-btn>
          </div>
          <div v-if="curMail" class="mail-preview-container">
            <div class="mail-header mb-3">
              <h3 class="text-h6 mb-2">{{ curMail.subject }}</h3>
              <MailContentRenderer :mail="curMail" :showEMailTo="showEMailTo"
                :enableUserDeleteEmail="enableUserDeleteEmail" :showReply="showReply" :showSaveS3="showSaveS3"
                :onDelete="deleteMail" :onReply="replyMail" :onForward="forwardMail" :onSaveToS3="saveToS3Proxy" />
            </div>
          </div>
          <v-card v-else flat class="d-flex align-center justify-center" style="min-height: 200px;">
            <v-card-text class="text-center">{{ t('pleaseSelectMail') }}</v-card-text>
          </v-card>
        </div>
      </div>
    </div>

    <!-- Mobile View -->
    <div v-else>
      <v-row align="center" dense class="mb-2">
        <v-col cols="auto">
          <v-pagination v-model="page" :length="Math.ceil(count / pageSize)" density="compact" size="small"></v-pagination>
        </v-col>
        <v-col cols="auto">
          <v-switch v-model="autoRefresh" density="compact" hide-details size="small"
            :label="autoRefresh ? `${autoRefreshInterval}s` : t('autoRefresh')"></v-switch>
        </v-col>
        <v-col cols="auto"><v-btn @click="backFirstPageAndRefresh" size="small" variant="text">{{ t('refresh') }}</v-btn></v-col>
      </v-row>
      <v-text-field v-if="showFilterInput" v-model="localFilterKeyword" :placeholder="t('keywordQueryTip')"
        variant="outlined" density="compact" hide-details clearable class="mb-2"></v-text-field>

      <v-list lines="three" style="max-height: 70vh; overflow-y: auto;">
        <v-list-item v-for="row in data" :key="row.id" @click="clickRow(row)">
          <v-list-item-title>{{ row.subject }}</v-list-item-title>
          <v-list-item-subtitle>
            <v-chip size="x-small" class="mr-1">{{ utcToLocalDate(row.created_at, useUTCDate) }}</v-chip>
            <v-chip size="x-small">{{ row.source }}</v-chip>
          </v-list-item-subtitle>
        </v-list-item>
      </v-list>
    </div>

    <!-- Mobile Mail Drawer - 只在移动端显示 -->
    <v-bottom-sheet v-if="isMobile" v-model="showMailDrawer" inset content-class="mobile-mail-sheet">
      <v-card v-if="curMail" variant="flat" :border="false" class="bg-surface">
        <v-card-title class="d-flex justify-space-between align-center">
          <span class="text-truncate" style="max-width: 80%;">{{ curMail.subject }}</span>
          <v-btn icon variant="text" size="small" @click="showMailDrawer = false; curMail = null"><v-icon>mdi-close</v-icon></v-btn>
        </v-card-title>
        <v-card-text style="max-height: 70vh; overflow-y: auto;">
          <MailContentRenderer :mail="curMail" :showEMailTo="showEMailTo"
            :enableUserDeleteEmail="enableUserDeleteEmail" :showReply="showReply" :showSaveS3="showSaveS3"
            :onDelete="deleteMail" :onReply="replyMail" :onForward="forwardMail" :onSaveToS3="saveToS3Proxy" />
        </v-card-text>
      </v-card>
    </v-bottom-sheet>

    <!-- Dialogs -->
    <v-dialog v-model="showMultiActionDownload" max-width="400">
      <v-card>
        <v-card-title>{{ t('downloadMail') }}</v-card-title>
        <v-card-text>
          <v-chip class="mb-2">{{ multiActionDownloadZip.filename }}</v-chip>
          <v-btn :href="multiActionDownloadZip.url" :download="multiActionDownloadZip.filename" color="info" block>
            <v-icon start>mdi-download</v-icon>{{ t('downloadMail') }} zip
          </v-btn>
        </v-card-text>
      </v-card>
    </v-dialog>

    <v-dialog v-model="showMultiActionDelete" max-width="300">
      <v-card>
        <v-card-title>{{ t('delete') }}</v-card-title>
        <v-card-text class="text-center">
          <v-progress-circular :model-value="multiActionDeleteProgress.percentage" color="error" size="80">
            {{ multiActionDeleteProgress.tip }}
          </v-progress-circular>
        </v-card-text>
      </v-card>
    </v-dialog>

    <v-dialog v-model="deleteConfirmDialog" max-width="300">
      <v-card>
        <v-card-title>{{ t('delete') }}</v-card-title>
        <v-card-text>{{ t('deleteMailTip') }}</v-card-text>
        <v-card-actions>
          <v-spacer></v-spacer>
          <v-btn @click="deleteConfirmDialog = false">Cancel</v-btn>
          <v-btn color="error" @click="deleteConfirmDialog = false; multiActionDeleteMail()">{{ t('delete') }}</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <v-snackbar v-model="snackbar" :color="snackbarColor" timeout="3000">{{ snackbarText }}</v-snackbar>
  </div>
</template>

<style scoped>
.selected-mail { background-color: rgba(var(--v-theme-primary), 0.1); }
.mail-preview-container { max-height: 70vh; overflow-y: auto; }
.mail-header { border-bottom: 1px solid rgba(var(--v-border-color), 0.12); padding-bottom: 12px; }
</style>

<style>
/* 移动端邮件底部弹出层 - 修复圆角露出底色问题 */
.mobile-mail-sheet {
  background: transparent !important;
}
.mobile-mail-sheet > .v-bottom-sheet {
  background: transparent !important;
}
.mobile-mail-sheet .v-card {
  background-color: rgb(var(--v-theme-surface)) !important;
}
</style>

// frontend-angular/src/app/components/mailbox/mailbox.component.ts
import { Component, Input, inject, OnInit, OnDestroy, signal, computed, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatListModule } from '@angular/material/list';
import { MatPaginatorModule, PageEvent } from '@angular/material/paginator';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import { MatDialogModule } from '@angular/material/dialog';
import { MatChipsModule } from '@angular/material/chips';
import { MatBottomSheetModule, MatBottomSheet, MatBottomSheetRef, MAT_BOTTOM_SHEET_DATA } from '@angular/material/bottom-sheet';
import { MatDividerModule } from '@angular/material/divider';

import { GlobalStateService } from '../../services/global-state.service';
import { ApiService } from '../../services/api.service';
import { SnackbarService } from '../../services/snackbar.service';
import { processItem, ParsedMail } from '../../utils/email-parser';
import { utcToLocalDate } from '../../utils/index';
import { MailContentRendererComponent } from '../mail-content-renderer/mail-content-renderer.component';

@Component({
  selector: 'app-mailbox',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatCardModule,
    MatButtonModule,
    MatIconModule,
    MatListModule,
    MatPaginatorModule,
    MatProgressSpinnerModule,
    MatCheckboxModule,
    MatFormFieldModule,
    MatInputModule,
    MatSlideToggleModule,
    MatDialogModule,
    MatChipsModule,
    MatBottomSheetModule,
    MatDividerModule,
    MailContentRendererComponent,
  ],
  template: `
    <div class="mailbox-container">
      <!-- Desktop View -->
      @if (!isMobile()) {
        <!-- Toolbar -->
        <div class="toolbar">
          <button mat-button (click)="refresh()">
            <mat-icon>refresh</mat-icon>
            刷新
          </button>
          <mat-slide-toggle [(ngModel)]="autoRefresh" (change)="setupAutoRefresh()">
            {{ autoRefresh ? '自动刷新 ' + autoRefreshCountdown + 's' : '自动刷新' }}
          </mat-slide-toggle>
          @if (showFilterInput) {
            <mat-form-field appearance="outline" class="filter-field" subscriptSizing="dynamic">
              <mat-label>过滤</mat-label>
              <input matInput [(ngModel)]="filterKeyword" placeholder="搜索邮件...">
            </mat-form-field>
          }
        </div>

        <!-- Mail List and Content -->
        <div class="mail-layout">
          <!-- Mail List -->
          <div class="mail-list">
            @if (state.loading()) {
              <div class="loading-container">
                <mat-spinner diameter="40"></mat-spinner>
              </div>
            } @else if (filteredData().length === 0) {
              <div class="empty-state">
                <mat-icon>inbox</mat-icon>
                <p>暂无邮件</p>
              </div>
            } @else {
              <mat-nav-list>
                @for (mail of filteredData(); track mail.id) {
                  <mat-list-item 
                    [class.selected]="curMail()?.id === mail.id"
                    (click)="selectMail(mail)">
                    <div matListItemTitle class="mail-subject">{{ mail.subject }}</div>
                    <div matListItemLine class="mail-meta">
                      <span class="mail-id">ID: {{ mail.id }}</span>
                      <span class="mail-date">{{ formatDate(mail.created_at) }}</span>
                    </div>
                    <div matListItemLine class="mail-from">{{ mail.source }}</div>
                  </mat-list-item>
                }
              </mat-nav-list>
            }
            
            <!-- Pagination -->
            <mat-paginator
              [length]="totalCount()"
              [pageSize]="pageSize"
              [pageIndex]="page() - 1"
              [pageSizeOptions]="[10, 20, 50]"
              (page)="onPageChange($event)"
              showFirstLastButtons>
            </mat-paginator>
          </div>

          <!-- Mail Content -->
          <div class="mail-content">
            @if (curMail()) {
              <div class="mail-header">
                <h2>{{ curMail()!.subject }}</h2>
                <div class="mail-actions">
                  <button mat-button (click)="prevMail()" [disabled]="!canGoPrev()">
                    <mat-icon>chevron_left</mat-icon>
                    上一封
                  </button>
                  <button mat-button (click)="nextMail()" [disabled]="!canGoNext()">
                    下一封
                    <mat-icon>chevron_right</mat-icon>
                  </button>
                </div>
              </div>
              <app-mail-content-renderer
                [mail]="curMail()!"
                [enableUserDeleteEmail]="enableUserDeleteEmail"
                [showReply]="showReply"
                [showEMailTo]="false"
                (onDelete)="deleteMailAction()"
                (onReply)="replyMail()"
                (onForward)="forwardMail()">
              </app-mail-content-renderer>
            } @else {
              <div class="empty-content">
                <mat-icon>email</mat-icon>
                <p>请选择邮件</p>
              </div>
            }
          </div>
        </div>
      } @else {
        <!-- Mobile View -->
        <div class="mobile-toolbar">
          <mat-slide-toggle [(ngModel)]="autoRefresh" (change)="setupAutoRefresh()">
            {{ autoRefresh ? autoRefreshCountdown + 's' : '自动刷新' }}
          </mat-slide-toggle>
          <button mat-button (click)="refresh()">刷新</button>
        </div>
        
        @if (showFilterInput) {
          <mat-form-field appearance="outline" class="mobile-filter-field" subscriptSizing="dynamic">
            <mat-label>过滤</mat-label>
            <input matInput [(ngModel)]="filterKeyword">
          </mat-form-field>
        }

        <mat-nav-list class="mobile-mail-list">
          @for (mail of filteredData(); track mail.id) {
            <mat-list-item (click)="selectMailMobile(mail)">
              <div matListItemTitle class="mail-subject">{{ mail.subject }}</div>
              <div matListItemLine class="mobile-mail-meta">
                ID: {{ mail.id }} · {{ formatDate(mail.created_at) }}
              </div>
              <div matListItemLine class="mobile-mail-from">{{ mail.source }}</div>
            </mat-list-item>
            <mat-divider></mat-divider>
          }
        </mat-nav-list>

        <mat-paginator
          [length]="totalCount()"
          [pageSize]="pageSize"
          [pageIndex]="page() - 1"
          [pageSizeOptions]="[10, 20, 50]"
          (page)="onPageChange($event)"
          showFirstLastButtons>
        </mat-paginator>
      }
    </div>
  `,
  styles: [`
    .mailbox-container {
      height: 100%;
    }
    .toolbar {
      display: flex;
      align-items: center;
      gap: 16px;
      margin-bottom: 16px;
      flex-wrap: wrap;
    }
    .filter-field {
      flex: 1;
      min-width: 200px;
    }
    ::ng-deep .filter-field .mat-mdc-form-field-subscript-wrapper,
    ::ng-deep .mobile-filter-field .mat-mdc-form-field-subscript-wrapper {
      display: none !important;
      height: 0 !important;
    }
    ::ng-deep .mobile-filter-field .mdc-notched-outline__trailing,
    ::ng-deep .mobile-filter-field .mdc-notched-outline__leading,
    ::ng-deep .mobile-filter-field .mdc-notched-outline__notch {
      border-width: 1px !important;
    }
    .mail-layout {
      display: flex;
      gap: 16px;
      height: calc(100% - 80px);
    }
    .mail-list {
      width: 320px;
      min-width: 320px;
      border-right: 1px solid var(--mat-sys-outline-variant, #ccc);
      display: flex;
      flex-direction: column;
    }
    mat-nav-list {
      flex: 1;
      overflow-y: auto;
      max-height: 60vh;
    }
    .mail-content {
      flex: 1;
      overflow-y: auto;
      max-height: 70vh;
    }
    .mail-subject {
      font-weight: 500;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    .mail-meta {
      font-size: 12px;
      color: var(--mat-sys-on-surface-variant, #666);
    }
    .mail-from {
      font-size: 12px;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    .mail-id {
      margin-right: 8px;
    }
    .selected {
      background-color: var(--mat-sys-primary-container, #e3f2fd) !important;
    }
    .loading-container, .empty-state, .empty-content {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 48px;
      color: var(--mat-sys-on-surface-variant, #666);
    }
    .empty-state mat-icon, .empty-content mat-icon {
      font-size: 48px;
      width: 48px;
      height: 48px;
      margin-bottom: 16px;
    }
    .mail-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 16px;
      padding-bottom: 16px;
      border-bottom: 1px solid var(--mat-sys-outline-variant, #ccc);
    }
    .mail-header h2 {
      margin: 0;
      font-size: 18px;
    }
    .mail-actions {
      display: flex;
      gap: 8px;
    }

    /* Mobile styles */
    .mobile-toolbar {
      display: flex;
      align-items: center;
      gap: 16px;
      margin-bottom: 8px;
    }
    .mobile-filter-field {
      width: 100%;
      margin-bottom: 16px;
    }
    .mobile-mail-list {
      max-height: 60vh;
      overflow-y: auto;
    }
    .mobile-mail-meta {
      font-size: 12px;
      color: var(--mat-sys-on-surface-variant, #666);
    }
    .mobile-mail-from {
      font-size: 12px;
      color: var(--mat-sys-on-surface-variant, #888);
    }
  `]
})
export class MailboxComponent implements OnInit, OnDestroy {
  @Input() enableUserDeleteEmail = false;
  @Input() showReply = false;
  @Input() showFilterInput = false;
  @Input() key = '';
  @Input() fetchMailData?: (limit: number, offset: number) => Promise<{ results: any[]; count: number }>;
  @Input() deleteMail?: (id: number) => Promise<void>;
  @Input() deleteMailFn?: (id: number) => Promise<void>;

  state = inject(GlobalStateService);
  private api = inject(ApiService);
  private snackbar = inject(SnackbarService);
  private bottomSheet = inject(MatBottomSheet);

  rawData = signal<ParsedMail[]>([]);
  curMail = signal<ParsedMail | null>(null);
  page = signal(1);
  pageSize = 20;
  totalCount = signal(0);
  filterKeyword = '';
  autoRefresh = false;
  autoRefreshCountdown = 60;
  isMobile = signal(window.innerWidth < 768);
  private refreshTimer: any = null;

  @HostListener('window:resize')
  onResize() {
    this.isMobile.set(window.innerWidth < 768);
  }

  filteredData = computed(() => {
    const data = this.rawData();
    if (!this.filterKeyword.trim()) return data;
    const keyword = this.filterKeyword.toLowerCase();
    return data.filter(mail => 
      (mail.subject || '').toLowerCase().includes(keyword) ||
      (mail.text || '').toLowerCase().includes(keyword) ||
      (mail.source || '').toLowerCase().includes(keyword)
    );
  });

  canGoPrev = computed(() => {
    if (!this.curMail()) return false;
    const idx = this.filteredData().findIndex(m => m.id === this.curMail()!.id);
    return idx > 0 || this.page() > 1;
  });

  canGoNext = computed(() => {
    if (!this.curMail()) return false;
    const idx = this.filteredData().findIndex(m => m.id === this.curMail()!.id);
    return idx < this.filteredData().length - 1 || this.totalCount() > this.page() * this.pageSize;
  });

  async ngOnInit() {
    await this.refresh();
  }

  ngOnDestroy() {
    this.clearTimer();
  }

  async refresh() {
    try {
      const offset = (this.page() - 1) * this.pageSize;
      let res: { results: any[]; count: number };
      
      if (this.fetchMailData) {
        res = await this.fetchMailData(this.pageSize, offset);
      } else {
        res = await this.api.fetch<{ results: any[]; count: number }>(
          `/api/mails?limit=${this.pageSize}&offset=${offset}`
        );
      }
      
      const processed = await Promise.all(
        res.results.map(item => processItem(item))
      );
      this.rawData.set(processed);
      this.totalCount.set(res.count);
      
      if (processed.length > 0 && !this.curMail() && !this.isMobile()) {
        this.curMail.set(processed[0]);
      }
    } catch (error: any) {
      this.snackbar.error(error.message || '加载失败');
    }
  }

  selectMail(mail: ParsedMail) {
    this.curMail.set(mail);
  }

  selectMailMobile(mail: ParsedMail) {
    this.curMail.set(mail);
    this.bottomSheet.open(MobileMailSheetComponent, {
      data: {
        mail,
        enableUserDeleteEmail: this.enableUserDeleteEmail,
        showReply: this.showReply,
        onDelete: () => this.deleteMailAction(),
        onReply: () => this.replyMail(),
        onForward: () => this.forwardMail(),
      },
      panelClass: 'mobile-mail-sheet'
    });
  }

  formatDate(date: string): string {
    return utcToLocalDate(date, false);
  }

  onPageChange(event: PageEvent) {
    this.page.set(event.pageIndex + 1);
    this.pageSize = event.pageSize;
    this.refresh();
  }

  async prevMail() {
    const data = this.filteredData();
    const idx = data.findIndex(m => m.id === this.curMail()!.id);
    if (idx > 0) {
      this.curMail.set(data[idx - 1]);
    } else if (this.page() > 1) {
      this.page.update(p => p - 1);
      await this.refresh();
      const newData = this.filteredData();
      if (newData.length > 0) {
        this.curMail.set(newData[newData.length - 1]);
      }
    }
  }

  async nextMail() {
    const data = this.filteredData();
    const idx = data.findIndex(m => m.id === this.curMail()!.id);
    if (idx < data.length - 1) {
      this.curMail.set(data[idx + 1]);
    } else if (this.totalCount() > this.page() * this.pageSize) {
      this.page.update(p => p + 1);
      await this.refresh();
      const newData = this.filteredData();
      if (newData.length > 0) {
        this.curMail.set(newData[0]);
      }
    }
  }

  async deleteMailAction() {
    if (!this.curMail()) return;
    try {
      const deleteFunc = this.deleteMail || this.deleteMailFn;
      if (deleteFunc) {
        await deleteFunc(this.curMail()!.id);
      } else {
        await this.api.fetch(`/api/mails/${this.curMail()!.id}`, { method: 'DELETE' });
      }
      this.snackbar.success('删除成功');
      this.curMail.set(null);
      await this.refresh();
    } catch (error: any) {
      this.snackbar.error(error.message || '删除失败');
    }
  }

  replyMail() {
    this.snackbar.info('回复功能待实现');
  }

  forwardMail() {
    this.snackbar.info('转发功能待实现');
  }

  setupAutoRefresh() {
    this.clearTimer();
    if (this.autoRefresh) {
      this.autoRefreshCountdown = 60;
      this.refreshTimer = setInterval(() => {
        this.autoRefreshCountdown--;
        if (this.autoRefreshCountdown <= 0) {
          this.autoRefreshCountdown = 60;
          this.page.set(1);
          this.refresh();
        }
      }, 1000);
    }
  }

  private clearTimer() {
    if (this.refreshTimer) {
      clearInterval(this.refreshTimer);
      this.refreshTimer = null;
    }
  }
}

// Mobile Mail Bottom Sheet Component
@Component({
  selector: 'app-mobile-mail-sheet',
  standalone: true,
  imports: [CommonModule, MatButtonModule, MatIconModule, MailContentRendererComponent],
  template: `
    <div class="sheet-header">
      <span class="sheet-title">{{ data.mail.subject }}</span>
      <button mat-icon-button (click)="close()">
        <mat-icon>close</mat-icon>
      </button>
    </div>
    <div class="sheet-content">
      <app-mail-content-renderer
        [mail]="data.mail"
        [enableUserDeleteEmail]="data.enableUserDeleteEmail"
        [showReply]="data.showReply"
        [showEMailTo]="false"
        (onDelete)="onDelete()"
        (onReply)="data.onReply()"
        (onForward)="data.onForward()">
      </app-mail-content-renderer>
    </div>
  `,
  styles: [`
    .sheet-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 16px;
      border-bottom: 1px solid #ccc;
    }
    .sheet-title {
      font-size: 16px;
      font-weight: 500;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
      max-width: calc(100% - 48px);
    }
    .sheet-content {
      padding: 16px;
      max-height: 70vh;
      overflow-y: auto;
    }
  `]
})
export class MobileMailSheetComponent {
  data = inject(MAT_BOTTOM_SHEET_DATA);
  private bottomSheetRef = inject(MatBottomSheetRef);

  close() {
    this.bottomSheetRef.dismiss();
  }

  onDelete() {
    this.data.onDelete();
    this.bottomSheetRef.dismiss();
  }
}
