// frontend/src/views/index/SendMail.vue
<script setup>
import '@wangeditor/editor/dist/css/style.css'
import { Editor, Toolbar } from '@wangeditor/editor-for-vue'
import { useI18n } from 'vue-i18n'
import { onMounted, onBeforeUnmount, ref, shallowRef } from 'vue'
import AdminContact from '../common/AdminContact.vue'

import { useGlobalState } from '../../store'
import { api } from '../../api'

const snackbar = ref({ show: false, text: '', color: 'success' })
const showMessage = (text, color = 'success') => {
    snackbar.value = { show: true, text, color }
}

const isPreview = ref(false)
const editorRef = shallowRef()

const { settings, sendMailModel, indexTab, userSettings } = useGlobalState()

const { t } = useI18n({
    locale: 'zh',
    messages: {
        en: {
            successSend: 'Please check your sendbox. If failed, please check your balance or try again later.',
            fromName: 'Your Name and Address, leave Name blank to use email address',
            toName: 'Recipient Name and Address, leave Name blank to use email address',
            subject: 'Subject',
            options: 'Options',
            edit: 'Edit',
            preview: 'Preview',
            content: 'Content',
            send: 'Send',
            requestAccess: 'Request Access',
            requestAccessTip: 'You need to request access to send mail, if have request, please contact admin.',
            send_balance: 'Send Mail Balance Left',
            text: 'Text',
            html: 'HTML',
            'rich text': 'Rich Text',
            tooLarge: 'Too large file, please upload file less than 1MB.',
            success: 'Success',
        },
        zh: {
            successSend: '请查看您的发件箱, 如果失败, 请检查您的余额或稍后重试。',
            fromName: '你的名称和地址，名称不填写则使用邮箱地址',
            toName: '收件人名称和地址，名称不填写则使用邮箱地址',
            subject: '主题',
            options: '选项',
            edit: '编辑',
            preview: '预览',
            content: '内容',
            send: '发送',
            requestAccess: '申请权限',
            requestAccessTip: '您需要申请权限才能发送邮件, 如果已经申请过, 请联系管理员提升额度。',
            send_balance: '剩余发送邮件额度',
            text: '文本',
            html: 'HTML',
            'rich text': '富文本',
            tooLarge: '文件过大, 请上传小于1MB的文件。',
            success: '成功',
        }
    }
});

const contentTypes = [
    { title: t('text'), value: 'text' },
    { title: t('html'), value: 'html' },
    { title: t('rich text'), value: 'rich' },
]

const send = async () => {
    try {
        await api.fetch(`/api/send_mail`, {
            method: 'POST',
            body: JSON.stringify({
                from_name: sendMailModel.value.fromName,
                to_name: sendMailModel.value.toName,
                to_mail: sendMailModel.value.toMail,
                subject: sendMailModel.value.subject,
                is_html: sendMailModel.value.contentType != 'text',
                content: sendMailModel.value.content,
            })
        })
        sendMailModel.value = {
            fromName: "",
            toName: "",
            toMail: "",
            subject: "",
            contentType: 'text',
            content: "",
        }
    } catch (error) {
        showMessage(error.message || "error", 'error');
    } finally {
        showMessage(t("successSend"));
        indexTab.value = 'sendbox'
    }
}

const requestAccess = async () => {
    try {
        await api.fetch(`/api/requset_send_mail_access`, {
            method: 'POST',
            body: JSON.stringify({})
        })
        showMessage(t("success"))
        await api.getSettings();
    } catch (error) {
        showMessage(error.message || "error", 'error');
    }
}

const toolbarConfig = {
    excludeKeys: ["uploadVideo"]
}

const editorConfig = {
    MENU_CONF: {
        'uploadImage': {
            async customUpload() {
                showMessage(t('tooLarge'), 'error')
            },
            maxFileSize: 1 * 1024 * 1024,
            base64LimitSize: 1 * 1024 * 1024,
        }
    }
}

onBeforeUnmount(() => {
    const editor = editorRef.value
    if (editor == null) return
    editor.destroy()
})

const handleCreated = (editor) => {
    editorRef.value = editor;
}

onMounted(async () => {
    if (!userSettings.value.user_id) await api.getUserSettings(snackbar);
    await api.getSettings();
})
</script>

<template>
    <div class="d-flex justify-center" v-if="settings.address">
        <v-card variant="flat" max-width="800" width="100%" class="pa-4">
            <v-card-text>
                <div v-if="!settings.send_balance || settings.send_balance <= 0">
                    <v-alert type="warning" variant="tonal" class="mb-3">
                        {{ t('requestAccessTip') }}
                        <v-btn color="primary" variant="tonal" size="small" @click="requestAccess" class="ml-2">
                            {{ t('requestAccess') }}
                        </v-btn>
                    </v-alert>
                    <AdminContact />
                </div>
                <div v-else>
                    <v-alert type="info" variant="tonal" closable class="mb-3">
                        {{ t('send_balance') }}: {{ settings.send_balance }}
                    </v-alert>
                    <div class="d-flex justify-end mb-4">
                        <v-btn color="primary" @click="send">{{ t('send') }}</v-btn>
                    </div>
                    <v-text-field :label="t('fromName')" variant="outlined" density="compact" class="mb-3">
                        <template #prepend-inner>
                            <v-text-field v-model="sendMailModel.fromName" variant="plain" density="compact"
                                hide-details single-line style="max-width: 150px;" />
                        </template>
                        <template #default>
                            <span class="text-medium-emphasis">{{ settings.address }}</span>
                        </template>
                    </v-text-field>
                    <div class="d-flex ga-2 mb-3">
                        <v-text-field v-model="sendMailModel.toName" :label="t('toName')" variant="outlined"
                            density="compact" hide-details />
                        <v-text-field v-model="sendMailModel.toMail" label="Email" variant="outlined" density="compact"
                            hide-details />
                    </div>
                    <v-text-field v-model="sendMailModel.subject" :label="t('subject')" variant="outlined"
                        density="compact" class="mb-3" />
                    <div class="d-flex align-center ga-2 mb-3">
                        <span class="text-subtitle-2">{{ t('options') }}:</span>
                        <v-btn-toggle v-model="sendMailModel.contentType" mandatory color="primary" variant="outlined"
                            density="compact">
                            <v-btn v-for="option in contentTypes" :key="option.value" :value="option.value" size="small">
                                {{ option.title }}
                            </v-btn>
                        </v-btn-toggle>
                        <v-btn v-if="sendMailModel.contentType != 'text'" @click="isPreview = !isPreview"
                            variant="outlined" size="small">
                            {{ isPreview ? t('edit') : t('preview') }}
                        </v-btn>
                    </div>
                    <div class="mb-3">
                        <div class="text-subtitle-2 mb-2">{{ t('content') }}</div>
                        <v-card v-if="isPreview" variant="tonal">
                            <v-card-text v-html="sendMailModel.content" />
                        </v-card>
                        <div v-else-if="sendMailModel.contentType == 'rich'" style="border: 1px solid #ccc">
                            <Toolbar style="border-bottom: 1px solid #ccc" :defaultConfig="toolbarConfig"
                                :editor="editorRef" mode="default" />
                            <Editor style="height: 500px; overflow-y: hidden;" v-model="sendMailModel.content"
                                :defaultConfig="editorConfig" mode="default" @onCreated="handleCreated" />
                        </div>
                        <v-textarea v-else v-model="sendMailModel.content" variant="outlined" rows="5" />
                    </div>
                </div>
            </v-card-text>
        </v-card>

        <v-snackbar v-model="snackbar.show" :color="snackbar.color" :timeout="2000">
            {{ snackbar.text }}
        </v-snackbar>
    </div>
</template>

// frontend-angular/src/app/views/index/send-mail/send-mail.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonToggleModule } from '@angular/material/button-toggle';
import { MatIconModule } from '@angular/material/icon';
import { GlobalStateService } from '../../../services/global-state.service';
import { ApiService } from '../../../services/api.service';
import { SnackbarService } from '../../../services/snackbar.service';
import { AdminContactComponent } from '../../common/admin-contact/admin-contact.component';

@Component({
  selector: 'app-send-mail',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatCardModule,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonToggleModule,
    MatIconModule,
    AdminContactComponent,
  ],
  template: `
    @if (state.settings().address) {
      <div class="send-mail-container">
        <mat-card appearance="outlined">
          <mat-card-content>
            @if (!state.settings().send_balance || state.settings().send_balance <= 0) {
              <!-- 无发送额度 -->
              <div class="warning-alert">
                <mat-icon>warning</mat-icon>
                <span>您需要申请权限才能发送邮件, 如果已经申请过, 请联系管理员提升额度。</span>
                <button mat-stroked-button color="primary" (click)="requestAccess()">
                  申请权限
                </button>
              </div>
              <app-admin-contact></app-admin-contact>
            } @else {
              <!-- 有发送额度 -->
              <div class="info-alert">
                <mat-icon>info</mat-icon>
                <span>剩余发送邮件额度: {{ state.settings().send_balance }}</span>
              </div>

              <div class="actions-row">
                <button mat-raised-button color="primary" (click)="send()">发送</button>
              </div>

              <!-- 发件人 -->
              <mat-form-field appearance="outline" class="full-width">
                <mat-label>你的名称和地址，名称不填写则使用邮箱地址</mat-label>
                <input matInput [(ngModel)]="sendMailModel.fromName" placeholder="名称">
                <span matSuffix class="address-suffix">{{ state.settings().address }}</span>
              </mat-form-field>

              <!-- 收件人 -->
              <div class="row-fields">
                <mat-form-field appearance="outline" class="flex-1">
                  <mat-label>收件人名称</mat-label>
                  <input matInput [(ngModel)]="sendMailModel.toName">
                </mat-form-field>
                <mat-form-field appearance="outline" class="flex-1">
                  <mat-label>Email</mat-label>
                  <input matInput [(ngModel)]="sendMailModel.toMail" type="email">
                </mat-form-field>
              </div>

              <!-- 主题 -->
              <mat-form-field appearance="outline" class="full-width">
                <mat-label>主题</mat-label>
                <input matInput [(ngModel)]="sendMailModel.subject">
              </mat-form-field>

              <!-- 选项 -->
              <div class="options-row">
                <span class="options-label">选项:</span>
                <mat-button-toggle-group [(ngModel)]="sendMailModel.contentType">
                  <mat-button-toggle value="text">文本</mat-button-toggle>
                  <mat-button-toggle value="html">HTML</mat-button-toggle>
                </mat-button-toggle-group>
                @if (sendMailModel.contentType !== 'text') {
                  <button mat-stroked-button (click)="isPreview.set(!isPreview())">
                    {{ isPreview() ? '编辑' : '预览' }}
                  </button>
                }
              </div>

              <!-- 内容 -->
              <div class="content-section">
                <label class="content-label">内容</label>
                @if (isPreview()) {
                  <mat-card appearance="outlined" class="preview-card">
                    <mat-card-content [innerHTML]="sendMailModel.content"></mat-card-content>
                  </mat-card>
                } @else {
                  <mat-form-field appearance="outline" class="full-width">
                    <textarea matInput [(ngModel)]="sendMailModel.content" rows="10"></textarea>
                  </mat-form-field>
                }
              </div>
            }
          </mat-card-content>
        </mat-card>
      </div>
    }
  `,
  styles: [`
    .send-mail-container {
      display: flex;
      justify-content: center;
      padding: 16px;
    }
    mat-card {
      max-width: 800px;
      width: 100%;
    }
    .warning-alert {
      display: flex;
      align-items: center;
      gap: 8px;
      padding: 12px 16px;
      background-color: #fff3e0;
      border-radius: 4px;
      color: #e65100;
      margin-bottom: 16px;
      flex-wrap: wrap;
    }
    .info-alert {
      display: flex;
      align-items: center;
      gap: 8px;
      padding: 12px 16px;
      background-color: #e3f2fd;
      border-radius: 4px;
      color: #1976d2;
      margin-bottom: 16px;
    }
    .actions-row {
      display: flex;
      justify-content: flex-end;
      margin-bottom: 16px;
    }
    .full-width {
      width: 100%;
      margin-bottom: 8px;
    }
    .row-fields {
      display: flex;
      gap: 16px;
      margin-bottom: 8px;
    }
    .flex-1 {
      flex: 1;
    }
    .options-row {
      display: flex;
      align-items: center;
      gap: 16px;
      margin-bottom: 16px;
      flex-wrap: wrap;
    }
    .options-label {
      font-weight: 500;
    }
    .content-section {
      margin-top: 8px;
    }
    .content-label {
      display: block;
      font-weight: 500;
      margin-bottom: 8px;
    }
    .preview-card {
      min-height: 200px;
    }
    .address-suffix {
      color: #666;
      font-size: 14px;
    }
    :host-context(.dark-theme) .warning-alert {
      background-color: #4a3000;
      color: #ffb74d;
    }
    :host-context(.dark-theme) .info-alert {
      background-color: #1e3a5f;
      color: #90caf9;
    }
  `]
})
export class SendMailComponent implements OnInit {
  state = inject(GlobalStateService);
  private api = inject(ApiService);
  private snackbar = inject(SnackbarService);

  isPreview = signal(false);

  sendMailModel = {
    fromName: '',
    toName: '',
    toMail: '',
    subject: '',
    contentType: 'text',
    content: '',
  };

  async ngOnInit() {
    await this.api.getSettings();
  }

  async send() {
    try {
      await this.api.fetch('/api/send_mail', {
        method: 'POST',
        body: {
          from_name: this.sendMailModel.fromName,
          to_name: this.sendMailModel.toName,
          to_mail: this.sendMailModel.toMail,
          subject: this.sendMailModel.subject,
          is_html: this.sendMailModel.contentType !== 'text',
          content: this.sendMailModel.content,
        },
      });
      // 重置表单
      this.sendMailModel = {
        fromName: '',
        toName: '',
        toMail: '',
        subject: '',
        contentType: 'text',
        content: '',
      };
      this.snackbar.success('请查看您的发件箱, 如果失败, 请检查您的余额或稍后重试。');
      // 切换到发件箱 tab
      this.state.indexTab.set('sendbox');
    } catch (error: any) {
      this.snackbar.error(error.message || 'error');
    }
  }

  async requestAccess() {
    try {
      await this.api.fetch('/api/requset_send_mail_access', {
        method: 'POST',
        body: {},
      });
      this.snackbar.success('成功');
      await this.api.getSettings();
    } catch (error: any) {
      this.snackbar.error(error.message || 'error');
    }
  }
}
