// frontend/src/views/index/TelegramAddress.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useI18n } from 'vue-i18n'

// @ts-ignore
import { useGlobalState } from '../../store'
// @ts-ignore
import { api } from '../../api'
// @ts-ignore
import Login from '../common/Login.vue';

const { jwt, telegramApp } = useGlobalState()

const snackbar = ref({ show: false, text: '', color: 'success' })
const showMessage = (text: string, color: string = 'success') => {
    snackbar.value = { show: true, text, color }
}

const showChangeConfirm = ref(false)
const showUnbindConfirm = ref(false)
const selectedRow = ref<any>(null)

const { t } = useI18n({
    messages: {
        en: {
            success: 'success',
            address: 'Address',
            actions: 'Actions',
            changeMailAddress: 'Change Mail Address',
            unbindMailAddress: 'Unbind Mail Address',
            bind: 'Bind',
            bindAddressSuccess: 'Bind Address Success',
            cancel: 'Cancel',
        },
        zh: {
            success: '成功',
            address: '地址',
            actions: '操作',
            changeMailAddress: '切换邮箱地址',
            unbindMailAddress: '解绑邮箱地址',
            bind: '绑定',
            bindAddressSuccess: '绑定地址成功',
            cancel: '取消',
        }
    }
});

const tabValue = ref('address')
const data = ref<any[]>([]);

const fetchData = async () => {
    try {
        data.value = await api.fetch(`/telegram/get_bind_address`, {
            method: 'POST',
            body: JSON.stringify({
                initData: telegramApp.value.initData
            })
        });
    } catch (error) {
        showMessage((error as Error).message || "error", 'error');
    }
}

const newAddressPath = async (address_name: string, domain: string, cf_token: string) => {
    return await api.fetch("/telegram/new_address", {
        method: "POST",
        body: JSON.stringify({
            initData: telegramApp.value.initData,
            address: `${address_name}@${domain}`,
            cf_token: cf_token,
        }),
    });
}

const bindAddress = async () => {
    try {
        await api.fetch(`/telegram/bind_address`, {
            method: 'POST',
            body: JSON.stringify({
                initData: telegramApp.value.initData,
                jwt: jwt.value
            })
        });
        showMessage(t('bindAddressSuccess'));
    } catch (error) {
        showMessage((error as Error).message || "error", 'error');
    }
}

const confirmChange = (row: any) => {
    selectedRow.value = row
    showChangeConfirm.value = true
}

const confirmUnbind = (row: any) => {
    selectedRow.value = row
    showUnbindConfirm.value = true
}

const changeAddress = () => {
    jwt.value = selectedRow.value.jwt
    location.reload()
}

const unbindAddress = async () => {
    await api.fetch(`/telegram/unbind_address`, {
        method: 'POST',
        body: JSON.stringify({
            initData: telegramApp.value.initData,
            address: selectedRow.value.address
        })
    });
    jwt.value = ""
    location.reload()
}

onMounted(async () => {
    if (!telegramApp.value?.initData || data.value.length > 0) {
        return
    }
    await fetchData()
})
</script>

<template>
    <div>
        <v-tabs v-model="tabValue" color="primary">
            <v-tab value="address">{{ t('address') }}</v-tab>
            <v-tab value="bind">{{ t('bind') }}</v-tab>
        </v-tabs>

        <v-window v-model="tabValue">
            <v-window-item value="address">
                <v-table class="mt-4">
                    <thead>
                        <tr>
                            <th>{{ t('address') }}</th>
                            <th>{{ t('actions') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="row in data" :key="row.address">
                            <td>{{ row.address }}</td>
                            <td>
                                <v-btn size="small" color="primary" variant="text" @click="confirmChange(row)">
                                    {{ t('changeMailAddress') }}
                                </v-btn>
                                <v-btn size="small" color="warning" variant="text" @click="confirmUnbind(row)">
                                    {{ t('unbindMailAddress') }}
                                </v-btn>
                            </td>
                        </tr>
                    </tbody>
                </v-table>
            </v-window-item>
            <v-window-item value="bind">
                <div class="mt-4">
                    <Login :newAddressPath="newAddressPath" :bindUserAddress="bindAddress" />
                </div>
            </v-window-item>
        </v-window>

        <v-dialog v-model="showChangeConfirm" max-width="400">
            <v-card>
                <v-card-text>{{ t('changeMailAddress') }}?</v-card-text>
                <v-card-actions>
                    <v-spacer />
                    <v-btn @click="showChangeConfirm = false">{{ t('cancel') }}</v-btn>
                    <v-btn color="primary" @click="changeAddress">{{ t('changeMailAddress') }}</v-btn>
                </v-card-actions>
            </v-card>
        </v-dialog>

        <v-dialog v-model="showUnbindConfirm" max-width="400">
            <v-card>
                <v-card-text>{{ t('unbindMailAddress') }}?</v-card-text>
                <v-card-actions>
                    <v-spacer />
                    <v-btn @click="showUnbindConfirm = false">{{ t('cancel') }}</v-btn>
                    <v-btn color="warning" @click="unbindAddress">{{ t('unbindMailAddress') }}</v-btn>
                </v-card-actions>
            </v-card>
        </v-dialog>

        <v-snackbar v-model="snackbar.show" :color="snackbar.color" :timeout="2000">
            {{ snackbar.text }}
        </v-snackbar>
    </div>
</template>

// frontend-angular/src/app/views/index/telegram-address/telegram-address.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatTabsModule } from '@angular/material/tabs';
import { MatTableModule } from '@angular/material/table';
import { MatButtonModule } from '@angular/material/button';
import { MatDialogModule, MatDialog, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { GlobalStateService } from '../../../services/global-state.service';
import { ApiService } from '../../../services/api.service';
import { SnackbarService } from '../../../services/snackbar.service';
import { LoginComponent } from '../../common/login/login.component';

interface TelegramAddressRow {
  address: string;
  jwt: string;
}

@Component({
  selector: 'app-telegram-address',
  standalone: true,
  imports: [CommonModule, MatTabsModule, MatTableModule, MatButtonModule, MatDialogModule, LoginComponent],
  template: `
    <div class="telegram-address">
      <mat-tab-group [(selectedIndex)]="selectedTab" color="primary" animationDuration="0ms">
        <mat-tab label="地址"></mat-tab>
        <mat-tab label="绑定"></mat-tab>
      </mat-tab-group>

      <div class="tab-content">
        @if (selectedTab === 0) {
          <div class="table-container">
            <table mat-table [dataSource]="data()" class="full-width">
              <ng-container matColumnDef="address">
                <th mat-header-cell *matHeaderCellDef>地址</th>
                <td mat-cell *matCellDef="let row">{{ row.address }}</td>
              </ng-container>
              <ng-container matColumnDef="actions">
                <th mat-header-cell *matHeaderCellDef>操作</th>
                <td mat-cell *matCellDef="let row">
                  <button mat-button color="primary" (click)="confirmChange(row)">切换邮箱地址</button>
                  <button mat-button color="warn" (click)="confirmUnbind(row)">解绑邮箱地址</button>
                </td>
              </ng-container>
              <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
              <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
            </table>
          </div>
        } @else {
          <div class="login-container"><app-login></app-login></div>
        }
      </div>
    </div>
  `,
  styles: [`
    .telegram-address { padding: 16px 0; }
    .tab-content { padding: 16px 0; }
    .table-container { overflow: auto; }
    .full-width { width: 100%; }
    .login-container { margin-top: 16px; }
  `]
})
export class TelegramAddressComponent implements OnInit {
  state = inject(GlobalStateService);
  private api = inject(ApiService);
  private snackbar = inject(SnackbarService);
  private dialog = inject(MatDialog);

  selectedTab = 0;
  displayedColumns = ['address', 'actions'];
  data = signal<TelegramAddressRow[]>([]);
  selectedRow = signal<TelegramAddressRow | null>(null);

  async ngOnInit() {
    if (this.state.telegramApp()?.initData && this.data().length === 0) {
      await this.fetchData();
    }
  }

  async fetchData() {
    try {
      const telegramApp = this.state.telegramApp();
      const results = await this.api.fetch('/telegram/get_bind_address', {
        method: 'POST',
        body: { initData: telegramApp.initData }
      });
      this.data.set(results || []);
    } catch (error: any) {
      this.snackbar.error(error.message || 'error');
    }
  }

  confirmChange(row: TelegramAddressRow) {
    this.selectedRow.set(row);
    const dialogRef = this.dialog.open(TelegramConfirmDialogComponent, {
      width: '320px',
      data: { message: '切换邮箱地址?', confirmText: '切换邮箱地址', confirmColor: 'primary' }
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) this.changeAddress();
    });
  }

  confirmUnbind(row: TelegramAddressRow) {
    this.selectedRow.set(row);
    const dialogRef = this.dialog.open(TelegramConfirmDialogComponent, {
      width: '320px',
      data: { message: '解绑邮箱地址?', confirmText: '解绑邮箱地址', confirmColor: 'warn' }
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) this.unbindAddress();
    });
  }

  changeAddress() {
    const row = this.selectedRow();
    if (row) {
      this.state.setJwt(row.jwt);
      location.reload();
    }
  }

  async unbindAddress() {
    try {
      const row = this.selectedRow();
      const telegramApp = this.state.telegramApp();
      if (row) {
        await this.api.fetch('/telegram/unbind_address', {
          method: 'POST',
          body: { initData: telegramApp.initData, address: row.address }
        });
        this.state.setJwt('');
        location.reload();
      }
    } catch (error: any) {
      this.snackbar.error(error.message || 'error');
    }
  }
}

// Confirm Dialog Component
@Component({
  selector: 'app-telegram-confirm-dialog',
  standalone: true,
  imports: [CommonModule, MatDialogModule, MatButtonModule],
  template: `
    <mat-dialog-content>{{ data.message }}</mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button mat-dialog-close>取消</button>
      <button mat-raised-button [color]="data.confirmColor || 'primary'" [mat-dialog-close]="true">{{ data.confirmText }}</button>
    </mat-dialog-actions>
  `
})
export class TelegramConfirmDialogComponent {
  data = inject(MAT_DIALOG_DATA);
}
