// frontend-angular/src/app/views/user/address-management/address-management.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatTabsModule } from '@angular/material/tabs';
import { MatTableModule } from '@angular/material/table';
import { MatButtonModule } from '@angular/material/button';
import { MatChipsModule } from '@angular/material/chips';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatIconModule } from '@angular/material/icon';
import { MatDialogModule, MatDialog, MAT_DIALOG_DATA, MatDialogRef } from '@angular/material/dialog';
import { GlobalStateService } from '../../../services/global-state.service';
import { ApiService } from '../../../services/api.service';
import { SnackbarService } from '../../../services/snackbar.service';
import { LoginComponent } from '../../common/login/login.component';

interface AddressRow {
  id: number;
  name: string;
  mail_count: number;
  send_count: number;
}

@Component({
  selector: 'app-address-management',
  standalone: true,
  imports: [
    CommonModule, FormsModule, MatCardModule, MatTabsModule, MatTableModule, MatButtonModule,
    MatChipsModule, MatFormFieldModule, MatInputModule, MatIconModule, MatDialogModule, LoginComponent
  ],
  template: `
    <div class="address-management">
      <mat-tab-group [(selectedIndex)]="selectedTab" color="primary" animationDuration="0ms">
        <mat-tab label="地址"></mat-tab>
        <mat-tab label="创建或绑定"></mat-tab>
      </mat-tab-group>

      <div class="tab-content">
        @if (selectedTab === 0) {
          <div class="table-container">
            <table mat-table [dataSource]="data()" class="full-width">
              <ng-container matColumnDef="name">
                <th mat-header-cell *matHeaderCellDef>名称</th>
                <td mat-cell *matCellDef="let row">{{ row.name }}</td>
              </ng-container>
              <ng-container matColumnDef="mail_count">
                <th mat-header-cell *matHeaderCellDef>邮件数量</th>
                <td mat-cell *matCellDef="let row"><mat-chip color="primary" highlighted>{{ row.mail_count }}</mat-chip></td>
              </ng-container>
              <ng-container matColumnDef="send_count">
                <th mat-header-cell *matHeaderCellDef>发送数量</th>
                <td mat-cell *matCellDef="let row"><mat-chip color="primary" highlighted>{{ row.send_count }}</mat-chip></td>
              </ng-container>
              <ng-container matColumnDef="actions">
                <th mat-header-cell *matHeaderCellDef>操作</th>
                <td mat-cell *matCellDef="let row">
                  <button mat-button color="primary" (click)="confirmChange(row)">切换地址</button>
                  <button mat-button color="primary" (click)="openTransferDialog(row)">转移地址</button>
                  <button mat-button color="warn" (click)="confirmUnbind(row)">解绑地址</button>
                </td>
              </ng-container>
              <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
              <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
            </table>
          </div>
        } @else {
          <div class="login-container">
            <mat-card appearance="outlined">
              <mat-card-content><app-login></app-login></mat-card-content>
            </mat-card>
          </div>
        }
      </div>
    </div>
  `,
  styles: [`
    .address-management { padding: 16px 0; }
    .tab-content { padding: 16px 0; }
    .table-container { overflow: auto; }
    .full-width { width: 100%; }
    .login-container { display: flex; justify-content: center; }
    .login-container mat-card { max-width: 600px; width: 100%; }
  `]
})
export class AddressManagementComponent implements OnInit {
  state = inject(GlobalStateService);
  private api = inject(ApiService);
  private snackbar = inject(SnackbarService);
  private router = inject(Router);
  private dialog = inject(MatDialog);

  selectedTab = 0;
  displayedColumns = ['name', 'mail_count', 'send_count', 'actions'];
  data = signal<AddressRow[]>([]);
  currentAddress = signal('');
  currentAddressId = signal(0);

  async ngOnInit() {
    await this.fetchData();
  }

  async fetchData() {
    try {
      const { results } = await this.api.getBindAddressList();
      this.data.set(results || []);
    } catch (error: any) {
      this.snackbar.error(error.message || 'error');
    }
  }

  confirmChange(row: AddressRow) {
    this.currentAddressId.set(row.id);
    const dialogRef = this.dialog.open(AddressConfirmDialogComponent, {
      width: '320px',
      data: { message: '切换地址?', confirmText: '切换地址', confirmColor: 'primary' }
    });
    dialogRef.afterClosed().subscribe(result => { if (result) this.changeMailAddress(); });
  }

  confirmUnbind(row: AddressRow) {
    this.currentAddressId.set(row.id);
    const dialogRef = this.dialog.open(AddressConfirmDialogComponent, {
      width: '360px',
      data: { message: '解绑前请切换到此邮箱地址并保存邮箱地址凭证。', confirmText: '解绑地址', confirmColor: 'warn' }
    });
    dialogRef.afterClosed().subscribe(result => { if (result) this.unbindAddress(); });
  }

  openTransferDialog(row: AddressRow) {
    this.currentAddressId.set(row.id);
    this.currentAddress.set(row.name);
    const dialogRef = this.dialog.open(TransferAddressDialogComponent, {
      width: '450px',
      data: { address: row.name }
    });
    dialogRef.afterClosed().subscribe(async (targetEmail) => {
      if (targetEmail) {
        await this.transferAddress(targetEmail);
      }
    });
  }

  async changeMailAddress() {
    try {
      const res = await this.api.getBindAddressJwt(this.currentAddressId());
      this.snackbar.success('切换地址 成功');
      if (!res.jwt) {
        this.snackbar.error('jwt not found');
        return;
      }
      this.state.setJwt(res.jwt);
      await this.router.navigate(['/']);
      location.reload();
    } catch (error: any) {
      this.snackbar.error(error.message || 'error');
    }
  }

  async unbindAddress() {
    try {
      await this.api.unbindAddress(this.currentAddressId());
      this.snackbar.success('解绑地址 成功');
      await this.fetchData();
    } catch (error: any) {
      this.snackbar.error(error.message || 'error');
    }
  }

  async transferAddress(targetUserEmail: string) {
    try {
      await this.api.transferAddress(this.currentAddressId(), targetUserEmail);
      this.snackbar.success('转移地址 成功');
      await this.fetchData();
    } catch (error: any) {
      this.snackbar.error(error.message || 'error');
    }
  }
}

// Confirm Dialog
@Component({
  selector: 'app-address-confirm-dialog',
  standalone: true,
  imports: [CommonModule, MatDialogModule, MatButtonModule],
  template: `
    <mat-dialog-content>{{ data.message }}</mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button mat-dialog-close>取消</button>
      <button mat-raised-button [color]="data.confirmColor || 'primary'" [mat-dialog-close]="true">{{ data.confirmText }}</button>
    </mat-dialog-actions>
  `
})
export class AddressConfirmDialogComponent {
  data = inject(MAT_DIALOG_DATA);
}

// Transfer Address Dialog
@Component({
  selector: 'app-transfer-address-dialog',
  standalone: true,
  imports: [CommonModule, FormsModule, MatDialogModule, MatButtonModule, MatFormFieldModule, MatInputModule],
  template: `
    <h2 mat-dialog-title>转移地址</h2>
    <mat-dialog-content>
      <p class="mb-2">转移地址到其他用户将会从你的账户中移除此地址并转移给其他用户。确定要转移地址吗？</p>
      <p class="mb-3">转移地址: {{ data.address }}</p>
      <mat-form-field appearance="outline" class="full-width">
        <mat-label>目标用户邮箱</mat-label>
        <input matInput [(ngModel)]="targetUserEmail">
      </mat-form-field>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button mat-dialog-close>取消</button>
      <button mat-raised-button color="warn" [mat-dialog-close]="targetUserEmail" [disabled]="!targetUserEmail">转移地址</button>
    </mat-dialog-actions>
  `,
  styles: [`.full-width { width: 100%; } .mb-2 { margin-bottom: 8px; } .mb-3 { margin-bottom: 12px; }`]
})
export class TransferAddressDialogComponent {
  data = inject(MAT_DIALOG_DATA);
  targetUserEmail = '';
}

// frontend/src/views/user/AddressManagement.vue
<script setup>
import { ref, onMounted } from 'vue';
import { useI18n } from 'vue-i18n'
import { useRouter } from 'vue-router';

import { useGlobalState } from '../../store'
import { api } from '../../api'
import { getRouterPathWithLang } from '../../utils'

import Login from '../common/Login.vue';

const { jwt, loading } = useGlobalState()
const router = useRouter()

const snackbar = ref({ show: false, text: '', color: 'success' })
const showMessage = (text, color = 'success') => {
    snackbar.value = { show: true, text, color }
}

const { locale, t } = useI18n({
    messages: {
        en: {
            success: 'success',
            name: 'Name',
            mail_count: 'Mail Count',
            send_count: 'Send Count',
            actions: 'Actions',
            changeMailAddress: 'Change Address',
            unbindAddress: 'Unbind Address',
            unbindAddressTip: 'Before unbinding, please switch to this email address and save the email address credential.',
            transferAddress: 'Transfer Address',
            targetUserEmail: 'Target User Email',
            transferAddressTip: 'Transfer address to another user will remove the address from your account and transfer it to another user. Are you sure to transfer the address?',
            address: 'Address',
            create_or_bind: 'Create or Bind',
            cancel: 'Cancel',
        },
        zh: {
            success: '成功',
            name: '名称',
            mail_count: '邮件数量',
            send_count: '发送数量',
            actions: '操作',
            changeMailAddress: '切换地址',
            unbindAddress: '解绑地址',
            unbindAddressTip: '解绑前请切换到此邮箱地址并保存邮箱地址凭证。',
            transferAddress: '转移地址',
            targetUserEmail: '目标用户邮箱',
            transferAddressTip: '转移地址到其他用户将会从你的账户中移除此地址并转移给其他用户。确定要转移地址吗？',
            address: '地址',
            create_or_bind: '创建或绑定',
            cancel: '取消',
        }
    }
});

const tabValue = ref('address')
const data = ref([])
const showTransferAddress = ref(false)
const showChangeConfirm = ref(false)
const showUnbindConfirm = ref(false)
const currentAddress = ref("")
const currentAddressId = ref(0)
const targetUserEmail = ref('')

const changeMailAddress = async () => {
    try {
        const res = await api.fetch(`/user_api/bind_address_jwt/${currentAddressId.value}`);
        showMessage(t('changeMailAddress') + " " + t('success'));
        if (!res.jwt) {
            showMessage("jwt not found", 'error');
            return;
        }
        jwt.value = res.jwt;
        await router.push(getRouterPathWithLang("/", locale.value))
        location.reload();
    } catch (error) {
        console.log(error)
        showMessage(error.message || "error", 'error');
    }
}

const unbindAddress = async () => {
    try {
        await api.fetch(`/user_api/unbind_address`, {
            method: 'POST',
            body: JSON.stringify({ address_id: currentAddressId.value })
        });
        showMessage(t('unbindAddress') + " " + t('success'));
        showUnbindConfirm.value = false;
        await fetchData();
    } catch (error) {
        console.log(error)
        showMessage(error.message || "error", 'error');
    }
}

const transferAddress = async () => {
    if (!targetUserEmail.value) {
        showMessage("targetUserEmail is required", 'error');
        return;
    }
    if (!currentAddressId.value) {
        showMessage("currentAddressId is required", 'error');
        return;
    }
    try {
        await api.fetch(`/user_api/transfer_address`, {
            method: 'POST',
            body: JSON.stringify({
                address_id: currentAddressId.value,
                target_user_email: targetUserEmail.value
            })
        });
        showMessage(t('transferAddress') + " " + t('success'));
        await fetchData();
        showTransferAddress.value = false;
        currentAddressId.value = 0;
        currentAddress.value = "";
        targetUserEmail.value = "";
    } catch (error) {
        console.log(error)
        showMessage(error.message || "error", 'error');
    }
}

const fetchData = async () => {
    try {
        const { results } = await api.fetch(`/user_api/bind_address`);
        data.value = results;
    } catch (error) {
        console.log(error)
        showMessage(error.message || "error", 'error');
    }
}

const confirmChange = (row) => {
    currentAddressId.value = row.id;
    currentAddress.value = row.name;
    showChangeConfirm.value = true;
}

const confirmUnbind = (row) => {
    currentAddressId.value = row.id;
    currentAddress.value = row.name;
    showUnbindConfirm.value = true;
}

const openTransfer = (row) => {
    currentAddressId.value = row.id;
    currentAddress.value = row.name;
    showTransferAddress.value = true;
}

onMounted(async () => {
    await fetchData()
})
</script>

<template>
    <div>
        <v-tabs v-model="tabValue" color="primary">
            <v-tab value="address">{{ t('address') }}</v-tab>
            <v-tab value="create_or_bind">{{ t('create_or_bind') }}</v-tab>
        </v-tabs>

        <v-window v-model="tabValue">
            <v-window-item value="address">
                <div style="overflow: auto;" class="mt-4">
                    <v-table>
                        <thead>
                            <tr>
                                <th>{{ t('name') }}</th>
                                <th>{{ t('mail_count') }}</th>
                                <th>{{ t('send_count') }}</th>
                                <th>{{ t('actions') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr v-for="row in data" :key="row.id">
                                <td>{{ row.name }}</td>
                                <td>
                                    <v-chip color="success" size="small">{{ row.mail_count }}</v-chip>
                                </td>
                                <td>
                                    <v-chip color="success" size="small">{{ row.send_count }}</v-chip>
                                </td>
                                <td>
                                    <v-btn size="small" color="primary" variant="text" @click="confirmChange(row)">
                                        {{ t('changeMailAddress') }}
                                    </v-btn>
                                    <v-btn size="small" color="primary" variant="text" @click="openTransfer(row)">
                                        {{ t('transferAddress') }}
                                    </v-btn>
                                    <v-btn size="small" color="error" variant="text" @click="confirmUnbind(row)">
                                        {{ t('unbindAddress') }}
                                    </v-btn>
                                </td>
                            </tr>
                        </tbody>
                    </v-table>
                </div>
            </v-window-item>
            <v-window-item value="create_or_bind">
                <div class="d-flex justify-center mt-4">
                    <Login />
                </div>
            </v-window-item>
        </v-window>

        <v-dialog v-model="showTransferAddress" max-width="500">
            <v-card>
                <v-card-title>{{ t('transferAddress') }}</v-card-title>
                <v-card-text>
                    <p class="mb-2">{{ t("transferAddressTip") }}</p>
                    <p class="mb-4">{{ t('transferAddress') + ": " + currentAddress }}</p>
                    <v-text-field v-model="targetUserEmail" :label="t('targetUserEmail')" variant="outlined"
                        density="compact" />
                </v-card-text>
                <v-card-actions>
                    <v-spacer />
                    <v-btn @click="showTransferAddress = false">{{ t('cancel') }}</v-btn>
                    <v-btn :loading="loading" @click="transferAddress" color="error">{{ t('transferAddress') }}</v-btn>
                </v-card-actions>
            </v-card>
        </v-dialog>

        <v-dialog v-model="showChangeConfirm" max-width="400">
            <v-card>
                <v-card-text>{{ t('changeMailAddress') }}?</v-card-text>
                <v-card-actions>
                    <v-spacer />
                    <v-btn @click="showChangeConfirm = false">{{ t('cancel') }}</v-btn>
                    <v-btn color="primary" @click="changeMailAddress">{{ t('changeMailAddress') }}</v-btn>
                </v-card-actions>
            </v-card>
        </v-dialog>

        <v-dialog v-model="showUnbindConfirm" max-width="400">
            <v-card>
                <v-card-text>{{ t('unbindAddressTip') }}</v-card-text>
                <v-card-actions>
                    <v-spacer />
                    <v-btn @click="showUnbindConfirm = false">{{ t('cancel') }}</v-btn>
                    <v-btn color="error" @click="unbindAddress">{{ t('unbindAddress') }}</v-btn>
                </v-card-actions>
            </v-card>
        </v-dialog>

        <v-snackbar v-model="snackbar.show" :color="snackbar.color" :timeout="2000">
            {{ snackbar.text }}
        </v-snackbar>
    </div>
</template>


<style scoped>
/* v-window 保持 hidden 确保切换动画正常 */
.v-window {
    overflow: hidden !important;
    padding: 4px !important;
}
/* v-window-item 内容加 padding 防止按钮动画被裁剪 */
.v-window-item {
    padding: 4px !important;
}
</style>
