// frontend-angular/src/app/views/user/user-login/user-login.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatTabsModule } from '@angular/material/tabs';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatIconModule } from '@angular/material/icon';
import { MatDividerModule } from '@angular/material/divider';
import { MatDialogModule, MatDialog, MAT_DIALOG_DATA, MatDialogRef } from '@angular/material/dialog';
import { GlobalStateService } from '../../../services/global-state.service';
import { ApiService } from '../../../services/api.service';
import { SnackbarService } from '../../../services/snackbar.service';
import { hashPassword } from '../../../utils';

@Component({
  selector: 'app-user-login',
  standalone: true,
  imports: [
    CommonModule, FormsModule, MatCardModule, MatTabsModule, MatButtonModule,
    MatFormFieldModule, MatInputModule, MatIconModule, MatDividerModule, MatDialogModule
  ],
  template: `
    @if (state.userOpenSettings().fetched) {
      <div class="user-login-container">
        <mat-tab-group [(selectedIndex)]="selectedTab" color="primary" animationDuration="0ms">
          <mat-tab label="登录"></mat-tab>
          @if (state.userOpenSettings().enable) {
            <mat-tab label="注册"></mat-tab>
          }
        </mat-tab-group>

        <div class="tab-content">
          @if (selectedTab === 0) {
            <mat-form-field appearance="outline" class="full-width">
              <mat-label>邮箱</mat-label>
              <input matInput [(ngModel)]="user.email" type="email">
            </mat-form-field>
            <mat-form-field appearance="outline" class="full-width">
              <mat-label>密码</mat-label>
              <input matInput [(ngModel)]="user.password" type="password">
            </mat-form-field>
            <button mat-stroked-button color="primary" class="full-width mb-2" (click)="emailLogin()">
              <mat-icon>email</mat-icon> 登录
            </button>
            <button mat-button (click)="openForgotPasswordDialog()" class="mb-3">忘记密码</button>
            <mat-divider class="mb-3"></mat-divider>
            <button mat-stroked-button color="primary" class="full-width mb-2" (click)="passkeyLogin()">
              <mat-icon>key</mat-icon> 使用 Passkey 登录
            </button>
            @for (item of state.userOpenSettings().oauth2ClientIDs; track item.clientID) {
              <button mat-stroked-button class="full-width mb-2" (click)="oauth2Login(item.clientID)">
                <mat-icon>{{ item.name.toLowerCase() === 'github' ? 'code' : 'login' }}</mat-icon>
                使用 {{ item.name }} 登录
              </button>
            }
          } @else if (selectedTab === 1) {
            <mat-form-field appearance="outline" class="full-width">
              <mat-label>邮箱</mat-label>
              <input matInput [(ngModel)]="user.email" type="email">
            </mat-form-field>
            <mat-form-field appearance="outline" class="full-width">
              <mat-label>密码</mat-label>
              <input matInput [(ngModel)]="user.password" type="password">
            </mat-form-field>
            @if (state.userOpenSettings().enableMailVerify) {
              <div class="verify-code-row">
                <mat-form-field appearance="outline" class="flex-1">
                  <mat-label>验证码</mat-label>
                  <input matInput [(ngModel)]="user.code">
                </mat-form-field>
                <button mat-stroked-button color="primary" [disabled]="verifyCodeTimeout() > 0" (click)="sendVerificationCode()">
                  {{ verifyCodeTimeout() > 0 ? '等待' + verifyCodeTimeout() + '秒' : '发送验证码' }}
                </button>
              </div>
            }
            <button mat-stroked-button color="primary" class="full-width" (click)="emailSignup()">注册</button>
          }
        </div>
      </div>
    }
  `,
  styles: [`
    .user-login-container { max-width: 600px; width: 100%; }
    .tab-content { padding: 16px 0; }
    .full-width { width: 100%; }
    .mb-2 { margin-bottom: 8px; }
    .mb-3 { margin-bottom: 12px; }
    .verify-code-row { display: flex; gap: 8px; align-items: flex-start; margin-bottom: 16px; }
    .flex-1 { flex: 1; }
  `]
})
export class UserLoginComponent implements OnInit {
  state = inject(GlobalStateService);
  private api = inject(ApiService);
  private snackbar = inject(SnackbarService);
  private dialog = inject(MatDialog);

  selectedTab = 0;
  verifyCodeTimeout = signal(0);
  private verifyCodeExpire = 0;
  user = { email: '', password: '', code: '' };
  cfToken = '';

  async ngOnInit() {
    if (!this.state.userOpenSettings().fetched) {
      await this.api.getUserOpenSettings();
    }
  }

  openForgotPasswordDialog() {
    const dialogRef = this.dialog.open(ForgotPasswordDialogComponent, {
      width: '450px',
      data: { 
        enable: this.state.userOpenSettings().enable,
        enableMailVerify: this.state.userOpenSettings().enableMailVerify,
        cfTurnstileSiteKey: this.state.openSettings().cfTurnstileSiteKey
      }
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.selectedTab = 0;
        this.snackbar.success('密码重置成功，请登录');
      }
    });
  }

  async emailLogin() {
    if (!this.user.email || !this.user.password) {
      this.snackbar.error('请输入邮箱和密码');
      return;
    }
    try {
      const hashedPassword = await hashPassword(this.user.password);
      const res = await this.api.userLogin(this.user.email, hashedPassword);
      this.state.setUserJwt(res.jwt);
      location.reload();
    } catch (error: any) {
      this.snackbar.error(error.message || '登录失败');
    }
  }

  async sendVerificationCode() {
    if (!this.user.email) {
      this.snackbar.error('请输入邮箱');
      return;
    }
    try {
      const res = await this.api.sendVerifyCode(this.user.email, this.cfToken);
      if (res && res.expirationTtl) {
        this.snackbar.success(`验证码已发送, ${res.expirationTtl} 秒后失效`);
        this.verifyCodeExpire = Date.now() + res.expirationTtl * 1000;
        this.startVerifyCodeCountdown();
      }
    } catch (error: any) {
      this.snackbar.error(error.message || '发送验证码失败');
    }
  }

  private startVerifyCodeCountdown() {
    const intervalId = setInterval(() => {
      const remaining = Math.round((this.verifyCodeExpire - Date.now()) / 1000);
      if (remaining <= 0) {
        clearInterval(intervalId);
        this.verifyCodeTimeout.set(0);
      } else {
        this.verifyCodeTimeout.set(remaining);
      }
    }, 1000);
  }

  async emailSignup() {
    if (!this.user.email || !this.user.password) {
      this.snackbar.error('请输入邮箱和密码');
      return;
    }
    if (!this.user.code && this.state.userOpenSettings().enableMailVerify) {
      this.snackbar.error('请输入验证码');
      return;
    }
    try {
      const hashedPassword = await hashPassword(this.user.password);
      await this.api.userRegister(this.user.email, hashedPassword, this.user.code);
      this.selectedTab = 0;
      this.snackbar.success('请登录');
    } catch (error: any) {
      this.snackbar.error(error.message || '注册失败');
    }
  }

  async passkeyLogin() {
    try {
      const { startAuthentication } = await import('@simplewebauthn/browser');
      const options = await this.api.passkeyAuthenticateRequest(location.hostname);
      const credential = await startAuthentication(options);
      const res = await this.api.passkeyAuthenticateResponse(location.origin, location.hostname, credential);
      this.state.setUserJwt(res.jwt);
      location.reload();
    } catch (error: any) {
      console.error(error);
      this.snackbar.error(error.message || 'Passkey 登录失败');
    }
  }

  async oauth2Login(clientID: string) {
    try {
      const state = Math.random().toString(36).substring(2);
      this.state.setUserOauth2SessionClientID(clientID);
      this.state.setUserOauth2SessionState(state);
      const res = await this.api.getOauth2LoginUrl(clientID, state);
      location.href = res.url;
    } catch (error: any) {
      this.snackbar.error(error.message || '登录失败');
    }
  }
}

// Forgot Password Dialog
@Component({
  selector: 'app-forgot-password-dialog',
  standalone: true,
  imports: [CommonModule, FormsModule, MatDialogModule, MatButtonModule, MatFormFieldModule, MatInputModule, MatIconModule],
  template: `
    <h2 mat-dialog-title>忘记密码</h2>
    <mat-dialog-content>
      @if (data.enable && data.enableMailVerify) {
        <mat-form-field appearance="outline" class="full-width">
          <mat-label>邮箱</mat-label>
          <input matInput [(ngModel)]="email" type="email">
        </mat-form-field>
        <mat-form-field appearance="outline" class="full-width">
          <mat-label>新密码</mat-label>
          <input matInput [(ngModel)]="password" type="password">
        </mat-form-field>
        <div class="verify-code-row">
          <mat-form-field appearance="outline" class="flex-1">
            <mat-label>验证码</mat-label>
            <input matInput [(ngModel)]="code">
          </mat-form-field>
          <button mat-stroked-button color="primary" [disabled]="verifyCodeTimeout > 0" (click)="sendVerificationCode()">
            {{ verifyCodeTimeout > 0 ? '等待' + verifyCodeTimeout + '秒' : '发送验证码' }}
          </button>
        </div>
      } @else {
        <div class="warning-alert">
          <mat-icon>warning</mat-icon>
          <span>未开启邮箱验证或未开启注册功能，无法重置密码，请联系管理员</span>
        </div>
      }
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button mat-dialog-close>取消</button>
      @if (data.enable && data.enableMailVerify) {
        <button mat-raised-button color="primary" (click)="resetPassword()">重置密码</button>
      }
    </mat-dialog-actions>
  `,
  styles: [`
    .full-width { width: 100%; }
    .verify-code-row { display: flex; gap: 8px; align-items: flex-start; }
    .flex-1 { flex: 1; }
    .warning-alert {
      display: flex; align-items: center; gap: 8px; padding: 12px 16px;
      background-color: #fff3e0; border-radius: 4px; color: #e65100;
    }
  `]
})
export class ForgotPasswordDialogComponent {
  data = inject(MAT_DIALOG_DATA);
  private dialogRef = inject(MatDialogRef<ForgotPasswordDialogComponent>);
  private api = inject(ApiService);
  private snackbar = inject(SnackbarService);

  email = '';
  password = '';
  code = '';
  verifyCodeTimeout = 0;
  private verifyCodeExpire = 0;

  async sendVerificationCode() {
    if (!this.email) {
      this.snackbar.error('请输入邮箱');
      return;
    }
    try {
      const res = await this.api.sendVerifyCode(this.email, '');
      if (res && res.expirationTtl) {
        this.snackbar.success(`验证码已发送, ${res.expirationTtl} 秒后失效`);
        this.verifyCodeExpire = Date.now() + res.expirationTtl * 1000;
        this.startVerifyCodeCountdown();
      }
    } catch (error: any) {
      this.snackbar.error(error.message || '发送验证码失败');
    }
  }

  private startVerifyCodeCountdown() {
    const intervalId = setInterval(() => {
      const remaining = Math.round((this.verifyCodeExpire - Date.now()) / 1000);
      if (remaining <= 0) {
        clearInterval(intervalId);
        this.verifyCodeTimeout = 0;
      } else {
        this.verifyCodeTimeout = remaining;
      }
    }, 1000);
  }

  async resetPassword() {
    if (!this.email || !this.password || !this.code) {
      this.snackbar.error('请填写完整信息');
      return;
    }
    try {
      const hashedPassword = await hashPassword(this.password);
      await this.api.userRegister(this.email, hashedPassword, this.code);
      this.dialogRef.close(true);
    } catch (error: any) {
      this.snackbar.error(error.message || '重置失败');
    }
  }
}

// frontend/src/views/user/UserLogin.vue
<script setup>
import { onMounted, ref } from "vue";
import { useI18n } from 'vue-i18n'
import { startAuthentication } from '@simplewebauthn/browser';

import { api } from '../../api';
import { useGlobalState } from '../../store'
import { hashPassword } from '../../utils';

import Turnstile from '../../components/Turnstile.vue';

const {
    userJwt, userOpenSettings, openSettings,
    userOauth2SessionState, userOauth2SessionClientID
} = useGlobalState()

const snackbar = ref({ show: false, text: '', color: 'success' })
const showMessage = (text, color = 'success') => {
    snackbar.value = { show: true, text, color }
}

const { t } = useI18n({
    messages: {
        en: {
            login: 'Login',
            register: 'Register',
            email: 'Email',
            password: 'Password',
            verifyCode: 'Verification Code',
            verifyCodeSent: 'Verification Code Sent, expires in {timeout} seconds',
            waitforVerifyCode: 'Wait for {timeout} seconds',
            sendVerificationCode: 'Send Verification Code',
            forgotPassword: 'Forgot Password',
            cannotForgotPassword: 'Mail verification is disabled or register is disabled, cannot reset password, please contact administrator',
            resetPassword: 'Reset Password',
            pleaseInput: 'Please input email and password',
            pleaseInputEmail: 'Please input email',
            pleaseInputCode: 'Please input code',
            pleaseCompleteTurnstile: 'Please complete turnstile',
            pleaseLogin: 'Please login',
            loginWithPasskey: 'Login with Passkey',
            loginWith: 'Login with {provider}',
            cancel: 'Cancel',
        },
        zh: {
            login: '登录',
            register: '注册',
            email: '邮箱',
            password: '密码',
            verifyCode: '验证码',
            sendVerificationCode: '发送验证码',
            verifyCodeSent: '验证码已发送, {timeout} 秒后失效',
            waitforVerifyCode: '等待{timeout}秒',
            forgotPassword: '忘记密码',
            cannotForgotPassword: '未开启邮箱验证或未开启注册功能，无法重置密码，请联系管理员',
            resetPassword: '重置密码',
            pleaseInput: '请输入邮箱和密码',
            pleaseInputEmail: '请输入邮箱',
            pleaseInputCode: '请输入验证码',
            pleaseCompleteTurnstile: '请完成人机验证',
            pleaseLogin: '请登录',
            loginWithPasskey: '使用 Passkey 登录',
            loginWith: '使用 {provider} 登录',
            cancel: '取消',
        }
    }
});

const tabValue = ref("signin");
const showModal = ref(false);
const user = ref({
    email: "",
    password: "",
    code: ""
});
const cfToken = ref("")

const emailLogin = async () => {
    if (!user.value.email || !user.value.password) {
        showMessage(t('pleaseInput'), 'error');
        return;
    }
    try {
        const res = await api.fetch(`/user_api/login`, {
            method: "POST",
            body: JSON.stringify({
                email: user.value.email,
                password: await hashPassword(user.value.password)
            })
        });
        userJwt.value = res.jwt;
        location.reload();
    } catch (error) {
        showMessage(error.message || "login failed", 'error');
    }
};

const verifyCodeExpire = ref(0);
const verifyCodeTimeout = ref(0);

const getVerifyCodeTimeout = () => {
    if (!verifyCodeExpire.value || verifyCodeExpire.value < new Date().getTime()) return 0;
    return Math.round((verifyCodeExpire.value - new Date().getTime()) / 1000);
};

const sendVerificationCode = async () => {
    if (!user.value.email) {
        showMessage(t('pleaseInputEmail'), 'error');
        return;
    }
    if (openSettings.value.cfTurnstileSiteKey && !cfToken.value && userOpenSettings.value.enableMailVerify) {
        showMessage(t('pleaseCompleteTurnstile'), 'error');
        return;
    }
    try {
        const res = await api.fetch(`/user_api/verify_code`, {
            method: "POST",
            body: JSON.stringify({
                email: user.value.email,
                cf_token: cfToken.value
            })
        });
        if (res && res.expirationTtl) {
            showMessage(t('verifyCodeSent', { timeout: res.expirationTtl }));
            verifyCodeExpire.value = new Date().getTime() + res.expirationTtl * 1000;
            const intervalId = setInterval(() => {
                verifyCodeTimeout.value = getVerifyCodeTimeout();
                if (verifyCodeTimeout.value <= 0) {
                    clearInterval(intervalId);
                    verifyCodeTimeout.value = 0;
                }
            }, 1000);
        }
    } catch (error) {
        showMessage(error.message || "send verification code failed", 'error');
    }
};

const emailSignup = async () => {
    if (!user.value.email || !user.value.password) {
        showMessage(t('pleaseInput'), 'error');
        return;
    }
    if (!user.value.code && userOpenSettings.value.enableMailVerify) {
        showMessage(t('pleaseInputCode'), 'error');
        return;
    }
    try {
        const res = await api.fetch(`/user_api/register`, {
            method: "POST",
            body: JSON.stringify({
                email: user.value.email,
                password: await hashPassword(user.value.password),
                code: user.value.code
            })
        });
        if (res) {
            tabValue.value = "signin";
            showMessage(t('pleaseLogin'));
        }
        showModal.value = false;
    } catch (error) {
        showMessage(error.message || "register failed", 'error');
    }
};

const passkeyLogin = async () => {
    try {
        const options = await api.fetch(`/user_api/passkey/authenticate_request`, {
            method: 'POST',
            body: JSON.stringify({
                domain: location.hostname,
            })
        })
        const credential = await startAuthentication(options)

        const res = await api.fetch(`/user_api/passkey/authenticate_response`, {
            method: 'POST',
            body: JSON.stringify({
                origin: location.origin,
                domain: location.hostname,
                credential
            })
        })
        userJwt.value = res.jwt;
        location.reload();
    } catch (e) {
        console.error(e)
        showMessage(e.message, 'error')
    }
};

const oauth2Login = async (clientID) => {
    try {
        userOauth2SessionClientID.value = clientID;
        userOauth2SessionState.value = Math.random().toString(36).substring(2);
        const res = await api.fetch(`/user_api/oauth2/login_url?clientID=${clientID}&state=${userOauth2SessionState.value}`);
        location.href = res.url;
    } catch (error) {
        showMessage(error.message || "login failed", 'error');
    }
};
</script>

<template>
    <div class="d-flex justify-center">
        <div v-if="userOpenSettings.fetched" style="max-width: 600px; width: 100%;">
            <v-tabs v-model="tabValue" color="primary" class="mb-4">
                <v-tab value="signin">{{ t('login') }}</v-tab>
                <v-tab v-if="userOpenSettings.enable" value="signup">{{ t('register') }}</v-tab>
            </v-tabs>

            <v-window v-model="tabValue">
                <v-window-item value="signin">
                    <v-text-field v-model="user.email" :label="t('email')" variant="outlined" density="compact"
                        class="mt-4 mb-3" />
                    <v-text-field v-model="user.password" :label="t('password')" type="password" variant="outlined"
                        density="compact" class="mb-3" />
                    <v-btn @click="emailLogin" color="primary" variant="outlined" block class="mb-2">
                        {{ t('login') }}
                    </v-btn>
                    <v-btn @click="showModal = true" variant="text" size="small" class="mb-4">
                        {{ t('forgotPassword') }}
                    </v-btn>
                    <v-divider class="mb-4" />
                    <v-btn @click="passkeyLogin" color="primary" variant="outlined" block prepend-icon="mdi-key"
                        class="mb-2">
                        {{ t('loginWithPasskey') }}
                    </v-btn>
                    <v-btn v-for="item in userOpenSettings.oauth2ClientIDs" :key="item.clientID"
                        @click="oauth2Login(item.clientID)" variant="outlined" block class="mb-2"
                        :prepend-icon="item.name.toLowerCase() === 'github' ? 'mdi-github' : 'mdi-login'">
                        {{ t('loginWith', { provider: item.name }) }}
                    </v-btn>
                </v-window-item>

                <v-window-item v-if="userOpenSettings.enable" value="signup">
                    <v-text-field v-model="user.email" :label="t('email')" variant="outlined" density="compact"
                        class="mt-4 mb-3" />
                    <v-text-field v-model="user.password" :label="t('password')" type="password" variant="outlined"
                        density="compact" class="mb-3" />
                    <Turnstile v-if="userOpenSettings.enableMailVerify" v-model:value="cfToken" />
                    <div v-if="userOpenSettings.enableMailVerify" class="d-flex ga-2 mb-3">
                        <v-text-field v-model="user.code" :label="t('verifyCode')" variant="outlined" density="compact"
                            hide-details />
                        <v-btn @click="sendVerificationCode" color="primary" variant="outlined"
                            :disabled="verifyCodeTimeout > 0">
                            {{ verifyCodeTimeout > 0 ? t('waitforVerifyCode', { timeout: verifyCodeTimeout }) :
                                t('sendVerificationCode') }}
                        </v-btn>
                    </div>
                    <v-btn @click="emailSignup" color="primary" variant="outlined" block>
                        {{ t('register') }}
                    </v-btn>
                </v-window-item>
            </v-window>
        </div>

        <v-dialog v-model="showModal" max-width="500">
            <v-card>
                <v-card-title>{{ t('forgotPassword') }}</v-card-title>
                <v-card-text>
                    <div v-if="userOpenSettings.enable && userOpenSettings.enableMailVerify">
                        <v-text-field v-model="user.email" :label="t('email')" variant="outlined" density="compact"
                            class="mb-3" />
                        <v-text-field v-model="user.password" :label="t('password')" type="password" variant="outlined"
                            density="compact" class="mb-3" />
                        <Turnstile v-model:value="cfToken" />
                        <div class="d-flex ga-2 mb-3">
                            <v-text-field v-model="user.code" :label="t('verifyCode')" variant="outlined"
                                density="compact" hide-details />
                            <v-btn @click="sendVerificationCode" color="primary" variant="outlined"
                                :disabled="verifyCodeTimeout > 0">
                                {{ verifyCodeTimeout > 0 ? t('waitforVerifyCode', { timeout: verifyCodeTimeout }) :
                                    t('sendVerificationCode') }}
                            </v-btn>
                        </div>
                        <v-btn @click="emailSignup" color="primary" variant="outlined" block>
                            {{ t('resetPassword') }}
                        </v-btn>
                    </div>
                    <v-alert v-else type="warning" variant="tonal">
                        {{ t('cannotForgotPassword') }}
                    </v-alert>
                </v-card-text>
                <v-card-actions>
                    <v-spacer />
                    <v-btn @click="showModal = false">{{ t('cancel') }}</v-btn>
                </v-card-actions>
            </v-card>
        </v-dialog>

        <v-snackbar v-model="snackbar.show" :color="snackbar.color" :timeout="2000">
            {{ snackbar.text }}
        </v-snackbar>
    </div>
</template>


<style scoped>
/* v-window 保持 hidden 确保切换动画正常 */
.v-window {
    overflow: hidden !important;
}
/* v-window-item 内容加 padding 防止按钮动画被裁剪 */
.v-window-item {
    padding: 4px !important;
}
</style>
