// frontend-angular/src/app/views/user/user-mailbox/user-mailbox.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSelectModule } from '@angular/material/select';
import { MatButtonModule } from '@angular/material/button';
import { ApiService } from '../../../services/api.service';
import { SnackbarService } from '../../../services/snackbar.service';
import { MailboxComponent } from '../../../components/mailbox/mailbox.component';

@Component({
  selector: 'app-user-mailbox',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatFormFieldModule,
    MatSelectModule,
    MatButtonModule,
    MailboxComponent,
  ],
  template: `
    <div class="user-mailbox">
      <div class="filter-row">
        <mat-form-field appearance="outline" class="address-select">
          <mat-label>留空查询所有地址</mat-label>
          <mat-select [(ngModel)]="addressFilter" (selectionChange)="queryMail()">
            <mat-option [value]="''">全部地址</mat-option>
            @for (option of addressFilterOptions(); track option.value) {
              <mat-option [value]="option.value">{{ option.title }}</mat-option>
            }
          </mat-select>
        </mat-form-field>
        <button mat-stroked-button color="primary" (click)="queryMail()">查询</button>
      </div>

      <app-mailbox
        [enableUserDeleteEmail]="true"
        [fetchMailData]="fetchMailData"
        [showFilterInput]="true">
      </app-mailbox>
    </div>
  `,
  styles: [`
    .user-mailbox {
      padding: 16px 0;
    }
    .filter-row {
      display: flex;
      gap: 8px;
      align-items: flex-start;
      margin-bottom: 16px;
    }
    .address-select {
      max-width: 300px;
    }
  `]
})
export class UserMailboxComponent implements OnInit {
  private api = inject(ApiService);
  private snackbar = inject(SnackbarService);

  addressFilter = '';
  addressFilterOptions = signal<{ title: string; value: string }[]>([]);

  async ngOnInit() {
    await this.fetchAddressData();
  }

  async fetchAddressData() {
    try {
      const { results } = await this.api.getBindAddressList();
      this.addressFilterOptions.set(
        (results || []).map((item: any) => ({
          title: item.name,
          value: item.name,
        }))
      );
    } catch (error: any) {
      console.error(error);
    }
  }

  queryMail() {
    this.addressFilter = this.addressFilter?.trim() || '';
  }

  fetchMailData = async (limit: number, offset: number) => {
    return await this.api.getUserMails(limit, offset, this.addressFilter || undefined);
  };
}

// frontend/src/views/user/UserMailBox.vue
<script setup>
import { onMounted, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n'

import { api } from '../../api'
import MailBox from '../../components/MailBox.vue';

const { t } = useI18n({
    messages: {
        en: {
            addressQueryTip: 'Leave blank to query all addresses',
            query: 'Query',
        },
        zh: {
            addressQueryTip: '留空查询所有地址',
            query: '查询',
        }
    }
});

const mailBoxKey = ref("")
const addressFilter = ref();
const addressFilterOptions = ref([]);

const queryMail = () => {
    addressFilter.value = addressFilter.value ? addressFilter.value.trim() : addressFilter.value;
    mailBoxKey.value = Date.now();
}

const fetchMailData = async (limit, offset) => {
    return await api.fetch(
        `/user_api/mails`
        + `?limit=${limit}`
        + `&offset=${offset}`
        + (addressFilter.value ? `&address=${addressFilter.value}` : '')
    );
}

const fetchAddresData = async () => {
    try {
        const { results } = await api.fetch(`/user_api/bind_address`);
        addressFilterOptions.value = results.map((item) => ({
            title: item.name,
            value: item.name
        }));
    } catch (error) {
        console.log(error)
    }
}

const deleteMail = async (curMailId) => {
    await api.fetch(`/user_api/mails/${curMailId}`, { method: 'DELETE' });
};

watch(addressFilter, async () => {
    queryMail();
});

onMounted(() => {
    fetchAddresData();
});
</script>

<template>
    <div class="mt-3">
        <div class="d-flex ga-2 mb-3">
            <v-select v-model="addressFilter" :items="addressFilterOptions" clearable :label="t('addressQueryTip')"
                variant="outlined" density="compact" style="max-width: 300px;" hide-details />
            <v-btn @click="queryMail" color="primary" variant="outlined">
                {{ t('query') }}
            </v-btn>
        </div>
        <MailBox :key="mailBoxKey" :enableUserDeleteEmail="true" :fetchMailData="fetchMailData"
            :deleteMail="deleteMail" :showFilterInput="true" />
    </div>
</template>
