// frontend-angular/src/app/views/common/login/login.component.ts
import { Component, inject, OnInit, signal, computed, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatTabsModule } from '@angular/material/tabs';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatChipsModule } from '@angular/material/chips';
import { MatIconModule } from '@angular/material/icon';
import { GlobalStateService } from '../../../services/global-state.service';
import { ApiService } from '../../../services/api.service';
import { SnackbarService } from '../../../services/snackbar.service';
import { hashPassword } from '../../../utils';
import { AdminContactComponent } from '../admin-contact/admin-contact.component';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatCardModule,
    MatTabsModule,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatChipsModule,
    MatIconModule,
    AdminContactComponent,
  ],
  template: `
    <div class="login-container">
      @if (state.userSettings().user_email) {
        <div class="info-alert mb-3">
          <mat-icon>info</mat-icon>
          <span>已登录用户, 登录未绑定邮箱或创建新邮箱地址将绑定到当前用户</span>
        </div>
      }

      @if (state.openSettings().fetched) {
        <mat-tab-group [(selectedIndex)]="selectedTab" color="primary">
          <mat-tab [label]="loginAndBindTag()"></mat-tab>
          @if (showNewAddressTab()) {
            <mat-tab label="创建新邮箱"></mat-tab>
          }
          <mat-tab label="帮助"></mat-tab>
        </mat-tab-group>

        <div class="tab-content">
          @if (selectedTab === 0) {
            <!-- 登录 -->
            @if (loginMethod === 'password') {
              <mat-form-field appearance="outline" class="full-width mb-2">
                <mat-label>邮箱</mat-label>
                <input matInput [(ngModel)]="loginAddress" type="email">
              </mat-form-field>
              <mat-form-field appearance="outline" class="full-width mb-2">
                <mat-label>密码</mat-label>
                <input matInput [(ngModel)]="loginPassword" type="password">
              </mat-form-field>
            } @else {
              <mat-form-field appearance="outline" class="full-width mb-2">
                <mat-label>邮箱地址凭据</mat-label>
                <textarea matInput [(ngModel)]="credential" rows="3"></textarea>
              </mat-form-field>
            }

            @if (state.openSettings().enableAddressPassword) {
              <div class="text-center mb-2">
                <button mat-button color="primary" (click)="toggleLoginMethod()">
                  {{ loginMethod === 'password' ? '凭据登录' : '密码登录' }}
                </button>
              </div>
            }

            <button mat-stroked-button color="primary" class="full-width mb-2" (click)="login()">
              <mat-icon>email</mat-icon>
              {{ loginAndBindTag() }}
            </button>

            @if (showNewAddressTab()) {
              <button mat-stroked-button class="full-width" (click)="selectedTab = 1">
                <mat-icon>add</mat-icon>
                创建新邮箱
              </button>
            }
          } @else if (selectedTab === 1 && showNewAddressTab()) {
            <!-- 创建新邮箱 -->
            @if (!state.openSettings().disableCustomAddressName) {
              <p class="mb-2">请输入你想要使用的邮箱地址, 只允许: {{ addressRegex().source }}</p>
              <p class="mb-2">留空将会生成一个随机的邮箱地址。</p>
            }
            <p class="mb-3">你可以从下拉列表中选择一个域名。</p>

            @if (!state.openSettings().disableCustomAddressName) {
              <button mat-button color="primary" class="mb-3" (click)="generateName()">
                <mat-icon>refresh</mat-icon>
                生成随机名字
              </button>
            }

            <div class="email-row">
              @if (addressPrefix()) {
                <mat-chip>{{ addressPrefix() }}</mat-chip>
              }
              @if (!state.openSettings().disableCustomAddressName) {
                <mat-form-field appearance="outline" class="flex-1">
                  <input matInput [(ngModel)]="emailName" 
                         [maxlength]="state.openSettings().maxAddressLen">
                  <mat-hint>{{ emailName.length }}/{{ state.openSettings().maxAddressLen }}</mat-hint>
                </mat-form-field>
              } @else {
                <mat-form-field appearance="outline" class="flex-1">
                  <input matInput value="自动生成名称" disabled>
                </mat-form-field>
              }
              <mat-chip>&#64;</mat-chip>
              <mat-form-field appearance="outline" class="flex-1">
                <mat-select [(ngModel)]="emailDomain">
                  @for (domain of domainsOptions(); track domain.value) {
                    <mat-option [value]="domain.value">{{ domain.label }}</mat-option>
                  }
                </mat-select>
              </mat-form-field>
            </div>

            <button mat-stroked-button color="primary" class="full-width mt-3" (click)="newEmail()">
              <mat-icon>add</mat-icon>
              创建新邮箱
            </button>
          } @else {
            <!-- 帮助 -->
            <div class="info-alert mb-3">
              <mat-icon>info</mat-icon>
              <span>请"登录"或点击 "注册新邮箱" 按钮来获取一个新的邮箱地址</span>
            </div>
            <app-admin-contact></app-admin-contact>
          }
        </div>
      }
    </div>
  `,
  styles: [`
    .login-container {
      max-width: 600px;
      width: 100%;
    }
    .tab-content {
      padding: 16px 0;
    }
    .full-width {
      width: 100%;
    }
    .mb-2 {
      margin-bottom: 8px;
    }
    .mb-3 {
      margin-bottom: 12px;
    }
    .mt-3 {
      margin-top: 12px;
    }
    .text-center {
      text-align: center;
    }
    .info-alert {
      display: flex;
      align-items: flex-start;
      gap: 8px;
      padding: 12px 16px;
      background-color: #e3f2fd;
      border-radius: 4px;
      color: #1976d2;
    }
    .info-alert mat-icon {
      flex-shrink: 0;
    }
    .email-row {
      display: flex;
      align-items: center;
      gap: 8px;
      flex-wrap: wrap;
    }
    .flex-1 {
      flex: 1;
      min-width: 120px;
    }
    :host-context(.dark-theme) .info-alert {
      background-color: #1e3a5f;
      color: #90caf9;
    }
  `]
})
export class LoginComponent implements OnInit {
  @Input() bindUserAddress: () => Promise<void> = async () => {
    await this.api.bindUserAddress();
  };

  state = inject(GlobalStateService);
  private api = inject(ApiService);
  private snackbar = inject(SnackbarService);
  private router = inject(Router);

  selectedTab = 0;
  loginMethod = 'credential';
  credential = '';
  loginAddress = '';
  loginPassword = '';
  emailName = '';
  emailDomain = '';
  cfToken = '';

  loginAndBindTag = computed(() => {
    return this.state.userSettings().user_email ? '登录并绑定' : '登录';
  });

  addressRegex = computed(() => {
    try {
      if (this.state.openSettings().addressRegex) {
        return new RegExp(this.state.openSettings().addressRegex, 'g');
      }
    } catch (error) {
      console.error(error);
    }
    return /[^a-z0-9]/g;
  });

  addressPrefix = computed(() => {
    if (this.state.userSettings().user_role) {
      return this.state.userSettings().user_role?.prefix || '';
    }
    return this.state.openSettings().prefix;
  });

  domainsOptions = computed(() => {
    const userRole = this.state.userSettings().user_role;
    if (userRole) {
      const allDomains = userRole.domains;
      if (!allDomains) return this.state.openSettings().domains;
      return this.state.openSettings().domains.filter(domain => allDomains.includes(domain.value));
    }
    const defaultDomains = this.state.openSettings().defaultDomains;
    if (!defaultDomains || defaultDomains.length === 0) {
      return this.state.openSettings().domains;
    }
    return this.state.openSettings().domains.filter(domain => defaultDomains.includes(domain.value));
  });

  showNewAddressTab = computed(() => {
    if (this.state.openSettings().disableAnonymousUserCreateEmail && !this.state.userSettings().user_email) {
      return false;
    }
    return this.state.openSettings().enableUserCreateEmail;
  });

  async ngOnInit() {
    if (!this.state.openSettings().domains || this.state.openSettings().domains.length === 0) {
      await this.api.getOpenSettings();
    }
    const domains = this.domainsOptions();
    this.emailDomain = domains.length > 0 ? domains[0].value : '';
    this.initLoginMethod();
  }

  initLoginMethod() {
    if (this.state.openSettings().enableAddressPassword) {
      this.loginMethod = 'password';
    } else {
      this.loginMethod = 'credential';
    }
  }

  toggleLoginMethod() {
    this.loginMethod = this.loginMethod === 'password' ? 'credential' : 'password';
  }

  async login() {
    if (this.loginMethod === 'password') {
      if (!this.loginAddress || !this.loginPassword) {
        this.snackbar.error('邮箱和密码不能为空');
        return;
      }
      try {
        const hashedPassword = await hashPassword(this.loginPassword);
        const res = await this.api.addressLogin(this.loginAddress, hashedPassword);
        this.state.setJwt(res.jwt);
        await this.api.getSettings();
        try {
          await this.bindUserAddress();
        } catch (error: any) {
          this.snackbar.error(`绑定邮箱地址到用户时错误: ${error.message}`);
        }
        await this.router.navigate(['/']);
      } catch (error: any) {
        this.snackbar.error(error.message || 'error');
      }
      return;
    }

    if (!this.credential) {
      this.snackbar.error('请输入邮箱地址凭据');
      return;
    }
    try {
      this.state.setJwt(this.credential);
      await this.api.getSettings();
      try {
        await this.bindUserAddress();
      } catch (error: any) {
        this.snackbar.error(`绑定邮箱地址到用户时错误: ${error.message}`);
      }
      await this.router.navigate(['/']);
    } catch (error: any) {
      this.snackbar.error(error.message || 'error');
    }
  }

  async generateName() {
    try {
      const { faker } = await import('@faker-js/faker');
      let name = faker.internet.email()
        .split('@')[0]
        .replace(/\s+/g, '.')
        .replace(/\.{2,}/g, '.')
        .replace(this.addressRegex(), '')
        .toLowerCase();
      if (name.length > this.state.openSettings().maxAddressLen) {
        name = name.slice(0, this.state.openSettings().maxAddressLen);
      }
      this.emailName = name;
    } catch (error: any) {
      this.snackbar.error(error.message || 'error');
    }
  }

  async newEmail() {
    try {
      const nameToSend = this.state.openSettings().disableCustomAddressName ? '' : this.emailName;
      const res = await this.api.newAddress(nameToSend, this.emailDomain, this.cfToken);
      this.state.setJwt(res.jwt);
      this.state.setAddressPassword(res.password || '');
      await this.api.getSettings();
      await this.router.navigate(['/']);
      this.state.showAddressCredential.set(true);
      try {
        await this.bindUserAddress();
      } catch (error: any) {
        this.snackbar.error(`绑定邮箱地址到用户时错误: ${error.message}`);
      }
    } catch (error: any) {
      this.snackbar.error(error.message || 'error');
    }
  }
}

// frontend/src/views/common/Login.vue
<script setup>
import { ref, onMounted, computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRouter } from 'vue-router'

import AdminContact from '../common/AdminContact.vue'
import Turnstile from '../../components/Turnstile.vue'
import M3LoadingIndicator from '../../components/M3LoadingIndicator.vue'

import { useGlobalState } from '../../store'
import { api } from '../../api'
import { getRouterPathWithLang, hashPassword } from '../../utils'

const props = defineProps({
    bindUserAddress: {
        type: Function,
        default: async () => { await api.bindUserAddress(); },
        required: true
    },
    newAddressPath: {
        type: Function,
        default: async (address_name, domain, cf_token) => {
            return await api.fetch("/api/new_address", {
                method: "POST",
                body: JSON.stringify({
                    name: address_name,
                    domain: domain,
                    cf_token: cf_token,
                }),
            });
        },
        required: true
    },
})

const router = useRouter()

const snackbar = ref(false)
const snackbarText = ref('')
const snackbarColor = ref('info')

const showMessage = (text, color = 'info') => {
    snackbarText.value = text
    snackbarColor.value = color
    snackbar.value = true
}

const message = {
    error: (text) => showMessage(text, 'error'),
    info: (text) => showMessage(text, 'info'),
    success: (text) => showMessage(text, 'success'),
}

const notification = {
    info: () => {}
}

const {
    jwt, loading, openSettings,
    showAddressCredential, userSettings, addressPassword
} = useGlobalState()

const tabValue = ref('signin')
const credential = ref('')
const emailName = ref("")
const emailDomain = ref("")
const cfToken = ref("")
const loginMethod = ref('credential')
const loginAddress = ref('')
const loginPassword = ref('')

const initLoginMethod = () => {
    if (openSettings.value?.enableAddressPassword) {
        loginMethod.value = 'password';
    } else {
        loginMethod.value = 'credential';
    }
}

const login = async () => {
    if (loginMethod.value === 'password') {
        if (!loginAddress.value || !loginPassword.value) {
            message.error(t('emailPasswordRequired'));
            return;
        }
        try {
            const res = await api.fetch('/api/address_login', {
                method: 'POST',
                body: JSON.stringify({
                    email: loginAddress.value,
                    password: await hashPassword(loginPassword.value)
                })
            });
            jwt.value = res.jwt;
            await api.getSettings();
            try {
                await props.bindUserAddress();
            } catch (error) {
                message.error(`${t('bindUserAddressError')}: ${error.message}`);
            }
            await router.push(getRouterPathWithLang("/", locale.value));
        } catch (error) {
            message.error(error.message || "error");
        }
        return;
    }
    if (!credential.value) {
        message.error(t('credentialInput'));
        return;
    }
    try {
        jwt.value = credential.value;
        await api.getSettings();
        try {
            await props.bindUserAddress();
        } catch (error) {
            message.error(`${t('bindUserAddressError')}: ${error.message}`);
        }
        await router.push(getRouterPathWithLang("/", locale.value));
    } catch (error) {
        message.error(error.message || "error");
    }
}

const { locale, t } = useI18n({
    messages: {
        en: {
            login: 'Login',
            loginAndBind: 'Login and Bind',
            pleaseGetNewEmail: 'Please login or click "Get New Email" button to get a new email address',
            getNewEmail: 'Create New Email',
            getNewEmailTip1: 'Please input the email you want to use. only allow: ',
            getNewEmailTip2: 'Levaing it blank will generate a random email address.',
            getNewEmailTip3: 'You can choose a domain from the dropdown list.',
            credential: 'Email Address Credential',
            ok: 'OK',
            generateName: 'Generate Fake Name',
            help: 'Help',
            credentialInput: 'Please input the Mail Address Credential',
            bindUserInfo: 'Logged in user, login without binding email or create new email address will bind to current user',
            bindUserAddressError: 'Error when bind email address to user',
            autoGeneratedName: 'Auto-generated name',
            passwordLogin: 'Password Login',
            credentialLogin: 'Credential Login',
            email: 'Email',
            password: 'Password',
            emailPasswordRequired: 'Email and password are required',
        },
        zh: {
            login: '登录',
            loginAndBind: '登录并绑定',
            pleaseGetNewEmail: '请"登录"或点击 "注册新邮箱" 按钮来获取一个新的邮箱地址',
            getNewEmail: '创建新邮箱',
            getNewEmailTip1: '请输入你想要使用的邮箱地址, 只允许: ',
            getNewEmailTip2: '留空将会生成一个随机的邮箱地址。',
            getNewEmailTip3: '你可以从下拉列表中选择一个域名。',
            credential: '邮箱地址凭据',
            ok: '确定',
            generateName: '生成随机名字',
            help: '帮助',
            credentialInput: '请输入邮箱地址凭据',
            bindUserInfo: '已登录用户, 登录未绑定邮箱或创建新邮箱地址将绑定到当前用户',
            bindUserAddressError: '绑定邮箱地址到用户时错误',
            autoGeneratedName: '自动生成名称',
            passwordLogin: '密码登录',
            credentialLogin: '凭据登录',
            email: '邮箱',
            password: '密码',
            emailPasswordRequired: '邮箱和密码不能为空',
        }
    }
});

const loginAndBindTag = computed(() => {
    if (userSettings.value.user_email) {
        return t('loginAndBind')
    }
    return t('login')
})

const addressRegex = computed(() => {
    try {
        if (openSettings.value.addressRegex) {
            return new RegExp(openSettings.value.addressRegex, 'g');
        }
    } catch (error) {
        console.error(error);
        message.error(`Invalid addressRegex: ${openSettings.value.addressRegex}`);
    }
    return /[^a-z0-9]/g;
});

const generateNameLoading = ref(false);
const generateName = async () => {
    try {
        generateNameLoading.value = true;
        const { faker } = await import('https://esm.sh/@faker-js/faker');
        emailName.value = faker.internet.email()
            .split('@')[0]
            .replace(/\s+/g, '.')
            .replace(/\.{2,}/g, '.')
            .replace(addressRegex.value, '')
            .toLowerCase();
        if (emailName.value.length > openSettings.value.maxAddressLen) {
            emailName.value = emailName.value.slice(0, openSettings.value.maxAddressLen);
        }
    } catch (error) {
        message.error(error.message || "error");
    } finally {
        generateNameLoading.value = false;
    }
};

const newEmail = async () => {
    try {
        const nameToSend = openSettings.value.disableCustomAddressName ? "" : emailName.value;
        const res = await props.newAddressPath(
            nameToSend,
            emailDomain.value,
            cfToken.value
        );
        jwt.value = res["jwt"];
        addressPassword.value = res["password"] || '';
        await api.getSettings();
        await router.push(getRouterPathWithLang("/", locale.value));
        showAddressCredential.value = true;
        try {
            await props.bindUserAddress();
        } catch (error) {
            message.error(`${t('bindUserAddressError')}: ${error.message}`);
        }
    } catch (error) {
        message.error(error.message || "error");
    }
};

const addressPrefix = computed(() => {
    if (userSettings.value?.user_role) {
        return userSettings.value.user_role.prefix || "";
    }
    return openSettings.value.prefix;
});

const domainsOptions = computed(() => {
    if (userSettings.value.user_role) {
        const allDomains = userSettings.value.user_role.domains;
        if (!allDomains) return openSettings.value.domains;
        return openSettings.value.domains.filter((domain) => {
            return allDomains.includes(domain.value);
        });
    }
    if (!openSettings.value.defaultDomains) {
        return openSettings.value.domains;
    }
    return openSettings.value.domains.filter((domain) => {
        return openSettings.value.defaultDomains.includes(domain.value);
    });
});

const showNewAddressTab = computed(() => {
    if (openSettings.value.disableAnonymousUserCreateEmail
        && !userSettings.value.user_email
    ) {
        return false;
    }
    return openSettings.value.enableUserCreateEmail;
});

onMounted(async () => {
    if (!openSettings.value.domains || openSettings.value.domains.length === 0) {
        await api.getOpenSettings(message, notification);
    }
    emailDomain.value = domainsOptions.value ? domainsOptions.value[0]?.value : "";
    initLoginMethod();
});
</script>

<template>
    <div class="d-flex justify-center">
        <div style="max-width: 600px; width: 100%;">
        <v-alert v-if="userSettings.user_email" type="info" variant="tonal" closable class="mb-4">
            {{ t('bindUserInfo') }}
        </v-alert>

        <v-tabs v-if="openSettings.fetched" v-model="tabValue" grow>
            <v-tab value="signin">{{ loginAndBindTag }}</v-tab>
            <v-tab v-if="showNewAddressTab" value="register">{{ t('getNewEmail') }}</v-tab>
            <v-tab value="help">{{ t('help') }}</v-tab>
        </v-tabs>

        <v-window v-model="tabValue" class="mt-4">
            <v-window-item value="signin" class="tab-content">
                <v-form>
                    <div v-if="loginMethod === 'password'">
                        <v-text-field v-model="loginAddress" :label="t('email')" variant="outlined" 
                            density="compact" class="mb-2"></v-text-field>
                        <v-text-field v-model="loginPassword" :label="t('password')" type="password"
                            variant="outlined" density="compact" 
                            :append-inner-icon="'mdi-eye'" class="mb-2"></v-text-field>
                    </div>
                    <div v-else>
                        <v-textarea v-model="credential" :label="t('credential')" variant="outlined"
                            rows="3" auto-grow class="mt-4 mb-2 no-resize-textarea"></v-textarea>
                    </div>

                    <div class="text-center mb-2">
                        <v-btn v-if="openSettings?.enableAddressPassword" variant="text" size="small" color="info"
                            @click="loginMethod === 'password' ? loginMethod = 'credential' : loginMethod = 'password'">
                            {{ loginMethod === 'password' ? t('credentialLogin') : t('passwordLogin') }}
                        </v-btn>
                    </div>

                    <v-btn @click="login" :loading="loading" color="primary" variant="outlined" block class="mb-2">
                        <v-icon start>mdi-email</v-icon>
                        {{ loginAndBindTag }}
                    </v-btn>
                    <v-btn v-if="showNewAddressTab" @click="tabValue = 'register'" variant="outlined" block>
                        <v-icon start>mdi-plus</v-icon>
                        {{ t('getNewEmail') }}
                    </v-btn>
                </v-form>
            </v-window-item>

            <v-window-item v-if="showNewAddressTab" value="register" class="tab-content">
                <v-overlay :model-value="generateNameLoading" class="align-center justify-center">
                    <M3LoadingIndicator />
                </v-overlay>
                <v-form>
                    <p v-if="!openSettings.disableCustomAddressName" class="mb-2">
                        {{ t("getNewEmailTip1") + addressRegex.source }}
                    </p>
                    <p v-if="!openSettings.disableCustomAddressName" class="mb-2">{{ t("getNewEmailTip2") }}</p>
                    <p class="mb-4">{{ t("getNewEmailTip3") }}</p>

                    <v-btn v-if="!openSettings.disableCustomAddressName" @click="generateName" 
                        variant="text" color="primary" class="mb-4" prepend-icon="mdi-refresh">
                        {{ t('generateName') }}
                    </v-btn>

                    <v-row dense>
                        <v-col v-if="addressPrefix" cols="auto">
                            <v-chip>{{ addressPrefix }}</v-chip>
                        </v-col>
                        <v-col>
                            <v-text-field v-if="!openSettings.disableCustomAddressName" v-model="emailName"
                                variant="outlined" density="compact" counter
                                :maxlength="openSettings.maxAddressLen"></v-text-field>
                            <v-text-field v-else :model-value="t('autoGeneratedName')" disabled
                                variant="outlined" density="compact"></v-text-field>
                        </v-col>
                        <v-col cols="auto">
                            <v-chip>@</v-chip>
                        </v-col>
                        <v-col>
                            <v-select v-model="emailDomain" :items="domainsOptions" item-title="label"
                                item-value="value" variant="outlined" density="compact"></v-select>
                        </v-col>
                    </v-row>

                    <Turnstile v-model:value="cfToken" />

                    <v-btn color="primary" variant="outlined" block @click="newEmail" :loading="loading" class="mt-4">
                        <v-icon start>mdi-plus</v-icon>
                        {{ t('getNewEmail') }}
                    </v-btn>
                </v-form>
            </v-window-item>

            <v-window-item value="help" class="tab-content">
                <v-alert type="info" variant="tonal" class="mt-4 mb-4">
                    {{ t('pleaseGetNewEmail') }}
                </v-alert>
                <AdminContact />
            </v-window-item>
        </v-window>

        <v-snackbar v-model="snackbar" :color="snackbarColor" timeout="3000">
            {{ snackbarText }}
        </v-snackbar>
        </div>
    </div>
</template>


<style scoped>
.no-resize-textarea :deep(textarea) {
    resize: none;
}
/* v-window 保持 hidden 确保切换动画正常，加 padding 防止按钮被裁剪 */
.v-window {
    overflow: hidden !important;
    padding: 4px !important;
}
/* v-window-item 内容加 padding 防止按钮动画被裁剪 */
.v-window-item {
    padding: 4px !important;
}
</style>
