// frontend-angular/src/app/pages/admin/admin.component.ts
import { Component, inject, OnInit, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatTabsModule } from '@angular/material/tabs';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatDialogModule, MatDialog, MatDialogRef } from '@angular/material/dialog';
import { TranslateModule } from '@ngx-translate/core';
import { GlobalStateService } from '../../services/global-state.service';
import { ApiService } from '../../services/api.service';
import { AdminAccountComponent } from '../../views/admin/account/account.component';
import { AdminMailsComponent } from '../../views/admin/mails/mails.component';
import { AdminStatisticsComponent } from '../../views/admin/statistics/statistics.component';
import { AppearanceComponent } from '../../views/common/appearance/appearance.component';
import { AboutComponent } from '../../views/common/about/about.component';
import { CreateAccountComponent } from '../../views/admin/create-account/create-account.component';
import { AdminAccountSettingsComponent } from '../../views/admin/account-settings/account-settings.component';
import { UserManagementComponent } from '../../views/admin/user-management/user-management.component';
import { AdminUserSettingsComponent } from '../../views/admin/user-settings/user-settings.component';
import { MailsUnknowComponent } from '../../views/admin/mails-unknow/mails-unknow.component';
import { AdminSendboxComponent } from '../../views/admin/sendbox/sendbox.component';
import { AdminSendMailComponent } from '../../views/admin/send-mail/send-mail.component';
import { MailWebhookComponent } from '../../views/admin/mail-webhook/mail-webhook.component';
import { AdminTelegramComponent } from '../../views/admin/telegram/telegram.component';
import { MaintenanceComponent } from '../../views/admin/maintenance/maintenance.component';
import { DatabaseManagerComponent } from '../../views/admin/database-manager/database-manager.component';
import { WorkerConfigComponent } from '../../views/admin/worker-config/worker-config.component';
import { IpBlacklistSettingsComponent } from '../../views/admin/ip-blacklist-settings/ip-blacklist-settings.component';
import { AiExtractSettingsComponent } from '../../views/admin/ai-extract-settings/ai-extract-settings.component';
import { SenderAccessComponent } from '../../views/admin/sender-access/sender-access.component';
import { AdminUserOauth2SettingsComponent } from '../../views/admin/user-oauth2-settings/user-oauth2-settings.component';
import { AdminRoleAddressConfigComponent } from '../../views/admin/role-address-config/role-address-config.component';
import { AdminWebhookSettingsComponent } from '../../views/admin/webhook-settings/webhook-settings.component';

@Component({
  selector: 'app-admin',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatCardModule,
    MatTabsModule,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatIconModule,
    MatProgressSpinnerModule,
    TranslateModule,
    MatDialogModule,
    AdminAccountComponent,
    AdminMailsComponent,
    AdminStatisticsComponent,
    AppearanceComponent,
    AboutComponent,
    CreateAccountComponent,
    AdminAccountSettingsComponent,
    UserManagementComponent,
    AdminUserSettingsComponent,
    MailsUnknowComponent,
    AdminSendboxComponent,
    AdminSendMailComponent,
    MailWebhookComponent,
    AdminTelegramComponent,
    MaintenanceComponent,
    DatabaseManagerComponent,
    WorkerConfigComponent,
    IpBlacklistSettingsComponent,
    AiExtractSettingsComponent,
    SenderAccessComponent,
    AdminUserOauth2SettingsComponent,
    AdminRoleAddressConfigComponent,
    AdminWebhookSettingsComponent,
  ],
  template: `
    @if (state.openSettings().fetched) {
        <div class="admin-container">
          <!-- Main Tabs -->
          <mat-tab-group [(selectedIndex)]="mainTab" color="primary" animationDuration="0ms">
            <!-- 快速设置 -->
            <mat-tab [label]="'quickSetup' | translate">
              <div class="tab-content">
                <mat-tab-group [(selectedIndex)]="quickSetupTab" color="primary">
                  <mat-tab [label]="'accountSettings' | translate">
                    <div class="sub-tab-content">
                      <app-admin-account-settings></app-admin-account-settings>
                    </div>
                  </mat-tab>
                  <mat-tab [label]="'userSettings' | translate">
                    <div class="sub-tab-content">
                      <app-admin-user-settings></app-admin-user-settings>
                    </div>
                  </mat-tab>
                </mat-tab-group>
              </div>
            </mat-tab>

            <!-- 账号 -->
            <mat-tab [label]="'account' | translate">
              <div class="tab-content">
                <mat-tab-group [(selectedIndex)]="accountTab" color="primary">
                  <mat-tab [label]="'accountList' | translate">
                    <div class="sub-tab-content">
                      <app-admin-account></app-admin-account>
                    </div>
                  </mat-tab>
                  <mat-tab [label]="'createAccount' | translate">
                    <div class="sub-tab-content">
                      <app-create-account></app-create-account>
                    </div>
                  </mat-tab>
                  <mat-tab [label]="'senderAccess' | translate">
                    <div class="sub-tab-content">
                      <app-sender-access></app-sender-access>
                    </div>
                  </mat-tab>
                </mat-tab-group>
              </div>
            </mat-tab>

            <!-- 用户 -->
            <mat-tab [label]="'user' | translate">
              <div class="tab-content">
                <mat-tab-group [(selectedIndex)]="userTab" color="primary">
                  <mat-tab [label]="'userManagement' | translate">
                    <div class="sub-tab-content">
                      <app-user-management></app-user-management>
                    </div>
                  </mat-tab>
                  <mat-tab [label]="'userSettings' | translate">
                    <div class="sub-tab-content">
                      <app-admin-user-settings></app-admin-user-settings>
                    </div>
                  </mat-tab>
                  <mat-tab [label]="'oauth2Settings' | translate">
                    <div class="sub-tab-content">
                      <app-admin-user-oauth2-settings></app-admin-user-oauth2-settings>
                    </div>
                  </mat-tab>
                  <mat-tab [label]="'roleAddressConfig' | translate">
                    <div class="sub-tab-content">
                      <app-admin-role-address-config></app-admin-role-address-config>
                    </div>
                  </mat-tab>
                </mat-tab-group>
              </div>
            </mat-tab>

            <!-- 邮件 -->
            <mat-tab [label]="'mails' | translate">
              <div class="tab-content">
                <mat-tab-group [(selectedIndex)]="mailsTab" color="primary">
                  <mat-tab [label]="'mailList' | translate">
                    <div class="sub-tab-content">
                      <app-admin-mails></app-admin-mails>
                    </div>
                  </mat-tab>
                  <mat-tab [label]="'unknownMails' | translate">
                    <div class="sub-tab-content">
                      <app-mails-unknow></app-mails-unknow>
                    </div>
                  </mat-tab>
                  <mat-tab [label]="'sendbox' | translate">
                    <div class="sub-tab-content">
                      <app-admin-sendbox></app-admin-sendbox>
                    </div>
                  </mat-tab>
                  <mat-tab [label]="'sendMail' | translate">
                    <div class="sub-tab-content">
                      <app-admin-send-mail></app-admin-send-mail>
                    </div>
                  </mat-tab>
                  <mat-tab [label]="'mailWebhook' | translate">
                    <div class="sub-tab-content">
                      <app-mail-webhook></app-mail-webhook>
                    </div>
                  </mat-tab>
                  <mat-tab label="Telegram">
                    <div class="sub-tab-content">
                      <app-admin-telegram></app-admin-telegram>
                    </div>
                  </mat-tab>
                </mat-tab-group>
              </div>
            </mat-tab>

            <!-- 统计 -->
            <mat-tab [label]="'statistics' | translate">
              <div class="tab-content">
                <app-admin-statistics></app-admin-statistics>
              </div>
            </mat-tab>

            <!-- 维护 -->
            <mat-tab [label]="'maintenance' | translate">
              <div class="tab-content">
                <mat-tab-group [(selectedIndex)]="maintenanceTab" color="primary">
                  <mat-tab [label]="'database' | translate">
                    <div class="sub-tab-content">
                      <app-database-manager></app-database-manager>
                    </div>
                  </mat-tab>
                  <mat-tab [label]="'cleanup' | translate">
                    <div class="sub-tab-content">
                      <app-maintenance></app-maintenance>
                    </div>
                  </mat-tab>
                  <mat-tab [label]="'workerConfig' | translate">
                    <div class="sub-tab-content">
                      <app-worker-config></app-worker-config>
                    </div>
                  </mat-tab>
                  <mat-tab [label]="'ipBlacklist' | translate">
                    <div class="sub-tab-content">
                      <app-ip-blacklist-settings></app-ip-blacklist-settings>
                    </div>
                  </mat-tab>
                  <mat-tab [label]="'aiExtract' | translate">
                    <div class="sub-tab-content">
                      <app-ai-extract-settings></app-ai-extract-settings>
                    </div>
                  </mat-tab>
                  <mat-tab label="Webhook">
                    <div class="sub-tab-content">
                      <app-admin-webhook-settings></app-admin-webhook-settings>
                    </div>
                  </mat-tab>
                </mat-tab-group>
              </div>
            </mat-tab>

            <!-- 外观 -->
            <mat-tab [label]="'appearance' | translate">
              <div class="tab-content">
                <app-appearance [showUseSimpleIndex]="true"></app-appearance>
              </div>
            </mat-tab>

            <!-- 关于 -->
            <mat-tab [label]="'about' | translate">
              <div class="tab-content">
                <app-about></app-about>
              </div>
            </mat-tab>
          </mat-tab-group>
        </div>
    } @else {
      <div class="loading-container">
        <mat-spinner diameter="40"></mat-spinner>
      </div>
    }
  `,
  styles: [`
    .admin-container { padding: 16px; }
    .tab-content { padding: 16px; }
    .sub-tab-content { padding: 16px 0; }
    .loading-container { display: flex; justify-content: center; padding: 48px; }
  `]
})
export class AdminComponent implements OnInit {
  state = inject(GlobalStateService);
  private api = inject(ApiService);
  private dialog = inject(MatDialog);

  mainTab = 0;
  quickSetupTab = 0;
  accountTab = 0;
  userTab = 0;
  mailsTab = 0;
  maintenanceTab = 0;

  showAdminPasswordModal = computed(() => {
    const hasAdminAuth = !!this.state.adminAuth();
    const isAdmin = this.state.userSettings().is_admin;
    const disableCheck = this.state.openSettings().disableAdminPasswordCheck;
    if (hasAdminAuth || isAdmin || disableCheck) return false;
    return true;
  });

  async ngOnInit() {
    if (!this.state.openSettings().fetched) {
      await this.api.getOpenSettings();
    }
    if (!this.state.userSettings().user_id) {
      await this.api.getUserSettings();
    }
    // 检查是否需要显示密码对话框
    if (this.showAdminPasswordModal()) {
      this.openAdminPasswordDialog();
    }
  }

  openAdminPasswordDialog() {
    const dialogRef = this.dialog.open(AdminPasswordDialogComponent, {
      width: '400px',
      disableClose: true
    });
    dialogRef.afterClosed().subscribe(password => {
      if (password) {
        this.state.setAdminAuth(password);
        location.reload();
      }
    });
  }
}

// Admin Password Dialog
@Component({
  selector: 'app-admin-password-dialog',
  standalone: true,
  imports: [CommonModule, FormsModule, MatDialogModule, MatButtonModule, MatFormFieldModule, MatInputModule, MatIconModule, TranslateModule],
  template: `
    <h2 mat-dialog-title>{{ 'adminPassword' | translate }}</h2>
    <mat-dialog-content>
      <p class="mb-3">{{ 'enterAdminPassword' | translate }}</p>
      <mat-form-field appearance="outline" class="full-width">
        <mat-label>{{ 'password' | translate }}</mat-label>
        <input matInput [(ngModel)]="password" [type]="showPassword ? 'text' : 'password'" (keyup.enter)="submit()">
        <button mat-icon-button matSuffix (click)="showPassword = !showPassword" type="button">
          <mat-icon>{{ showPassword ? 'visibility_off' : 'visibility' }}</mat-icon>
        </button>
      </mat-form-field>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-raised-button color="primary" (click)="submit()">{{ 'confirm' | translate }}</button>
    </mat-dialog-actions>
  `,
  styles: [`.full-width { width: 100%; } .mb-3 { margin-bottom: 12px; }`]
})
export class AdminPasswordDialogComponent {
  private dialogRef = inject(MatDialogRef<AdminPasswordDialogComponent>);
  password = '';
  showPassword = false;

  submit() {
    this.dialogRef.close(this.password);
  }
}

// frontend/src/views/Admin.vue
<script setup>
import { computed, onMounted, ref, defineAsyncComponent } from 'vue';
import { useI18n } from 'vue-i18n'

import { useGlobalState } from '../store'
import { api } from '../api'

import SenderAccess from './admin/SenderAccess.vue'
import Statistics from "./admin/Statistics.vue"
import SendBox from './admin/SendBox.vue';
import Account from './admin/Account.vue';
import CreateAccount from './admin/CreateAccount.vue';
import AccountSettings from './admin/AccountSettings.vue';
import UserManagement from './admin/UserManagement.vue';
import UserSettings from './admin/UserSettings.vue';
import UserOauth2Settings from './admin/UserOauth2Settings.vue';
import RoleAddressConfig from './admin/RoleAddressConfig.vue';
import Mails from './admin/Mails.vue';
import MailsUnknow from './admin/MailsUnknow.vue';
import About from './common/About.vue';
import Maintenance from './admin/Maintenance.vue';
import DatabaseManager from './admin/DatabaseManager.vue';
import Appearance from './common/Appearance.vue';
import Telegram from './admin/Telegram.vue';
import Webhook from './admin/Webhook.vue';
import MailWebhook from './admin/MailWebhook.vue';
import WorkerConfig from './admin/WorkerConfig.vue';
import IpBlacklistSettings from './admin/IpBlacklistSettings.vue';
import AiExtractSettings from './admin/AiExtractSettings.vue';

const {
  adminAuth, showAdminAuth, adminTab, loading,
  globalTabplacement, showAdminPage, userSettings
} = useGlobalState()

const snackbar = ref({ show: false, text: '', color: 'error' })

const SendMail = defineAsyncComponent(() => {
  loading.value = true;
  return import('./admin/SendMail.vue')
    .finally(() => loading.value = false);
});

const authFunc = async () => {
  try {
    adminAuth.value = tmpAdminAuth.value;
    location.reload()
  } catch (error) {
    snackbar.value = { show: true, text: error.message || "error", color: 'error' }
  }
}

const { t } = useI18n({
  messages: {
    en: {
      accessHeader: 'Admin Password',
      accessTip: 'Please enter the admin password',
      mails: 'Emails',
      sendMail: 'Send Mail',
      qucickSetup: 'Quick Setup',
      account: 'Account',
      account_create: 'Create Account',
      account_settings: 'Account Settings',
      user: 'User',
      user_management: 'User Management',
      user_settings: 'User Settings',
      userOauth2Settings: 'Oauth2 Settings',
      roleAddressConfig: 'Role Address Config',
      unknow: 'Mails with unknow receiver',
      senderAccess: 'Sender Access Control',
      sendBox: 'Send Box',
      telegram: 'Telegram Bot',
      webhookSettings: 'Webhook Settings',
      statistics: 'Statistics',
      maintenance: 'Maintenance',
      database: 'Database',
      workerconfig: 'Worker Config',
      ipBlacklistSettings: 'IP Blacklist',
      aiExtractSettings: 'AI Extract Settings',
      appearance: 'Appearance',
      about: 'About',
      ok: 'OK',
      mailWebhook: 'Mail Webhook',
    },
    zh: {
      accessHeader: 'Admin 密码',
      accessTip: '请输入 Admin 密码',
      mails: '邮件',
      sendMail: '发送邮件',
      qucickSetup: '快速设置',
      account: '账号',
      account_create: '创建账号',
      account_settings: '账号设置',
      user: '用户',
      user_management: '用户管理',
      user_settings: '用户设置',
      userOauth2Settings: 'Oauth2 设置',
      roleAddressConfig: '角色地址配置',
      unknow: '无收件人邮件',
      senderAccess: '发件权限控制',
      sendBox: '发件箱',
      telegram: '电报机器人',
      webhookSettings: 'Webhook 设置',
      statistics: '统计',
      maintenance: '维护',
      database: '数据库',
      workerconfig: 'Worker 配置',
      ipBlacklistSettings: 'IP 黑名单',
      aiExtractSettings: 'AI 提取设置',
      appearance: '外观',
      about: '关于',
      ok: '确定',
      mailWebhook: '邮件 Webhook',
    }
  }
});

const showAdminPasswordModal = computed(() => !showAdminPage.value || showAdminAuth.value)
const tmpAdminAuth = ref('')
const showPassword = ref(false)

// Sub tabs
const quickSetupTab = ref('database')
const accountTab = ref('account')
const userTab = ref('user_management')
const mailsTab = ref('mails')
const maintenanceTab = ref('database')

onMounted(async () => {
  if (!userSettings.value.user_id) await api.getUserSettings(snackbar);
})
</script>

<template>
  <div v-if="userSettings.fetched">
    <v-dialog v-model="showAdminPasswordModal" persistent max-width="400">
      <v-card>
        <v-card-title>{{ t('accessHeader') }}</v-card-title>
        <v-card-text>
          <p class="mb-4">{{ t('accessTip') }}</p>
          <v-text-field v-model="tmpAdminAuth" :type="showPassword ? 'text' : 'password'" variant="outlined" density="compact"
            :append-inner-icon="showPassword ? 'mdi-eye-off' : 'mdi-eye'" @click:append-inner="showPassword = !showPassword" />
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn @click="authFunc" color="primary" :loading="loading">
            {{ t('ok') }}
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <v-tabs v-if="showAdminPage" v-model="adminTab" :direction="globalTabplacement === 'left' || globalTabplacement === 'right' ? 'vertical' : 'horizontal'"
      color="primary" align-tabs="center" class="mb-4">
      <v-tab value="qucickSetup">{{ t('qucickSetup') }}</v-tab>
      <v-tab value="account">{{ t('account') }}</v-tab>
      <v-tab value="user">{{ t('user') }}</v-tab>
      <v-tab value="mails">{{ t('mails') }}</v-tab>
      <v-tab value="telegram">{{ t('telegram') }}</v-tab>
      <v-tab value="statistics">{{ t('statistics') }}</v-tab>
      <v-tab value="maintenance">{{ t('maintenance') }}</v-tab>
      <v-tab value="appearance">{{ t('appearance') }}</v-tab>
      <v-tab value="about">{{ t('about') }}</v-tab>
    </v-tabs>

    <v-window v-if="showAdminPage" v-model="adminTab">
      <v-window-item value="qucickSetup">
        <v-tabs v-model="quickSetupTab" align-tabs="center" color="primary" class="mb-4">
          <v-tab value="database">{{ t('database') }}</v-tab>
          <v-tab value="account_settings">{{ t('account_settings') }}</v-tab>
          <v-tab value="user_settings">{{ t('user_settings') }}</v-tab>
          <v-tab value="workerconfig">{{ t('workerconfig') }}</v-tab>
        </v-tabs>
        <v-window v-model="quickSetupTab">
          <v-window-item value="database"><DatabaseManager /></v-window-item>
          <v-window-item value="account_settings"><AccountSettings /></v-window-item>
          <v-window-item value="user_settings"><UserSettings /></v-window-item>
          <v-window-item value="workerconfig"><WorkerConfig /></v-window-item>
        </v-window>
      </v-window-item>

      <v-window-item value="account">
        <v-tabs v-model="accountTab" align-tabs="center" color="primary" class="mb-4">
          <v-tab value="account">{{ t('account') }}</v-tab>
          <v-tab value="account_create">{{ t('account_create') }}</v-tab>
          <v-tab value="account_settings">{{ t('account_settings') }}</v-tab>
          <v-tab value="senderAccess">{{ t('senderAccess') }}</v-tab>
          <v-tab value="ipBlacklistSettings">{{ t('ipBlacklistSettings') }}</v-tab>
          <v-tab value="aiExtractSettings">{{ t('aiExtractSettings') }}</v-tab>
          <v-tab value="webhook">{{ t('webhookSettings') }}</v-tab>
        </v-tabs>
        <v-window v-model="accountTab">
          <v-window-item value="account"><Account /></v-window-item>
          <v-window-item value="account_create"><CreateAccount /></v-window-item>
          <v-window-item value="account_settings"><AccountSettings /></v-window-item>
          <v-window-item value="senderAccess"><SenderAccess /></v-window-item>
          <v-window-item value="ipBlacklistSettings"><IpBlacklistSettings /></v-window-item>
          <v-window-item value="aiExtractSettings"><AiExtractSettings /></v-window-item>
          <v-window-item value="webhook"><Webhook /></v-window-item>
        </v-window>
      </v-window-item>

      <v-window-item value="user">
        <v-tabs v-model="userTab" align-tabs="center" color="primary" class="mb-4">
          <v-tab value="user_management">{{ t('user_management') }}</v-tab>
          <v-tab value="user_settings">{{ t('user_settings') }}</v-tab>
          <v-tab value="userOauth2Settings">{{ t('userOauth2Settings') }}</v-tab>
          <v-tab value="roleAddressConfig">{{ t('roleAddressConfig') }}</v-tab>
        </v-tabs>
        <v-window v-model="userTab">
          <v-window-item value="user_management"><UserManagement /></v-window-item>
          <v-window-item value="user_settings"><UserSettings /></v-window-item>
          <v-window-item value="userOauth2Settings"><UserOauth2Settings /></v-window-item>
          <v-window-item value="roleAddressConfig"><RoleAddressConfig /></v-window-item>
        </v-window>
      </v-window-item>

      <v-window-item value="mails">
        <v-tabs v-model="mailsTab" align-tabs="center" color="primary" class="mb-4">
          <v-tab value="mails">{{ t('mails') }}</v-tab>
          <v-tab value="unknow">{{ t('unknow') }}</v-tab>
          <v-tab value="sendBox">{{ t('sendBox') }}</v-tab>
          <v-tab value="sendMail">{{ t('sendMail') }}</v-tab>
          <v-tab value="mailWebhook">{{ t('mailWebhook') }}</v-tab>
        </v-tabs>
        <v-window v-model="mailsTab">
          <v-window-item value="mails"><Mails /></v-window-item>
          <v-window-item value="unknow"><MailsUnknow /></v-window-item>
          <v-window-item value="sendBox"><SendBox /></v-window-item>
          <v-window-item value="sendMail"><SendMail /></v-window-item>
          <v-window-item value="mailWebhook"><MailWebhook /></v-window-item>
        </v-window>
      </v-window-item>

      <v-window-item value="telegram"><Telegram /></v-window-item>
      <v-window-item value="statistics"><Statistics /></v-window-item>

      <v-window-item value="maintenance">
        <v-tabs v-model="maintenanceTab" align-tabs="center" color="primary" class="mb-4">
          <v-tab value="database">{{ t('database') }}</v-tab>
          <v-tab value="workerconfig">{{ t('workerconfig') }}</v-tab>
          <v-tab value="maintenance">{{ t('maintenance') }}</v-tab>
        </v-tabs>
        <v-window v-model="maintenanceTab">
          <v-window-item value="database"><DatabaseManager /></v-window-item>
          <v-window-item value="workerconfig"><WorkerConfig /></v-window-item>
          <v-window-item value="maintenance"><Maintenance /></v-window-item>
        </v-window>
      </v-window-item>

      <v-window-item value="appearance"><Appearance /></v-window-item>
      <v-window-item value="about"><About /></v-window-item>
    </v-window>

    <v-snackbar v-model="snackbar.show" :color="snackbar.color" :timeout="2000">
      {{ snackbar.text }}
    </v-snackbar>
  </div>
</template>
