// angular_frontend/src/app/components/footer/footer.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { StateService } from '../../services/state.service';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [CommonModule],
  template: `
    <footer>
      <span>© {{ year }} {{ state.openSettings().copyright || 'NoviceLevel' }}</span>
      @if (state.openSettings().showGithub) {
        <a href="https://github.com/dreamhunter2333/cloudflare_temp_email" target="_blank" rel="noopener">
          GitHub
        </a>
      }
    </footer>
  `,
  styles: [`
    footer {
      display: flex;
      justify-content: center;
      align-items: center;
      gap: 16px;
      padding: 8px 16px;
      border-top: 1px solid var(--mat-sys-outline-variant);
      font-size: 14px;
      color: var(--mat-sys-on-surface-variant);
      
      a {
        color: var(--mat-sys-primary);
        text-decoration: none;
        
        &:hover {
          text-decoration: underline;
        }
      }
    }
  `]
})
export class FooterComponent {
  state = inject(StateService);
  year = new Date().getFullYear();
}

// frontend/src/views/Footer.vue
<script setup>
import { useI18n } from 'vue-i18n'
import { useGlobalState } from '../store'
const { openSettings } = useGlobalState()

const { t } = useI18n({
    messages: {
        en: {
            copyright: "Copyright"
        },
        zh: {
            copyright: "版权所有"
        }
    }
});
</script>

<template>
    <footer class="m3-footer">
        <div class="footer-content">
            <span class="text-on-surface-variant">
                {{ t('copyright') }} © 2023-{{ new Date().getFullYear() }}
            </span>
            <span class="text-on-surface-variant" v-html="openSettings.copyright"></span>
        </div>
    </footer>
</template>

<style scoped>
.m3-footer {
    border-top: 1px solid rgb(var(--v-theme-outline-variant));
    padding: 14px 0;
    font-size: 14px;
}

.footer-content {
    display: flex;
    justify-content: center;
    gap: 8px;
}
</style>
