// frontend-angular/src/app/views/header/header.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule } from '@angular/material/menu';
import { MatDialogModule, MatDialog, MatDialogRef } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSidenavModule } from '@angular/material/sidenav';
import { MatListModule } from '@angular/material/list';
import { TranslateModule, TranslateService } from '@ngx-translate/core';

import { GlobalStateService } from '../../services/global-state.service';
import { SnackbarService } from '../../services/snackbar.service';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatToolbarModule,
    MatButtonModule,
    MatIconModule,
    MatMenuModule,
    MatDialogModule,
    MatFormFieldModule,
    MatInputModule,
    MatSidenavModule,
    MatListModule,
    TranslateModule,
  ],
  template: `
    <mat-toolbar color="primary">
      <img src="/logo.png" alt="Logo" width="32" height="32" class="logo" (click)="logoClick()">
      <span class="title">{{ state.openSettings().title || '临时邮箱' }}</span>
      
      <span class="spacer"></span>

      <!-- Desktop Menu -->
      <ng-container *ngIf="!isMobile()">
        <button mat-button (click)="goHome()">
          <mat-icon>home</mat-icon>
          主页
        </button>
        <button mat-button (click)="goUser()">
          <mat-icon>person</mat-icon>
          用户
        </button>
        @if (state.showAdminPage()) {
          <button mat-button (click)="goAdmin()">
            <mat-icon>admin_panel_settings</mat-icon>
            Admin
          </button>
        }
        <button mat-button (click)="toggleTheme()">
          <mat-icon>{{ isDark() ? 'light_mode' : 'dark_mode' }}</mat-icon>
          {{ isDark() ? '亮色' : '暗色' }}
        </button>
        <button mat-button (click)="toggleLang()">
          <mat-icon>translate</mat-icon>
          {{ currentLang() === 'zh' ? 'English' : '中文' }}
        </button>
        @if (state.openSettings().showGithub) {
          <a mat-button href="https://github.com/dreamhunter2333/cloudflare_temp_email" target="_blank">
            <mat-icon>code</mat-icon>
            Github
          </a>
        }
      </ng-container>

      <!-- Mobile Menu Button -->
      @if (isMobile()) {
        <button mat-icon-button (click)="showMobileMenu.set(!showMobileMenu())">
          <mat-icon>menu</mat-icon>
        </button>
      }
    </mat-toolbar>

    <!-- Mobile Menu -->
    @if (isMobile() && showMobileMenu()) {
      <div class="mobile-menu">
        <mat-nav-list>
          <mat-list-item (click)="goHome()">
            <mat-icon matListItemIcon>home</mat-icon>
            <span matListItemTitle>主页</span>
          </mat-list-item>
          <mat-list-item (click)="goUser()">
            <mat-icon matListItemIcon>person</mat-icon>
            <span matListItemTitle>用户</span>
          </mat-list-item>
          @if (state.showAdminPage()) {
            <mat-list-item (click)="goAdmin()">
              <mat-icon matListItemIcon>admin_panel_settings</mat-icon>
              <span matListItemTitle>Admin</span>
            </mat-list-item>
          }
          <mat-list-item (click)="toggleTheme()">
            <mat-icon matListItemIcon>{{ isDark() ? 'light_mode' : 'dark_mode' }}</mat-icon>
            <span matListItemTitle>{{ isDark() ? '亮色' : '暗色' }}</span>
          </mat-list-item>
          <mat-list-item (click)="toggleLang()">
            <mat-icon matListItemIcon>translate</mat-icon>
            <span matListItemTitle>{{ currentLang() === 'zh' ? 'English' : '中文' }}</span>
          </mat-list-item>
        </mat-nav-list>
      </div>
    }
  `,
  styles: [`
    .logo {
      cursor: pointer;
      margin-right: 8px;
    }
    .title {
      font-size: 18px;
    }
    .spacer {
      flex: 1 1 auto;
    }
    .mobile-menu {
      position: absolute;
      top: 64px;
      left: 0;
      right: 0;
      background: var(--mat-sys-surface);
      z-index: 1000;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
  `]
})
export class HeaderComponent implements OnInit {
  state = inject(GlobalStateService);
  private router = inject(Router);
  private translate = inject(TranslateService);
  private snackbar = inject(SnackbarService);
  private dialog = inject(MatDialog);

  showMobileMenu = signal(false);
  currentLang = signal('zh');
  logoClickCount = 0;

  // 使用 GlobalStateService 的 isDark
  isDark = () => this.state.isDark();

  isMobile(): boolean {
    return window.innerWidth < 768;
  }

  async ngOnInit() {
    // 检查是否需要显示认证对话框
    if (this.state.showAuth()) {
      this.openAuthDialog();
    }
  }

  openAuthDialog() {
    const dialogRef = this.dialog.open(AuthDialogComponent, {
      width: '400px',
      disableClose: true
    });
    dialogRef.afterClosed().subscribe(password => {
      if (password) {
        this.state.setAuth(password);
        location.reload();
      }
    });
  }

  goHome() {
    this.router.navigate(['/']);
    this.showMobileMenu.set(false);
  }

  goUser() {
    this.router.navigate(['/user']);
    this.showMobileMenu.set(false);
  }

  goAdmin() {
    this.router.navigate(['/admin']);
    this.showMobileMenu.set(false);
  }

  toggleTheme() {
    this.state.toggleDark();
    document.body.classList.toggle('dark-theme', this.state.isDark());
    this.showMobileMenu.set(false);
  }

  toggleLang() {
    const newLang = this.currentLang() === 'zh' ? 'en' : 'zh';
    this.currentLang.set(newLang);
    this.translate.use(newLang);
    this.showMobileMenu.set(false);
  }

  logoClick() {
    this.logoClickCount++;
    if (this.logoClickCount >= 5) {
      this.logoClickCount = 0;
      this.router.navigate(['/admin']);
    } else {
      this.snackbar.info(`再点击 ${5 - this.logoClickCount} 次进入管理页面`);
    }
  }
}

// Auth Dialog Component
@Component({
  selector: 'app-auth-dialog',
  standalone: true,
  imports: [CommonModule, FormsModule, MatDialogModule, MatButtonModule, MatFormFieldModule, MatInputModule],
  template: `
    <h2 mat-dialog-title>访问密码</h2>
    <mat-dialog-content>
      <p>请输入站点访问密码</p>
      <mat-form-field appearance="outline" class="full-width">
        <mat-label>密码</mat-label>
        <input matInput type="password" [(ngModel)]="password" (keyup.enter)="submit()">
      </mat-form-field>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-raised-button color="primary" (click)="submit()">确定</button>
    </mat-dialog-actions>
  `,
  styles: [`.full-width { width: 100%; }`]
})
export class AuthDialogComponent {
  private dialogRef = inject(MatDialogRef<AuthDialogComponent>);
  password = '';

  submit() {
    this.dialogRef.close(this.password);
  }
}

// frontend/src/views/Header.vue
<script setup>
import { ref, computed, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { useHead } from '@unhead/vue'
import { useRoute, useRouter } from 'vue-router'
import { useIsMobile } from '../utils/composables'

import { useGlobalState } from '../store'
import { api } from '../api'
import { getRouterPathWithLang } from '../utils'

const snackbar = ref(false)
const snackbarText = ref('')
const snackbarColor = ref('info')

const showMessage = (text, color = 'info') => {
  snackbarText.value = text
  snackbarColor.value = color
  snackbar.value = true
}

const {
    toggleDark, isDark, isTelegram, showAdminPage,
    showAuth, auth, loading, openSettings, userSettings
} = useGlobalState()
const route = useRoute()
const router = useRouter()
const isMobile = useIsMobile()

const showMobileMenu = ref(false)

const authFunc = async () => {
    try {
        location.reload()
    } catch (error) {
        showMessage(error.message || "error", 'error')
    }
}

const changeLocale = async (lang) => {
    if (lang == 'zh') {
        await router.push(route.fullPath.replace('/en', ''));
    } else {
        await router.push(`/${lang}${route.fullPath}`);
    }
}

const { locale, t } = useI18n({
    messages: {
        en: {
            title: 'Cloudflare Temp Email',
            dark: 'Dark',
            light: 'Light',
            accessHeader: 'Access Password',
            accessTip: 'Please enter the correct access password',
            home: 'Home',
            menu: 'Menu',
            user: 'User',
            ok: 'OK',
        },
        zh: {
            title: 'Cloudflare 临时邮件',
            dark: '暗色',
            light: '亮色',
            accessHeader: '访问密码',
            accessTip: '请输入站点访问密码',
            home: '主页',
            menu: '菜单',
            user: '用户',
            ok: '确定',
        }
    }
});

const version = import.meta.env.PACKAGE_VERSION ? `v${import.meta.env.PACKAGE_VERSION}` : "";

const goHome = async () => {
    await router.push(getRouterPathWithLang('/', locale.value));
    showMobileMenu.value = false;
}

const goUser = async () => {
    await router.push(getRouterPathWithLang("/user", locale.value));
    showMobileMenu.value = false;
}

const goAdmin = async () => {
    loading.value = true;
    await router.push(getRouterPathWithLang('/admin', locale.value));
    loading.value = false;
    showMobileMenu.value = false;
}

const toggleTheme = () => {
    toggleDark();
    showMobileMenu.value = false;
}

const toggleLang = async () => {
    locale.value == 'zh' ? await changeLocale('en') : await changeLocale('zh');
    showMobileMenu.value = false;
}

useHead({
    title: () => openSettings.value.title || t('title'),
    meta: [
        { name: "description", content: openSettings.value.description || t('title') },
    ]
});

const logoClickCount = ref(0);
const logoClick = async () => {
    if (route.path.includes("admin")) {
        logoClickCount.value = 0;
        return;
    }
    if (logoClickCount.value >= 5) {
        logoClickCount.value = 0;
        showMessage("Change to admin Page", 'info');
        loading.value = true;
        await router.push(getRouterPathWithLang('/admin', locale.value));
        loading.value = false;
    } else {
        logoClickCount.value++;
    }
    if (logoClickCount.value > 0) {
        showMessage(`Click ${5 - logoClickCount.value + 1} times to enter the admin page`, 'info');
    }
}

// Mock message/notification for api calls
const message = {
    error: (text) => showMessage(text, 'error'),
    info: (text) => showMessage(text, 'info'),
    success: (text) => showMessage(text, 'success'),
}
const notification = {
    info: (opts) => {
        if (opts.content) {
            showMessage('Announcement', 'info')
        }
    }
}

onMounted(async () => {
    await api.getOpenSettings(message, notification);
    if (!userSettings.value.user_id) await api.getUserSettings(message);
});
</script>

<template>
    <div>
        <v-app-bar color="primary" density="comfortable">
            <template v-slot:prepend>
                <v-avatar @click="logoClick" class="cursor-pointer ml-2">
                    <v-img src="/logo.png" alt="Logo"></v-img>
                </v-avatar>
            </template>

            <v-app-bar-title>{{ openSettings.title || t('title') }}</v-app-bar-title>

            <template v-slot:append>
                <!-- Desktop Menu -->
                <template v-if="!isMobile">
                    <v-btn variant="text" @click="goHome">
                        <v-icon start>mdi-home</v-icon>
                        {{ t('home') }}
                    </v-btn>
                    <v-btn v-if="!isTelegram" variant="text" @click="goUser">
                        <v-icon start>mdi-account</v-icon>
                        {{ t('user') }}
                    </v-btn>
                    <v-btn v-if="showAdminPage" variant="text" @click="goAdmin">
                        <v-icon start>mdi-shield-account</v-icon>
                        Admin
                    </v-btn>
                    <v-btn variant="text" @click="toggleTheme">
                        <v-icon start>{{ isDark ? 'mdi-white-balance-sunny' : 'mdi-moon-waning-crescent' }}</v-icon>
                        {{ isDark ? t('light') : t('dark') }}
                    </v-btn>
                    <v-btn variant="text" @click="toggleLang">
                        <v-icon start>mdi-translate</v-icon>
                        {{ locale == 'zh' ? 'English' : '中文' }}
                    </v-btn>
                    <v-btn v-if="openSettings?.showGithub" variant="text" 
                        href="https://github.com/dreamhunter2333/cloudflare_temp_email" target="_blank">
                        <v-icon start>mdi-github</v-icon>
                        {{ version || 'Github' }}
                    </v-btn>
                </template>

                <!-- Mobile Menu Button -->
                <v-btn v-else icon @click="showMobileMenu = !showMobileMenu">
                    <v-icon>mdi-menu</v-icon>
                </v-btn>
            </template>
        </v-app-bar>

        <!-- Mobile Navigation Drawer -->
        <v-navigation-drawer v-model="showMobileMenu" location="top" temporary>
            <v-list>
                <v-list-item prepend-icon="mdi-home" :title="t('home')" @click="goHome"></v-list-item>
                <v-list-item v-if="!isTelegram" prepend-icon="mdi-account" :title="t('user')" @click="goUser"></v-list-item>
                <v-list-item v-if="showAdminPage" prepend-icon="mdi-shield-account" title="Admin" @click="goAdmin"></v-list-item>
                <v-list-item :prepend-icon="isDark ? 'mdi-white-balance-sunny' : 'mdi-moon-waning-crescent'" 
                    :title="isDark ? t('light') : t('dark')" @click="toggleTheme"></v-list-item>
                <v-list-item prepend-icon="mdi-translate" :title="locale == 'zh' ? 'English' : '中文'" @click="toggleLang"></v-list-item>
                <v-list-item v-if="openSettings?.showGithub" prepend-icon="mdi-github" :title="version || 'Github'"
                    href="https://github.com/dreamhunter2333/cloudflare_temp_email" target="_blank"></v-list-item>
            </v-list>
        </v-navigation-drawer>

        <!-- Access Password Dialog -->
        <v-dialog v-model="showAuth" persistent max-width="400">
            <v-card>
                <v-card-title>{{ t('accessHeader') }}</v-card-title>
                <v-card-text>
                    <p class="mb-4">{{ t('accessTip') }}</p>
                    <v-text-field v-model="auth" type="password" 
                        :append-inner-icon="'mdi-eye'"
                        variant="outlined" density="compact"></v-text-field>
                </v-card-text>
                <v-card-actions>
                    <v-spacer></v-spacer>
                    <v-btn color="primary" :loading="loading" @click="authFunc">
                        {{ t('ok') }}
                    </v-btn>
                </v-card-actions>
            </v-card>
        </v-dialog>

        <!-- Snackbar for messages -->
        <v-snackbar v-model="snackbar" :color="snackbarColor" timeout="3000">
            {{ snackbarText }}
            <template v-slot:actions>
                <v-btn variant="text" @click="snackbar = false">Close</v-btn>
            </template>
        </v-snackbar>
    </div>
</template>

<style scoped>
.cursor-pointer {
    cursor: pointer;
}
</style>
